//! **What a notification says, in the language the reader chose** — generated, do not edit.
//!
//! Written by `scripts/gen-notify-wording.mjs` out of `app/src/core/i18n/locales`, which is where
//! the nineteen languages are already kept. Editing this file instead of the dictionary puts the two
//! out of step, and `guards/check-notify-wording-fresh.sh` is what notices.
//!
//! Run `make notify-wording` after moving a `notify.*` key or a status label, and commit what moves.

/// One language's side of a notification: a sentence per key, and Amenbo's own word for each state.
///
/// Both are sorted by key, and a language that has not translated a key simply has no pair for it —
/// [`crate::notify_wording`] falls back to English one key at a time, so a half-written dictionary
/// costs that one sentence rather than the whole language.
pub(crate) struct Wording {
    pub(crate) language: &'static str,
    pub(crate) says: &'static [(&'static str, &'static str)],
    pub(crate) statuses: &'static [(&'static str, &'static str)],
}

/// Every language a line can be written in, in the order the dictionaries are named.
pub(crate) const WORDINGS: &[Wording] = &[
    Wording {
        language: "de",
        says: &[
            ("commentAdded", "{who} hat {what} kommentiert"),
            ("commentAddedBare", "{who} hat {what} hinzugefügt"),
            ("commentRemoved", "{who} hat einen Kommentar zu {what} zurückgenommen"),
            ("commentRemovedBare", "{who} hat {what} zurückgenommen"),
            ("decisionAccepted", "{who} hat {what} angenommen"),
            ("decisionRejected", "{who} hat {what} abgelehnt"),
            ("statusChanged", "{who} hat {what} auf {state} gesetzt"),
            ("statusChangedBare", "{who} hat den Status von {what} geändert"),
            ("taskAssigned", "{who} hat {what} an {state} übergeben"),
            ("taskAssignedBare", "{who} hat {what} zugewiesen"),
            ("taskCreated", "{who} hat {what} erstellt"),
            ("taskDeleted", "{who} hat {what} gelöscht"),
            ("taskDone", "{who} hat {what} erledigt"),
            ("taskDue", "{what} ist fällig"),
            ("taskDueTomorrow", "{what} ist morgen fällig"),
            ("taskMoved", "{who} hat {what} nach {state} verschoben"),
            ("taskMovedBare", "{who} hat {what} in ein anderes Projekt verschoben"),
            ("taskRejected", "{who} hat entschieden, {what} nicht zu machen"),
            ("test", "Testnachricht von Amenbo — dieses Projekt meldet hierher."),
            ("unknown", "{who} hat etwas an {what} gemacht ({event})"),
        ],
        statuses: &[
            ("blocked", "Blockiert"),
            ("done", "Erledigt"),
            ("in_progress", "In Arbeit"),
            ("rejected", "Verworfen"),
            ("todo", "Offen"),
        ],
    },
    Wording {
        language: "en",
        says: &[
            ("commentAdded", "{who} added a comment on {what}"),
            ("commentAddedBare", "{who} added {what}"),
            ("commentRemoved", "{who} took back a comment on {what}"),
            ("commentRemovedBare", "{who} took back {what}"),
            ("decisionAccepted", "{who} accepted {what}"),
            ("decisionRejected", "{who} rejected {what}"),
            ("statusChanged", "{who} moved {what} to {state}"),
            ("statusChangedBare", "{who} moved {what}"),
            ("taskAssigned", "{who} assigned {what} to {state}"),
            ("taskAssignedBare", "{who} assigned {what}"),
            ("taskCreated", "{who} created {what}"),
            ("taskDeleted", "{who} deleted {what}"),
            ("taskDone", "{who} finished {what}"),
            ("taskDue", "{what} is due"),
            ("taskDueTomorrow", "{what} is due tomorrow"),
            ("taskMoved", "{who} moved {what} into {state}"),
            ("taskMovedBare", "{who} moved {what} to another project"),
            ("taskRejected", "{who} decided against {what}"),
            ("test", "Test message from Amenbo — this project reports here."),
            ("unknown", "{who} acted on {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Blocked"),
            ("done", "Done"),
            ("in_progress", "In progress"),
            ("rejected", "Rejected"),
            ("todo", "To do"),
        ],
    },
    Wording {
        language: "es",
        says: &[
            ("commentAdded", "{who} comentó en {what}"),
            ("commentAddedBare", "{who} añadió {what}"),
            ("commentRemoved", "{who} retiró un comentario de {what}"),
            ("commentRemovedBare", "{who} retiró {what}"),
            ("decisionAccepted", "{who} aceptó {what}"),
            ("decisionRejected", "{who} rechazó {what}"),
            ("statusChanged", "{who} cambió {what} a {state}"),
            ("statusChangedBare", "{who} cambió el estado de {what}"),
            ("taskAssigned", "{who} asignó {what} a {state}"),
            ("taskAssignedBare", "{who} asignó {what}"),
            ("taskCreated", "{who} creó {what}"),
            ("taskDeleted", "{who} eliminó {what}"),
            ("taskDone", "{who} terminó {what}"),
            ("taskDue", "El plazo de {what} ha llegado"),
            ("taskDueTomorrow", "El plazo de {what} es mañana"),
            ("taskMoved", "{who} movió {what} a {state}"),
            ("taskMovedBare", "{who} movió {what} a otro proyecto"),
            ("taskRejected", "{who} decidió no hacer {what}"),
            ("test", "Mensaje de prueba de Amenbo: este proyecto informa aquí."),
            ("unknown", "{who} hizo algo en {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Bloqueado"),
            ("done", "Hecho"),
            ("in_progress", "En curso"),
            ("rejected", "Descartado"),
            ("todo", "Pendiente"),
        ],
    },
    Wording {
        language: "fr",
        says: &[
            ("commentAdded", "{who} a commenté {what}"),
            ("commentAddedBare", "{who} a ajouté {what}"),
            ("commentRemoved", "{who} a retiré un commentaire sur {what}"),
            ("commentRemovedBare", "{who} a retiré {what}"),
            ("decisionAccepted", "{who} a accepté {what}"),
            ("decisionRejected", "{who} a rejeté {what}"),
            ("statusChanged", "{who} a fait passer {what} à {state}"),
            ("statusChangedBare", "{who} a changé l'état de {what}"),
            ("taskAssigned", "{who} a affecté {what} à {state}"),
            ("taskAssignedBare", "{who} a affecté {what}"),
            ("taskCreated", "{who} a créé {what}"),
            ("taskDeleted", "{who} a supprimé {what}"),
            ("taskDone", "{who} a terminé {what}"),
            ("taskDue", "L'échéance de {what} est arrivée"),
            ("taskDueTomorrow", "L'échéance de {what} est demain"),
            ("taskMoved", "{who} a déplacé {what} vers {state}"),
            ("taskMovedBare", "{who} a déplacé {what} vers un autre projet"),
            ("taskRejected", "{who} a décidé de ne pas faire {what}"),
            ("test", "Message de test d'Amenbo — ce projet rend compte ici."),
            ("unknown", "{who} est intervenu sur {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Bloquée"),
            ("done", "Terminée"),
            ("in_progress", "En cours"),
            ("rejected", "Écartée"),
            ("todo", "À faire"),
        ],
    },
    Wording {
        language: "hi",
        says: &[
            ("commentAdded", "{who} ने {what} पर टिप्पणी की"),
            ("commentAddedBare", "{who} ने {what} जोड़ा"),
            ("commentRemoved", "{who} ने {what} पर की टिप्पणी वापस ली"),
            ("commentRemovedBare", "{who} ने {what} वापस लिया"),
            ("decisionAccepted", "{who} ने {what} स्वीकार किया"),
            ("decisionRejected", "{who} ने {what} अस्वीकार किया"),
            ("statusChanged", "{who} ने {what} को {state} किया"),
            ("statusChangedBare", "{who} ने {what} की स्थिति बदली"),
            ("taskAssigned", "{who} ने {what} {state} को सौंपा"),
            ("taskAssignedBare", "{who} ने {what} सौंपा"),
            ("taskCreated", "{who} ने {what} बनाया"),
            ("taskDeleted", "{who} ने {what} मिटाया"),
            ("taskDone", "{who} ने {what} पूरा किया"),
            ("taskDue", "{what} की समय-सीमा आ गई है"),
            ("taskDueTomorrow", "{what} की समय-सीमा कल है"),
            ("taskMoved", "{who} ने {what} को {state} में डाला"),
            ("taskMovedBare", "{who} ने {what} को दूसरे प्रोजेक्ट में डाला"),
            ("taskRejected", "{who} ने {what} न करने का तय किया"),
            ("test", "Amenbo से परीक्षण संदेश — यह प्रोजेक्ट यहीं बताएगा।"),
            ("unknown", "{who} ने {what} पर कुछ किया ({event})"),
        ],
        statuses: &[
            ("blocked", "रुका हुआ"),
            ("done", "पूरा"),
            ("in_progress", "चल रहा है"),
            ("rejected", "अस्वीकृत"),
            ("todo", "करना है"),
        ],
    },
    Wording {
        language: "id",
        says: &[
            ("commentAdded", "{who} mengomentari {what}"),
            ("commentAddedBare", "{who} menambahkan {what}"),
            ("commentRemoved", "{who} menarik komentar pada {what}"),
            ("commentRemovedBare", "{who} menarik {what}"),
            ("decisionAccepted", "{who} menerima {what}"),
            ("decisionRejected", "{who} menolak {what}"),
            ("statusChanged", "{who} mengubah {what} menjadi {state}"),
            ("statusChangedBare", "{who} mengubah status {what}"),
            ("taskAssigned", "{who} menugaskan {what} ke {state}"),
            ("taskAssignedBare", "{who} menugaskan {what}"),
            ("taskCreated", "{who} membuat {what}"),
            ("taskDeleted", "{who} menghapus {what}"),
            ("taskDone", "{who} menyelesaikan {what}"),
            ("taskDue", "{what} sudah jatuh tempo"),
            ("taskDueTomorrow", "{what} jatuh tempo besok"),
            ("taskMoved", "{who} memindahkan {what} ke {state}"),
            ("taskMovedBare", "{who} memindahkan {what} ke proyek lain"),
            ("taskRejected", "{who} memutuskan tidak mengerjakan {what}"),
            ("test", "Pesan uji dari Amenbo — proyek ini melapor ke sini."),
            ("unknown", "{who} melakukan sesuatu pada {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Terhambat"),
            ("done", "Selesai"),
            ("in_progress", "Sedang dikerjakan"),
            ("rejected", "Ditolak"),
            ("todo", "Akan dikerjakan"),
        ],
    },
    Wording {
        language: "it",
        says: &[
            ("commentAdded", "{who} ha commentato {what}"),
            ("commentAddedBare", "{who} ha aggiunto {what}"),
            ("commentRemoved", "{who} ha ritirato un commento su {what}"),
            ("commentRemovedBare", "{who} ha ritirato {what}"),
            ("decisionAccepted", "{who} ha accettato {what}"),
            ("decisionRejected", "{who} ha respinto {what}"),
            ("statusChanged", "{who} ha portato {what} a {state}"),
            ("statusChangedBare", "{who} ha cambiato lo stato di {what}"),
            ("taskAssigned", "{who} ha assegnato {what} a {state}"),
            ("taskAssignedBare", "{who} ha assegnato {what}"),
            ("taskCreated", "{who} ha creato {what}"),
            ("taskDeleted", "{who} ha eliminato {what}"),
            ("taskDone", "{who} ha completato {what}"),
            ("taskDue", "{what} è in scadenza"),
            ("taskDueTomorrow", "{what} scade domani"),
            ("taskMoved", "{who} ha spostato {what} in {state}"),
            ("taskMovedBare", "{who} ha spostato {what} in un altro progetto"),
            ("taskRejected", "{who} ha deciso di non fare {what}"),
            ("test", "Messaggio di prova da Amenbo — questo progetto riferisce qui."),
            ("unknown", "{who} è intervenuto su {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Bloccata"),
            ("done", "Fatta"),
            ("in_progress", "In corso"),
            ("rejected", "Scartata"),
            ("todo", "Da fare"),
        ],
    },
    Wording {
        language: "ja",
        says: &[
            ("commentAdded", "{who} が {what} にコメントしました"),
            ("commentAddedBare", "{who} が {what} を追加しました"),
            ("commentRemoved", "{who} が {what} のコメントを取り消しました"),
            ("commentRemovedBare", "{who} が {what} を取り消しました"),
            ("decisionAccepted", "{who} が {what} を採択しました"),
            ("decisionRejected", "{who} が {what} を却下しました"),
            ("statusChanged", "{who} が {what} を{state}にしました"),
            ("statusChangedBare", "{who} が {what} のステータスを変更しました"),
            ("taskAssigned", "{who} が {what} を {state} に割り当てました"),
            ("taskAssignedBare", "{who} が {what} を割り当てました"),
            ("taskCreated", "{who} が {what} を作成しました"),
            ("taskDeleted", "{who} が {what} を削除しました"),
            ("taskDone", "{who} が {what} を完了しました"),
            ("taskDue", "{what} は期日が来ています"),
            ("taskDueTomorrow", "{what} は明日が期日です"),
            ("taskMoved", "{who} が {what} を {state} へ移動しました"),
            ("taskMovedBare", "{who} が {what} を別のプロジェクトへ移動しました"),
            ("taskRejected", "{who} が {what} を見送りました"),
            ("test", "Amenbo からのテスト送信です。このプロジェクトの通知はここに届きます。"),
            ("unknown", "{who} が {what} を操作しました（{event}）"),
        ],
        statuses: &[
            ("blocked", "ブロック"),
            ("done", "完了"),
            ("in_progress", "進行中"),
            ("rejected", "却下"),
            ("todo", "未着手"),
        ],
    },
    Wording {
        language: "ko",
        says: &[
            ("commentAdded", "{who}이(가) {what}에 댓글을 남겼습니다"),
            ("commentAddedBare", "{who}이(가) {what}을(를) 남겼습니다"),
            ("commentRemoved", "{who}이(가) {what}의 댓글을 거뒀습니다"),
            ("commentRemovedBare", "{who}이(가) {what}을(를) 거뒀습니다"),
            ("decisionAccepted", "{who}이(가) {what}을(를) 채택했습니다"),
            ("decisionRejected", "{who}이(가) {what}을(를) 기각했습니다"),
            ("statusChanged", "{who}이(가) {what}을(를) {state}(으)로 바꿨습니다"),
            ("statusChangedBare", "{who}이(가) {what}의 상태를 바꿨습니다"),
            ("taskAssigned", "{who}이(가) {what}을(를) {state}에게 맡겼습니다"),
            ("taskAssignedBare", "{who}이(가) {what}의 담당을 정했습니다"),
            ("taskCreated", "{who}이(가) {what}을(를) 만들었습니다"),
            ("taskDeleted", "{who}이(가) {what}을(를) 삭제했습니다"),
            ("taskDone", "{who}이(가) {what}을(를) 완료했습니다"),
            ("taskDue", "{what}의 기한이 되었습니다"),
            ("taskDueTomorrow", "{what}의 기한이 내일입니다"),
            ("taskMoved", "{who}이(가) {what}을(를) {state}(으)로 옮겼습니다"),
            ("taskMovedBare", "{who}이(가) {what}을(를) 다른 프로젝트로 옮겼습니다"),
            ("taskRejected", "{who}이(가) {what}을(를) 하지 않기로 했습니다"),
            ("test", "Amenbo에서 보낸 테스트 메시지입니다. 이 프로젝트는 여기로 보고합니다."),
            ("unknown", "{who}이(가) {what}에 무언가 했습니다 ({event})"),
        ],
        statuses: &[
            ("blocked", "막힘"),
            ("done", "완료"),
            ("in_progress", "진행 중"),
            ("rejected", "기각"),
            ("todo", "할 일"),
        ],
    },
    Wording {
        language: "nl",
        says: &[
            ("commentAdded", "{who} heeft op {what} gereageerd"),
            ("commentAddedBare", "{who} heeft {what} toegevoegd"),
            ("commentRemoved", "{who} heeft een reactie op {what} ingetrokken"),
            ("commentRemovedBare", "{who} heeft {what} ingetrokken"),
            ("decisionAccepted", "{who} heeft {what} aangenomen"),
            ("decisionRejected", "{who} heeft {what} afgewezen"),
            ("statusChanged", "{who} heeft {what} op {state} gezet"),
            ("statusChangedBare", "{who} heeft de status van {what} gewijzigd"),
            ("taskAssigned", "{who} heeft {what} aan {state} toegewezen"),
            ("taskAssignedBare", "{who} heeft {what} toegewezen"),
            ("taskCreated", "{who} heeft {what} aangemaakt"),
            ("taskDeleted", "{who} heeft {what} verwijderd"),
            ("taskDone", "{who} heeft {what} afgerond"),
            ("taskDue", "De deadline van {what} is bereikt"),
            ("taskDueTomorrow", "De deadline van {what} is morgen"),
            ("taskMoved", "{who} heeft {what} naar {state} verplaatst"),
            ("taskMovedBare", "{who} heeft {what} naar een ander project verplaatst"),
            ("taskRejected", "{who} heeft besloten {what} niet te doen"),
            ("test", "Testbericht van Amenbo — dit project meldt hier."),
            ("unknown", "{who} heeft iets met {what} gedaan ({event})"),
        ],
        statuses: &[
            ("blocked", "Geblokkeerd"),
            ("done", "Klaar"),
            ("in_progress", "Bezig"),
            ("rejected", "Afgewezen"),
            ("todo", "Te doen"),
        ],
    },
    Wording {
        language: "pl",
        says: &[
            ("commentAdded", "{who} skomentował(a) {what}"),
            ("commentAddedBare", "{who} dodał(a) {what}"),
            ("commentRemoved", "{who} wycofał(a) komentarz do {what}"),
            ("commentRemovedBare", "{who} wycofał(a) {what}"),
            ("decisionAccepted", "{who} przyjął(-ęła) {what}"),
            ("decisionRejected", "{who} odrzucił(a) {what}"),
            ("statusChanged", "{who} zmienił(a) {what} na {state}"),
            ("statusChangedBare", "{who} zmienił(a) status {what}"),
            ("taskAssigned", "{who} przypisał(a) {what} do {state}"),
            ("taskAssignedBare", "{who} przypisał(a) {what}"),
            ("taskCreated", "{who} utworzył(a) {what}"),
            ("taskDeleted", "{who} usunął(-ęła) {what}"),
            ("taskDone", "{who} ukończył(a) {what}"),
            ("taskDue", "Termin {what} nadszedł"),
            ("taskDueTomorrow", "Termin {what} przypada jutro"),
            ("taskMoved", "{who} umieścił(a) {what} w {state}"),
            ("taskMovedBare", "{who} umieścił(a) {what} w innym projekcie"),
            ("taskRejected", "{who} postanowił(a) nie robić {what}"),
            ("test", "Wiadomość testowa z Amenbo — ten projekt raportuje tutaj."),
            ("unknown", "{who} zrobił(a) coś z {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Zablokowane"),
            ("done", "Gotowe"),
            ("in_progress", "W toku"),
            ("rejected", "Odrzucone"),
            ("todo", "Do zrobienia"),
        ],
    },
    Wording {
        language: "pt-BR",
        says: &[
            ("commentAdded", "{who} comentou em {what}"),
            ("commentAddedBare", "{who} adicionou {what}"),
            ("commentRemoved", "{who} retirou um comentário de {what}"),
            ("commentRemovedBare", "{who} retirou {what}"),
            ("decisionAccepted", "{who} aceitou {what}"),
            ("decisionRejected", "{who} recusou {what}"),
            ("statusChanged", "{who} mudou {what} para {state}"),
            ("statusChangedBare", "{who} mudou o status de {what}"),
            ("taskAssigned", "{who} atribuiu {what} a {state}"),
            ("taskAssignedBare", "{who} definiu o responsável de {what}"),
            ("taskCreated", "{who} criou {what}"),
            ("taskDeleted", "{who} excluiu {what}"),
            ("taskDone", "{who} concluiu {what}"),
            ("taskDue", "O prazo de {what} chegou"),
            ("taskDueTomorrow", "O prazo de {what} é amanhã"),
            ("taskMoved", "{who} moveu {what} para {state}"),
            ("taskMovedBare", "{who} moveu {what} para outro projeto"),
            ("taskRejected", "{who} decidiu não fazer {what}"),
            ("test", "Mensagem de teste do Amenbo — este projeto reporta aqui."),
            ("unknown", "{who} fez algo em {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Bloqueada"),
            ("done", "Concluída"),
            ("in_progress", "Em andamento"),
            ("rejected", "Recusada"),
            ("todo", "A fazer"),
        ],
    },
    Wording {
        language: "ru",
        says: &[
            ("commentAdded", "{who} прокомментировал {what}"),
            ("commentAddedBare", "{who} добавил {what}"),
            ("commentRemoved", "{who} отозвал комментарий к {what}"),
            ("commentRemovedBare", "{who} отозвал {what}"),
            ("decisionAccepted", "{who} принял {what}"),
            ("decisionRejected", "{who} отклонил {what}"),
            ("statusChanged", "{who} перевёл {what} в статус {state}"),
            ("statusChangedBare", "{who} изменил статус {what}"),
            ("taskAssigned", "{who} назначил {state} ответственным за {what}"),
            ("taskAssignedBare", "{who} назначил ответственного за {what}"),
            ("taskCreated", "{who} создал {what}"),
            ("taskDeleted", "{who} удалил {what}"),
            ("taskDone", "{who} завершил {what}"),
            ("taskDue", "Срок {what} наступил"),
            ("taskDueTomorrow", "Срок {what} — завтра"),
            ("taskMoved", "{who} переместил {what} в {state}"),
            ("taskMovedBare", "{who} переместил {what} в другой проект"),
            ("taskRejected", "{who} решил не делать {what}"),
            ("test", "Тестовое сообщение от Amenbo — этот проект отчитывается сюда."),
            ("unknown", "{who} что-то сделал с {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Заблокировано"),
            ("done", "Готово"),
            ("in_progress", "В работе"),
            ("rejected", "Отклонено"),
            ("todo", "К выполнению"),
        ],
    },
    Wording {
        language: "th",
        says: &[
            ("commentAdded", "{who} แสดงความเห็นใน {what}"),
            ("commentAddedBare", "{who} เพิ่ม {what}"),
            ("commentRemoved", "{who} ถอนความเห็นใน {what}"),
            ("commentRemovedBare", "{who} ถอน {what}"),
            ("decisionAccepted", "{who} รับ {what} แล้ว"),
            ("decisionRejected", "{who} ตีตก {what}"),
            ("statusChanged", "{who} เปลี่ยน {what} เป็น {state}"),
            ("statusChangedBare", "{who} เปลี่ยนสถานะของ {what}"),
            ("taskAssigned", "{who} มอบหมาย {what} ให้ {state}"),
            ("taskAssignedBare", "{who} มอบหมาย {what}"),
            ("taskCreated", "{who} สร้าง {what}"),
            ("taskDeleted", "{who} ลบ {what}"),
            ("taskDone", "{who} ทำ {what} เสร็จแล้ว"),
            ("taskDue", "{what} ถึงกำหนดแล้ว"),
            ("taskDueTomorrow", "{what} ถึงกำหนดพรุ่งนี้"),
            ("taskMoved", "{who} ย้าย {what} ไปที่ {state}"),
            ("taskMovedBare", "{who} ย้าย {what} ไปโปรเจกต์อื่น"),
            ("taskRejected", "{who} ตัดสินใจไม่ทำ {what}"),
            ("test", "ข้อความทดสอบจาก Amenbo — โปรเจกต์นี้จะรายงานมาที่นี่"),
            ("unknown", "{who} ทำบางอย่างกับ {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "ติดขัด"),
            ("done", "เสร็จแล้ว"),
            ("in_progress", "กำลังทำ"),
            ("rejected", "ตีตก"),
            ("todo", "รอทำ"),
        ],
    },
    Wording {
        language: "tr",
        says: &[
            ("commentAdded", "{who}, {what} kaydına yorum yaptı"),
            ("commentAddedBare", "{who}, {what} ekledi"),
            ("commentRemoved", "{who}, {what} kaydındaki yorumu geri aldı"),
            ("commentRemovedBare", "{who}, {what} geri aldı"),
            ("decisionAccepted", "{who}, {what} kararını kabul etti"),
            ("decisionRejected", "{who}, {what} kararını reddetti"),
            ("statusChanged", "{who}, {what} kaydını {state} durumuna geçirdi"),
            ("statusChangedBare", "{who}, {what} kaydının durumunu değiştirdi"),
            ("taskAssigned", "{who}, {what} kaydını {state} kullanıcısına verdi"),
            ("taskAssignedBare", "{who}, {what} kaydının sorumlusunu belirledi"),
            ("taskCreated", "{who}, {what} kaydını oluşturdu"),
            ("taskDeleted", "{who}, {what} kaydını sildi"),
            ("taskDone", "{who}, {what} kaydını bitirdi"),
            ("taskDue", "{what} kaydının teslim tarihi geldi"),
            ("taskDueTomorrow", "{what} kaydının teslim tarihi yarın"),
            ("taskMoved", "{who}, {what} kaydını {state} projesine taşıdı"),
            ("taskMovedBare", "{who}, {what} kaydını başka bir projeye taşıdı"),
            ("taskRejected", "{who}, {what} kaydını yapmamaya karar verdi"),
            ("test", "Amenbo'dan test mesajı — bu proje buraya bildiriyor."),
            ("unknown", "{who}, {what} üzerinde bir işlem yaptı ({event})"),
        ],
        statuses: &[
            ("blocked", "Engelli"),
            ("done", "Bitti"),
            ("in_progress", "Sürüyor"),
            ("rejected", "Reddedildi"),
            ("todo", "Yapılacak"),
        ],
    },
    Wording {
        language: "uk",
        says: &[
            ("commentAdded", "{who} прокоментував {what}"),
            ("commentAddedBare", "{who} додав {what}"),
            ("commentRemoved", "{who} відкликав коментар до {what}"),
            ("commentRemovedBare", "{who} відкликав {what}"),
            ("decisionAccepted", "{who} прийняв {what}"),
            ("decisionRejected", "{who} відхилив {what}"),
            ("statusChanged", "{who} перевів {what} у статус {state}"),
            ("statusChangedBare", "{who} змінив статус {what}"),
            ("taskAssigned", "{who} призначив {state} відповідальним за {what}"),
            ("taskAssignedBare", "{who} призначив відповідального за {what}"),
            ("taskCreated", "{who} створив {what}"),
            ("taskDeleted", "{who} видалив {what}"),
            ("taskDone", "{who} завершив {what}"),
            ("taskDue", "Термін {what} настав"),
            ("taskDueTomorrow", "Термін {what} — завтра"),
            ("taskMoved", "{who} перемістив {what} до {state}"),
            ("taskMovedBare", "{who} перемістив {what} до іншого проєкту"),
            ("taskRejected", "{who} вирішив не робити {what}"),
            ("test", "Тестове повідомлення від Amenbo — цей проєкт звітує сюди."),
            ("unknown", "{who} щось зробив з {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Заблоковано"),
            ("done", "Готово"),
            ("in_progress", "У роботі"),
            ("rejected", "Відхилено"),
            ("todo", "До виконання"),
        ],
    },
    Wording {
        language: "vi",
        says: &[
            ("commentAdded", "{who} đã bình luận về {what}"),
            ("commentAddedBare", "{who} đã thêm {what}"),
            ("commentRemoved", "{who} đã rút lại bình luận về {what}"),
            ("commentRemovedBare", "{who} đã rút lại {what}"),
            ("decisionAccepted", "{who} đã chấp nhận {what}"),
            ("decisionRejected", "{who} đã bác {what}"),
            ("statusChanged", "{who} đã chuyển {what} sang {state}"),
            ("statusChangedBare", "{who} đã đổi trạng thái của {what}"),
            ("taskAssigned", "{who} đã giao {what} cho {state}"),
            ("taskAssignedBare", "{who} đã giao {what}"),
            ("taskCreated", "{who} đã tạo {what}"),
            ("taskDeleted", "{who} đã xoá {what}"),
            ("taskDone", "{who} đã hoàn thành {what}"),
            ("taskDue", "{what} đã đến hạn"),
            ("taskDueTomorrow", "{what} đến hạn vào ngày mai"),
            ("taskMoved", "{who} đã chuyển {what} sang dự án {state}"),
            ("taskMovedBare", "{who} đã chuyển {what} sang dự án khác"),
            ("taskRejected", "{who} đã quyết định không làm {what}"),
            ("test", "Tin nhắn thử từ Amenbo — dự án này sẽ báo về đây."),
            ("unknown", "{who} đã tác động đến {what} ({event})"),
        ],
        statuses: &[
            ("blocked", "Bị chặn"),
            ("done", "Xong"),
            ("in_progress", "Đang làm"),
            ("rejected", "Bị bác"),
            ("todo", "Cần làm"),
        ],
    },
    Wording {
        language: "zh-Hans",
        says: &[
            ("commentAdded", "{who} 评论了 {what}"),
            ("commentAddedBare", "{who} 添加了 {what}"),
            ("commentRemoved", "{who} 撤回了对 {what} 的评论"),
            ("commentRemovedBare", "{who} 撤回了 {what}"),
            ("decisionAccepted", "{who} 采纳了 {what}"),
            ("decisionRejected", "{who} 否决了 {what}"),
            ("statusChanged", "{who} 把 {what} 改为{state}"),
            ("statusChangedBare", "{who} 修改了 {what} 的状态"),
            ("taskAssigned", "{who} 把 {what} 分配给了 {state}"),
            ("taskAssignedBare", "{who} 分配了 {what}"),
            ("taskCreated", "{who} 创建了 {what}"),
            ("taskDeleted", "{who} 删除了 {what}"),
            ("taskDone", "{who} 完成了 {what}"),
            ("taskDue", "{what} 已到期"),
            ("taskDueTomorrow", "{what} 明天到期"),
            ("taskMoved", "{who} 把 {what} 移动到了 {state}"),
            ("taskMovedBare", "{who} 把 {what} 移动到了另一个项目"),
            ("taskRejected", "{who} 决定不做 {what}"),
            ("test", "来自 Amenbo 的测试消息——这个项目会报告到这里。"),
            ("unknown", "{who} 对 {what} 做了操作（{event}）"),
        ],
        statuses: &[
            ("blocked", "受阻"),
            ("done", "已完成"),
            ("in_progress", "进行中"),
            ("rejected", "已否决"),
            ("todo", "待办"),
        ],
    },
    Wording {
        language: "zh-Hant",
        says: &[
            ("commentAdded", "{who} 評論了 {what}"),
            ("commentAddedBare", "{who} 新增了 {what}"),
            ("commentRemoved", "{who} 撤回了對 {what} 的評論"),
            ("commentRemovedBare", "{who} 撤回了 {what}"),
            ("decisionAccepted", "{who} 採納了 {what}"),
            ("decisionRejected", "{who} 否決了 {what}"),
            ("statusChanged", "{who} 把 {what} 改成{state}"),
            ("statusChangedBare", "{who} 修改了 {what} 的狀態"),
            ("taskAssigned", "{who} 把 {what} 指派給了 {state}"),
            ("taskAssignedBare", "{who} 指派了 {what}"),
            ("taskCreated", "{who} 建立了 {what}"),
            ("taskDeleted", "{who} 刪除了 {what}"),
            ("taskDone", "{who} 完成了 {what}"),
            ("taskDue", "{what} 已到期"),
            ("taskDueTomorrow", "{what} 明天到期"),
            ("taskMoved", "{who} 把 {what} 移動到了 {state}"),
            ("taskMovedBare", "{who} 把 {what} 移動到了另一個專案"),
            ("taskRejected", "{who} 決定不做 {what}"),
            ("test", "來自 Amenbo 的測試訊息——這個專案會報告到這裡。"),
            ("unknown", "{who} 對 {what} 做了操作（{event}）"),
        ],
        statuses: &[
            ("blocked", "受阻"),
            ("done", "已完成"),
            ("in_progress", "進行中"),
            ("rejected", "已否決"),
            ("todo", "待辦"),
        ],
    },
];
