//! **What a notification says, in the language the reader chose** — generated, do not edit.
//!
//! Written by `scripts/gen-notify-wording.mjs` out of `app/src/core/i18n/locales`, which is where
//! the nineteen languages are already kept. Editing this file instead of the dictionary puts the two
//! out of step, and `guards/check-notify-wording-fresh.sh` is what notices.
//!
//! Run `make notify-wording` after moving a `notify.*` or `auto.say.*` key or a status label, and commit what moves.

/// One language's side of a notification: a sentence per key, and Amenbo's own word for each state —
/// and the sentences of the line a stopped run leaves on its task ([`crate::run_wording`]).
///
/// All three are sorted by key, and a language that has not translated a key simply has no pair for it —
/// [`crate::notify_wording`] falls back to English one key at a time, so a half-written dictionary
/// costs that one sentence rather than the whole language.
pub(crate) struct Wording {
    pub(crate) language: &'static str,
    pub(crate) says: &'static [(&'static str, &'static str)],
    pub(crate) runs: &'static [(&'static str, &'static str)],
    pub(crate) statuses: &'static [(&'static str, &'static str)],
}

/// Every language a line can be written in, in the order the dictionaries are named.
pub(crate) const WORDINGS: &[Wording] = &[
    Wording {
        language: "de",
        says: &[
            ("commentAdded", "{who} hat {what} kommentiert"),
            ("commentAddedBare", "{who} hat {what} hinzugefügt"),
            ("commentRemoved", "{who} hat einen Kommentar zu {what} zurückgenommen"),
            ("commentRemovedBare", "{who} hat {what} zurückgenommen"),
            ("decisionAccepted", "{who} hat {what} fertig geschrieben"),
            ("decisionRejected", "{who} hat {what} abgelehnt"),
            ("statusChanged", "{who} hat {what} auf {state} gesetzt"),
            ("statusChangedBare", "{who} hat den Status von {what} geändert"),
            ("subject.commentAdded", "Kommentar hinzugefügt"),
            ("subject.commentRemoved", "Kommentar zurückgenommen"),
            ("subject.count", "{n} Änderungen"),
            ("subject.countOne", "{n} Änderung"),
            ("subject.decisionAccepted", "Entscheidung fertig geschrieben"),
            ("subject.decisionRejected", "Entscheidung abgelehnt"),
            ("subject.statusChanged", "Aufgabe auf {state}"),
            ("subject.statusChangedBare", "Aufgabenstatus geändert"),
            ("subject.taskAssigned", "Aufgabe neu zugewiesen"),
            ("subject.taskCreated", "Aufgabe erstellt"),
            ("subject.taskDeleted", "Aufgabe gelöscht"),
            ("subject.taskDone", "Aufgabe abgeschlossen"),
            ("subject.taskDue", "Aufgabe fällig"),
            ("subject.taskDueTomorrow", "Aufgabe morgen fällig"),
            ("subject.taskMoved", "Aufgabe verschoben"),
            ("subject.taskRejected", "Aufgabe verworfen"),
            ("taskAssigned", "{who} hat {what} an {state} übergeben"),
            ("taskAssignedBare", "{who} hat {what} zugewiesen"),
            ("taskCreated", "{who} hat {what} erstellt"),
            ("taskDeleted", "{who} hat {what} gelöscht"),
            ("taskDone", "{who} hat {what} erledigt"),
            ("taskDue", "{what} ist fällig"),
            ("taskDueTomorrow", "{what} ist morgen fällig"),
            ("taskMoved", "{who} hat {what} nach {state} verschoben"),
            ("taskMovedBare", "{who} hat {what} in ein anderes Projekt verschoben"),
            ("taskRejected", "{who} hat entschieden, {what} nicht zu machen"),
            ("test", "Testnachricht von Amenbo — dieses Projekt meldet hierher."),
            ("unknown", "{who} hat etwas an {what} gemacht ({event})"),
        ],
        runs: &[
            ("canceled", "Ein Automationslauf wurde abgebrochen."),
            ("completed", "Ein Automationslauf wurde abgeschlossen."),
            ("crashed", "Ein Automationslauf ist fehlgeschlagen: Ein Schritt endete ohne Bericht – sein Programm wurde beendet, oder Amenbo wurde während des Laufs neu gestartet."),
            ("halted", "Ein Automationslauf hat angehalten, um einen Menschen zu rufen: Ein Schritt nahm einen Ausgang, der nach einem Menschen ruft."),
            ("leftTaskOpen", "Ein Automationslauf ist fehlgeschlagen: Er ging weiter, ohne die übernommene Aufgabe abzuschließen."),
            ("line", "{why} {reached} (Lauf {run})"),
            ("maxTimes", "Ein Automationslauf ist fehlgeschlagen: Ein Rückweg wurde so oft genommen, wie es erlaubt ist."),
            ("noAgent", "Ein Automationslauf ist fehlgeschlagen: Der Agent, den ein Schritt verlangt hat, konnte nicht gestartet werden."),
            ("noInput", "Ein Automationslauf ist fehlgeschlagen: Eine Pflichteingabe eines Schritts war leer."),
            ("noWayOn", "Ein Automationslauf ist fehlgeschlagen: Es gab keinen Schritt mehr, der geöffnet werden konnte."),
            ("reached", "Er kam bis „{step}“."),
            ("reachedGone", "Er kam bis zu einem Schritt, den es nicht mehr gibt."),
            ("reachedNothing", "Er hielt an, bevor ein Schritt geöffnet wurde."),
        ],
        statuses: &[
            ("blocked", "Blockiert"),
            ("done", "Erledigt"),
            ("in_progress", "In Arbeit"),
            ("rejected", "Verworfen"),
            ("todo", "Offen"),
        ],
    },
    Wording {
        language: "en",
        says: &[
            ("commentAdded", "{who} added a comment on {what}"),
            ("commentAddedBare", "{who} added {what}"),
            ("commentRemoved", "{who} took back a comment on {what}"),
            ("commentRemovedBare", "{who} took back {what}"),
            ("decisionAccepted", "{who} finished writing {what}"),
            ("decisionRejected", "{who} rejected {what}"),
            ("statusChanged", "{who} moved {what} to {state}"),
            ("statusChangedBare", "{who} moved {what}"),
            ("subject.commentAdded", "Comment added"),
            ("subject.commentRemoved", "Comment removed"),
            ("subject.count", "{n} updates"),
            ("subject.countOne", "{n} update"),
            ("subject.decisionAccepted", "Decision written"),
            ("subject.decisionRejected", "Decision rejected"),
            ("subject.statusChanged", "Task moved to {state}"),
            ("subject.statusChangedBare", "Task status changed"),
            ("subject.taskAssigned", "Task reassigned"),
            ("subject.taskCreated", "Task created"),
            ("subject.taskDeleted", "Task deleted"),
            ("subject.taskDone", "Task finished"),
            ("subject.taskDue", "Task due"),
            ("subject.taskDueTomorrow", "Task due tomorrow"),
            ("subject.taskMoved", "Task moved"),
            ("subject.taskRejected", "Task decided against"),
            ("taskAssigned", "{who} assigned {what} to {state}"),
            ("taskAssignedBare", "{who} assigned {what}"),
            ("taskCreated", "{who} created {what}"),
            ("taskDeleted", "{who} deleted {what}"),
            ("taskDone", "{who} finished {what}"),
            ("taskDue", "{what} is due"),
            ("taskDueTomorrow", "{what} is due tomorrow"),
            ("taskMoved", "{who} moved {what} into {state}"),
            ("taskMovedBare", "{who} moved {what} to another project"),
            ("taskRejected", "{who} decided against {what}"),
            ("test", "Test message from Amenbo — this project reports here."),
            ("unknown", "{who} acted on {what} ({event})"),
        ],
        runs: &[
            ("canceled", "An automation run was canceled."),
            ("completed", "An automation run completed."),
            ("crashed", "An automation run failed: a step ended without reporting — its program exited, or Amenbo was restarted while it was under way."),
            ("halted", "An automation run stopped to call a person: a step left through a way out that asks for one."),
            ("leftTaskOpen", "An automation run failed: it went on without closing the task it had taken."),
            ("line", "{why} {reached} (run {run})"),
            ("maxTimes", "An automation run failed: a way back was taken as often as it is allowed to be."),
            ("noAgent", "An automation run failed: the agent a step asked for could not be started."),
            ("noInput", "An automation run failed: a step's required input had nothing to fill it."),
            ("noWayOn", "An automation run failed: nothing was left for it to open."),
            ("reached", "It got as far as \"{step}\"."),
            ("reachedGone", "It got as far as a step that is no longer there."),
            ("reachedNothing", "It stopped before opening a step."),
        ],
        statuses: &[
            ("blocked", "Blocked"),
            ("done", "Done"),
            ("in_progress", "In progress"),
            ("rejected", "Rejected"),
            ("todo", "To do"),
        ],
    },
    Wording {
        language: "es",
        says: &[
            ("commentAdded", "{who} comentó en {what}"),
            ("commentAddedBare", "{who} añadió {what}"),
            ("commentRemoved", "{who} retiró un comentario de {what}"),
            ("commentRemovedBare", "{who} retiró {what}"),
            ("decisionAccepted", "{who} terminó de escribir {what}"),
            ("decisionRejected", "{who} rechazó {what}"),
            ("statusChanged", "{who} cambió {what} a {state}"),
            ("statusChangedBare", "{who} cambió el estado de {what}"),
            ("subject.commentAdded", "Comentario añadido"),
            ("subject.commentRemoved", "Comentario retirado"),
            ("subject.count", "{n} novedades"),
            ("subject.countOne", "{n} novedad"),
            ("subject.decisionAccepted", "Decisión terminada"),
            ("subject.decisionRejected", "Decisión rechazada"),
            ("subject.statusChanged", "Tarea a {state}"),
            ("subject.statusChangedBare", "Estado de la tarea cambiado"),
            ("subject.taskAssigned", "Tarea reasignada"),
            ("subject.taskCreated", "Tarea creada"),
            ("subject.taskDeleted", "Tarea eliminada"),
            ("subject.taskDone", "Tarea terminada"),
            ("subject.taskDue", "Tarea vencida"),
            ("subject.taskDueTomorrow", "Tarea vence mañana"),
            ("subject.taskMoved", "Tarea movida"),
            ("subject.taskRejected", "Tarea descartada"),
            ("taskAssigned", "{who} asignó {what} a {state}"),
            ("taskAssignedBare", "{who} asignó {what}"),
            ("taskCreated", "{who} creó {what}"),
            ("taskDeleted", "{who} eliminó {what}"),
            ("taskDone", "{who} terminó {what}"),
            ("taskDue", "El plazo de {what} ha llegado"),
            ("taskDueTomorrow", "El plazo de {what} es mañana"),
            ("taskMoved", "{who} movió {what} a {state}"),
            ("taskMovedBare", "{who} movió {what} a otro proyecto"),
            ("taskRejected", "{who} decidió no hacer {what}"),
            ("test", "Mensaje de prueba de Amenbo: este proyecto informa aquí."),
            ("unknown", "{who} hizo algo en {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Una ejecución de automatización se canceló."),
            ("completed", "Una ejecución de automatización se completó."),
            ("crashed", "Una ejecución de automatización falló: un paso terminó sin informar; su programa salió o Amenbo se reinició mientras estaba en marcha."),
            ("halted", "Una ejecución de automatización se detuvo para llamar a una persona: un paso salió por una salida que pide a una persona."),
            ("leftTaskOpen", "Una ejecución de automatización falló: siguió adelante sin cerrar la tarea que había tomado."),
            ("line", "{why} {reached} (ejecución {run})"),
            ("maxTimes", "Una ejecución de automatización falló: se tomó un camino de vuelta tantas veces como está permitido."),
            ("noAgent", "Una ejecución de automatización falló: no se pudo iniciar el agente que pedía un paso."),
            ("noInput", "Una ejecución de automatización falló: una entrada obligatoria de un paso estaba vacía."),
            ("noWayOn", "Una ejecución de automatización falló: no quedaba ningún paso que abrir."),
            ("reached", "Llegó hasta «{step}»."),
            ("reachedGone", "Llegó hasta un paso que ya no existe."),
            ("reachedNothing", "Se detuvo antes de abrir un paso."),
        ],
        statuses: &[
            ("blocked", "Bloqueado"),
            ("done", "Hecho"),
            ("in_progress", "En curso"),
            ("rejected", "Descartado"),
            ("todo", "Pendiente"),
        ],
    },
    Wording {
        language: "fr",
        says: &[
            ("commentAdded", "{who} a commenté {what}"),
            ("commentAddedBare", "{who} a ajouté {what}"),
            ("commentRemoved", "{who} a retiré un commentaire sur {what}"),
            ("commentRemovedBare", "{who} a retiré {what}"),
            ("decisionAccepted", "{who} a fini d'écrire {what}"),
            ("decisionRejected", "{who} a rejeté {what}"),
            ("statusChanged", "{who} a fait passer {what} à {state}"),
            ("statusChangedBare", "{who} a changé l'état de {what}"),
            ("subject.commentAdded", "Commentaire ajouté"),
            ("subject.commentRemoved", "Commentaire retiré"),
            ("subject.count", "{n} mises à jour"),
            ("subject.countOne", "{n} mise à jour"),
            ("subject.decisionAccepted", "Décision écrite"),
            ("subject.decisionRejected", "Décision rejetée"),
            ("subject.statusChanged", "Tâche à {state}"),
            ("subject.statusChangedBare", "Statut de tâche modifié"),
            ("subject.taskAssigned", "Tâche réattribuée"),
            ("subject.taskCreated", "Tâche créée"),
            ("subject.taskDeleted", "Tâche supprimée"),
            ("subject.taskDone", "Tâche terminée"),
            ("subject.taskDue", "Tâche à échéance"),
            ("subject.taskDueTomorrow", "Tâche à échéance demain"),
            ("subject.taskMoved", "Tâche déplacée"),
            ("subject.taskRejected", "Tâche écartée"),
            ("taskAssigned", "{who} a affecté {what} à {state}"),
            ("taskAssignedBare", "{who} a affecté {what}"),
            ("taskCreated", "{who} a créé {what}"),
            ("taskDeleted", "{who} a supprimé {what}"),
            ("taskDone", "{who} a terminé {what}"),
            ("taskDue", "L'échéance de {what} est arrivée"),
            ("taskDueTomorrow", "L'échéance de {what} est demain"),
            ("taskMoved", "{who} a déplacé {what} vers {state}"),
            ("taskMovedBare", "{who} a déplacé {what} vers un autre projet"),
            ("taskRejected", "{who} a décidé de ne pas faire {what}"),
            ("test", "Message de test d'Amenbo — ce projet rend compte ici."),
            ("unknown", "{who} est intervenu sur {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Une exécution d'automatisation a été annulée."),
            ("completed", "Une exécution d'automatisation s'est terminée."),
            ("crashed", "Une exécution d'automatisation a échoué : une étape s'est terminée sans rendre compte ; son programme s'est arrêté, ou Amenbo a redémarré pendant qu'elle était en cours."),
            ("halted", "Une exécution d'automatisation s'est arrêtée pour appeler une personne : une étape est sortie par une sortie qui en demande une."),
            ("leftTaskOpen", "Une exécution d'automatisation a échoué : elle a continué sans fermer la tâche qu'elle avait prise."),
            ("line", "{why} {reached} (exécution {run})"),
            ("maxTimes", "Une exécution d'automatisation a échoué : un chemin de retour a été pris aussi souvent qu'il est permis."),
            ("noAgent", "Une exécution d'automatisation a échoué : l'agent demandé par une étape n'a pas pu être lancé."),
            ("noInput", "Une exécution d'automatisation a échoué : une entrée obligatoire d'une étape était vide."),
            ("noWayOn", "Une exécution d'automatisation a échoué : il ne restait aucune étape à ouvrir."),
            ("reached", "Elle est allée jusqu'à « {step} »."),
            ("reachedGone", "Elle est allée jusqu'à une étape qui n'existe plus."),
            ("reachedNothing", "Elle s'est arrêtée avant d'ouvrir une étape."),
        ],
        statuses: &[
            ("blocked", "Bloquée"),
            ("done", "Terminée"),
            ("in_progress", "En cours"),
            ("rejected", "Écartée"),
            ("todo", "À faire"),
        ],
    },
    Wording {
        language: "hi",
        says: &[
            ("commentAdded", "{who} ने {what} पर टिप्पणी की"),
            ("commentAddedBare", "{who} ने {what} जोड़ा"),
            ("commentRemoved", "{who} ने {what} पर की टिप्पणी वापस ली"),
            ("commentRemovedBare", "{who} ने {what} वापस लिया"),
            ("decisionAccepted", "{who} ने {what} लिखना पूरा किया"),
            ("decisionRejected", "{who} ने {what} अस्वीकार किया"),
            ("statusChanged", "{who} ने {what} को {state} किया"),
            ("statusChangedBare", "{who} ने {what} की स्थिति बदली"),
            ("subject.commentAdded", "टिप्पणी जोड़ी"),
            ("subject.commentRemoved", "टिप्पणी हटाई"),
            ("subject.count", "{n} अपडेट"),
            ("subject.countOne", "{n} अपडेट"),
            ("subject.decisionAccepted", "निर्णय लिखा गया"),
            ("subject.decisionRejected", "निर्णय अस्वीकृत"),
            ("subject.statusChanged", "कार्य {state}"),
            ("subject.statusChangedBare", "कार्य की स्थिति बदली"),
            ("subject.taskAssigned", "कार्य सौंपा"),
            ("subject.taskCreated", "कार्य बनाया"),
            ("subject.taskDeleted", "कार्य मिटाया"),
            ("subject.taskDone", "कार्य पूरा"),
            ("subject.taskDue", "कार्य की समय-सीमा"),
            ("subject.taskDueTomorrow", "कार्य की समय-सीमा कल"),
            ("subject.taskMoved", "कार्य स्थानांतरित"),
            ("subject.taskRejected", "कार्य छोड़ा"),
            ("taskAssigned", "{who} ने {what} {state} को सौंपा"),
            ("taskAssignedBare", "{who} ने {what} सौंपा"),
            ("taskCreated", "{who} ने {what} बनाया"),
            ("taskDeleted", "{who} ने {what} मिटाया"),
            ("taskDone", "{who} ने {what} पूरा किया"),
            ("taskDue", "{what} की समय-सीमा आ गई है"),
            ("taskDueTomorrow", "{what} की समय-सीमा कल है"),
            ("taskMoved", "{who} ने {what} को {state} में डाला"),
            ("taskMovedBare", "{who} ने {what} को दूसरे प्रोजेक्ट में डाला"),
            ("taskRejected", "{who} ने {what} न करने का तय किया"),
            ("test", "Amenbo से परीक्षण संदेश — यह प्रोजेक्ट यहीं बताएगा।"),
            ("unknown", "{who} ने {what} पर कुछ किया ({event})"),
        ],
        runs: &[
            ("canceled", "एक ऑटोमेशन रन रद्द किया गया।"),
            ("completed", "एक ऑटोमेशन रन पूरा हुआ।"),
            ("crashed", "एक ऑटोमेशन रन विफल हुआ: एक चरण रिपोर्ट किए बिना समाप्त हो गया — उसका प्रोग्राम बंद हो गया, या चलते समय Amenbo फिर से शुरू हुआ।"),
            ("halted", "एक ऑटोमेशन रन किसी व्यक्ति को बुलाने के लिए रुका: एक चरण ऐसे निकास से निकला जो व्यक्ति को बुलाता है।"),
            ("leftTaskOpen", "एक ऑटोमेशन रन विफल हुआ: उसने ली हुई टास्क बंद किए बिना आगे बढ़ना चाहा।"),
            ("line", "{why} {reached} (रन {run})"),
            ("maxTimes", "एक ऑटोमेशन रन विफल हुआ: एक वापसी का रास्ता जितनी बार अनुमति है उतनी बार लिया गया।"),
            ("noAgent", "एक ऑटोमेशन रन विफल हुआ: किसी चरण द्वारा माँगा गया एजेंट शुरू नहीं हो सका।"),
            ("noInput", "एक ऑटोमेशन रन विफल हुआ: किसी चरण का आवश्यक इनपुट खाली था।"),
            ("noWayOn", "एक ऑटोमेशन रन विफल हुआ: खोलने के लिए कोई चरण नहीं बचा था।"),
            ("reached", "यह \"{step}\" तक पहुँचा।"),
            ("reachedGone", "यह एक ऐसे चरण तक पहुँचा जो अब मौजूद नहीं है।"),
            ("reachedNothing", "यह कोई चरण खोलने से पहले रुक गया।"),
        ],
        statuses: &[
            ("blocked", "रुका हुआ"),
            ("done", "पूरा"),
            ("in_progress", "चल रहा है"),
            ("rejected", "अस्वीकृत"),
            ("todo", "करना है"),
        ],
    },
    Wording {
        language: "id",
        says: &[
            ("commentAdded", "{who} mengomentari {what}"),
            ("commentAddedBare", "{who} menambahkan {what}"),
            ("commentRemoved", "{who} menarik komentar pada {what}"),
            ("commentRemovedBare", "{who} menarik {what}"),
            ("decisionAccepted", "{who} selesai menulis {what}"),
            ("decisionRejected", "{who} menolak {what}"),
            ("statusChanged", "{who} mengubah {what} menjadi {state}"),
            ("statusChangedBare", "{who} mengubah status {what}"),
            ("subject.commentAdded", "Komentar ditambahkan"),
            ("subject.commentRemoved", "Komentar ditarik"),
            ("subject.count", "{n} pembaruan"),
            ("subject.countOne", "{n} pembaruan"),
            ("subject.decisionAccepted", "Keputusan selesai ditulis"),
            ("subject.decisionRejected", "Keputusan ditolak"),
            ("subject.statusChanged", "Tugas jadi {state}"),
            ("subject.statusChangedBare", "Status tugas berubah"),
            ("subject.taskAssigned", "Tugas dialihkan"),
            ("subject.taskCreated", "Tugas dibuat"),
            ("subject.taskDeleted", "Tugas dihapus"),
            ("subject.taskDone", "Tugas selesai"),
            ("subject.taskDue", "Tugas jatuh tempo"),
            ("subject.taskDueTomorrow", "Tugas jatuh tempo besok"),
            ("subject.taskMoved", "Tugas dipindahkan"),
            ("subject.taskRejected", "Tugas dibatalkan"),
            ("taskAssigned", "{who} menugaskan {what} ke {state}"),
            ("taskAssignedBare", "{who} menugaskan {what}"),
            ("taskCreated", "{who} membuat {what}"),
            ("taskDeleted", "{who} menghapus {what}"),
            ("taskDone", "{who} menyelesaikan {what}"),
            ("taskDue", "{what} sudah jatuh tempo"),
            ("taskDueTomorrow", "{what} jatuh tempo besok"),
            ("taskMoved", "{who} memindahkan {what} ke {state}"),
            ("taskMovedBare", "{who} memindahkan {what} ke proyek lain"),
            ("taskRejected", "{who} memutuskan tidak mengerjakan {what}"),
            ("test", "Pesan uji dari Amenbo — proyek ini melapor ke sini."),
            ("unknown", "{who} melakukan sesuatu pada {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Sebuah eksekusi otomasi dibatalkan."),
            ("completed", "Sebuah eksekusi otomasi selesai."),
            ("crashed", "Sebuah eksekusi otomasi gagal: sebuah langkah berakhir tanpa melapor — programnya keluar, atau Amenbo dimulai ulang saat langkah itu berjalan."),
            ("halted", "Sebuah eksekusi otomasi berhenti untuk memanggil seseorang: sebuah langkah keluar lewat jalan keluar yang meminta seseorang."),
            ("leftTaskOpen", "Sebuah eksekusi otomasi gagal: eksekusi itu lanjut tanpa menutup tugas yang diambilnya."),
            ("line", "{why} {reached} (eksekusi {run})"),
            ("maxTimes", "Sebuah eksekusi otomasi gagal: sebuah jalan kembali diambil sebanyak yang diizinkan."),
            ("noAgent", "Sebuah eksekusi otomasi gagal: agen yang diminta sebuah langkah tidak bisa dijalankan."),
            ("noInput", "Sebuah eksekusi otomasi gagal: input wajib sebuah langkah kosong."),
            ("noWayOn", "Sebuah eksekusi otomasi gagal: tidak ada langkah lagi yang bisa dibuka."),
            ("reached", "Eksekusi itu sampai di \"{step}\"."),
            ("reachedGone", "Eksekusi itu sampai di langkah yang sudah tidak ada."),
            ("reachedNothing", "Eksekusi itu berhenti sebelum membuka satu langkah pun."),
        ],
        statuses: &[
            ("blocked", "Terhambat"),
            ("done", "Selesai"),
            ("in_progress", "Sedang dikerjakan"),
            ("rejected", "Ditolak"),
            ("todo", "Akan dikerjakan"),
        ],
    },
    Wording {
        language: "it",
        says: &[
            ("commentAdded", "{who} ha commentato {what}"),
            ("commentAddedBare", "{who} ha aggiunto {what}"),
            ("commentRemoved", "{who} ha ritirato un commento su {what}"),
            ("commentRemovedBare", "{who} ha ritirato {what}"),
            ("decisionAccepted", "{who} ha finito di scrivere {what}"),
            ("decisionRejected", "{who} ha respinto {what}"),
            ("statusChanged", "{who} ha portato {what} a {state}"),
            ("statusChangedBare", "{who} ha cambiato lo stato di {what}"),
            ("subject.commentAdded", "Commento aggiunto"),
            ("subject.commentRemoved", "Commento ritirato"),
            ("subject.count", "{n} aggiornamenti"),
            ("subject.countOne", "{n} aggiornamento"),
            ("subject.decisionAccepted", "Decisione scritta"),
            ("subject.decisionRejected", "Decisione respinta"),
            ("subject.statusChanged", "Attività a {state}"),
            ("subject.statusChangedBare", "Stato attività cambiato"),
            ("subject.taskAssigned", "Attività riassegnata"),
            ("subject.taskCreated", "Attività creata"),
            ("subject.taskDeleted", "Attività eliminata"),
            ("subject.taskDone", "Attività completata"),
            ("subject.taskDue", "Attività in scadenza"),
            ("subject.taskDueTomorrow", "Attività scade domani"),
            ("subject.taskMoved", "Attività spostata"),
            ("subject.taskRejected", "Attività scartata"),
            ("taskAssigned", "{who} ha assegnato {what} a {state}"),
            ("taskAssignedBare", "{who} ha assegnato {what}"),
            ("taskCreated", "{who} ha creato {what}"),
            ("taskDeleted", "{who} ha eliminato {what}"),
            ("taskDone", "{who} ha completato {what}"),
            ("taskDue", "{what} è in scadenza"),
            ("taskDueTomorrow", "{what} scade domani"),
            ("taskMoved", "{who} ha spostato {what} in {state}"),
            ("taskMovedBare", "{who} ha spostato {what} in un altro progetto"),
            ("taskRejected", "{who} ha deciso di non fare {what}"),
            ("test", "Messaggio di prova da Amenbo — questo progetto riferisce qui."),
            ("unknown", "{who} è intervenuto su {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Un'esecuzione di automazione è stata annullata."),
            ("completed", "Un'esecuzione di automazione è stata completata."),
            ("crashed", "Un'esecuzione di automazione non è riuscita: un passo è finito senza riferire; il suo programma è uscito, oppure Amenbo è stato riavviato mentre era in corso."),
            ("halted", "Un'esecuzione di automazione si è fermata per chiamare una persona: un passo è uscito da un'uscita che ne chiede una."),
            ("leftTaskOpen", "Un'esecuzione di automazione non è riuscita: è andata avanti senza chiudere l'attività che aveva preso."),
            ("line", "{why} {reached} (esecuzione {run})"),
            ("maxTimes", "Un'esecuzione di automazione non è riuscita: una via di ritorno è stata presa tante volte quante è permesso."),
            ("noAgent", "Un'esecuzione di automazione non è riuscita: non è stato possibile avviare l'agente richiesto da un passo."),
            ("noInput", "Un'esecuzione di automazione non è riuscita: un input obbligatorio di un passo era vuoto."),
            ("noWayOn", "Un'esecuzione di automazione non è riuscita: non restava nessun passo da aprire."),
            ("reached", "È arrivata fino a «{step}»."),
            ("reachedGone", "È arrivata fino a un passo che non esiste più."),
            ("reachedNothing", "Si è fermata prima di aprire un passo."),
        ],
        statuses: &[
            ("blocked", "Bloccata"),
            ("done", "Fatta"),
            ("in_progress", "In corso"),
            ("rejected", "Scartata"),
            ("todo", "Da fare"),
        ],
    },
    Wording {
        language: "ja",
        says: &[
            ("commentAdded", "{who} が {what} にコメントしました"),
            ("commentAddedBare", "{who} が {what} を追加しました"),
            ("commentRemoved", "{who} が {what} のコメントを取り消しました"),
            ("commentRemovedBare", "{who} が {what} を取り消しました"),
            ("decisionAccepted", "{who} が {what} を書き終えました"),
            ("decisionRejected", "{who} が {what} を却下しました"),
            ("statusChanged", "{who} が {what} を{state}にしました"),
            ("statusChangedBare", "{who} が {what} のステータスを変更しました"),
            ("subject.commentAdded", "コメントを追加"),
            ("subject.commentRemoved", "コメントを削除"),
            ("subject.count", "更新 {n}件"),
            ("subject.countOne", "更新 {n}件"),
            ("subject.decisionAccepted", "決定を書き上げ"),
            ("subject.decisionRejected", "決定を却下"),
            ("subject.statusChanged", "タスクのステータスを{state}に変更"),
            ("subject.statusChangedBare", "タスクのステータスを変更"),
            ("subject.taskAssigned", "タスクの担当を変更"),
            ("subject.taskCreated", "タスクを作成"),
            ("subject.taskDeleted", "タスクを削除"),
            ("subject.taskDone", "タスクを完了"),
            ("subject.taskDue", "タスクの期日が到来"),
            ("subject.taskDueTomorrow", "タスクの期日は明日"),
            ("subject.taskMoved", "タスクを移動"),
            ("subject.taskRejected", "タスクを却下"),
            ("taskAssigned", "{who} が {what} を {state} に割り当てました"),
            ("taskAssignedBare", "{who} が {what} を割り当てました"),
            ("taskCreated", "{who} が {what} を作成しました"),
            ("taskDeleted", "{who} が {what} を削除しました"),
            ("taskDone", "{who} が {what} を完了しました"),
            ("taskDue", "{what} は期日が来ています"),
            ("taskDueTomorrow", "{what} は明日が期日です"),
            ("taskMoved", "{who} が {what} を {state} へ移動しました"),
            ("taskMovedBare", "{who} が {what} を別のプロジェクトへ移動しました"),
            ("taskRejected", "{who} が {what} を見送りました"),
            ("test", "Amenbo からのテスト送信です。このプロジェクトの通知はここに届きます。"),
            ("unknown", "{who} が {what} を操作しました（{event}）"),
        ],
        runs: &[
            ("canceled", "オートメーションの実行が中止されました。"),
            ("completed", "オートメーションの実行が完了しました。"),
            ("crashed", "オートメーションの実行が失敗しました。ステップが報告せずに終わりました。プログラムが終了したか、実行中に Amenbo が再起動しました。"),
            ("halted", "オートメーションの実行が止まり、人を呼んでいます。ステップが、人を呼ぶ出口から出ました。"),
            ("leftTaskOpen", "オートメーションの実行が失敗しました。取ったタスクを閉じずに次へ進もうとしました。"),
            ("line", "{why}{reached}（実行 {run}）"),
            ("maxTimes", "オートメーションの実行が失敗しました。戻る道を、許された回数まで通りました。"),
            ("noAgent", "オートメーションの実行が失敗しました。ステップが求めたエージェントを起動できませんでした。"),
            ("noInput", "オートメーションの実行が失敗しました。ステップの必須の入力が空でした。"),
            ("noWayOn", "オートメーションの実行が失敗しました。次に開くステップがありませんでした。"),
            ("reached", "「{step}」まで進みました。"),
            ("reachedGone", "今はもう無いステップまで進みました。"),
            ("reachedNothing", "ステップを1つも開かずに止まりました。"),
        ],
        statuses: &[
            ("blocked", "ブロック"),
            ("done", "完了"),
            ("in_progress", "進行中"),
            ("rejected", "却下"),
            ("todo", "未着手"),
        ],
    },
    Wording {
        language: "ko",
        says: &[
            ("commentAdded", "{who}이(가) {what}에 댓글을 남겼습니다"),
            ("commentAddedBare", "{who}이(가) {what}을(를) 남겼습니다"),
            ("commentRemoved", "{who}이(가) {what}의 댓글을 거뒀습니다"),
            ("commentRemovedBare", "{who}이(가) {what}을(를) 거뒀습니다"),
            ("decisionAccepted", "{who}이(가) {what}을(를) 다 썼습니다"),
            ("decisionRejected", "{who}이(가) {what}을(를) 기각했습니다"),
            ("statusChanged", "{who}이(가) {what}을(를) {state}(으)로 바꿨습니다"),
            ("statusChangedBare", "{who}이(가) {what}의 상태를 바꿨습니다"),
            ("subject.commentAdded", "댓글 추가"),
            ("subject.commentRemoved", "댓글 철회"),
            ("subject.count", "업데이트 {n}건"),
            ("subject.countOne", "업데이트 {n}건"),
            ("subject.decisionAccepted", "결정 작성 완료"),
            ("subject.decisionRejected", "결정 기각"),
            ("subject.statusChanged", "작업 {state}"),
            ("subject.statusChangedBare", "작업 상태 변경"),
            ("subject.taskAssigned", "작업 담당 변경"),
            ("subject.taskCreated", "작업 생성"),
            ("subject.taskDeleted", "작업 삭제"),
            ("subject.taskDone", "작업 완료"),
            ("subject.taskDue", "작업 기한"),
            ("subject.taskDueTomorrow", "작업 기한 내일"),
            ("subject.taskMoved", "작업 이동"),
            ("subject.taskRejected", "작업 기각"),
            ("taskAssigned", "{who}이(가) {what}을(를) {state}에게 맡겼습니다"),
            ("taskAssignedBare", "{who}이(가) {what}의 담당을 정했습니다"),
            ("taskCreated", "{who}이(가) {what}을(를) 만들었습니다"),
            ("taskDeleted", "{who}이(가) {what}을(를) 삭제했습니다"),
            ("taskDone", "{who}이(가) {what}을(를) 완료했습니다"),
            ("taskDue", "{what}의 기한이 되었습니다"),
            ("taskDueTomorrow", "{what}의 기한이 내일입니다"),
            ("taskMoved", "{who}이(가) {what}을(를) {state}(으)로 옮겼습니다"),
            ("taskMovedBare", "{who}이(가) {what}을(를) 다른 프로젝트로 옮겼습니다"),
            ("taskRejected", "{who}이(가) {what}을(를) 하지 않기로 했습니다"),
            ("test", "Amenbo에서 보낸 테스트 메시지입니다. 이 프로젝트는 여기로 보고합니다."),
            ("unknown", "{who}이(가) {what}에 무언가 했습니다 ({event})"),
        ],
        runs: &[
            ("canceled", "오토메이션 실행이 중지되었습니다."),
            ("completed", "오토메이션 실행이 완료되었습니다."),
            ("crashed", "오토메이션 실행이 실패했습니다. 단계가 보고하지 않고 끝났습니다. 프로그램이 종료되었거나, 실행 중에 Amenbo가 다시 시작되었습니다."),
            ("halted", "오토메이션 실행이 멈추고 사람을 부르고 있습니다. 단계가 사람을 부르는 출구로 나갔습니다."),
            ("leftTaskOpen", "오토메이션 실행이 실패했습니다. 맡은 태스크를 닫지 않고 다음으로 가려고 했습니다."),
            ("line", "{why} {reached} (실행 {run})"),
            ("maxTimes", "오토메이션 실행이 실패했습니다. 되돌아가는 길을 허용된 횟수만큼 지났습니다."),
            ("noAgent", "오토메이션 실행이 실패했습니다. 단계가 요청한 에이전트를 시작할 수 없었습니다."),
            ("noInput", "오토메이션 실행이 실패했습니다. 단계의 필수 입력이 비어 있었습니다."),
            ("noWayOn", "오토메이션 실행이 실패했습니다. 다음에 열 단계가 없었습니다."),
            ("reached", "\"{step}\"까지 진행했습니다."),
            ("reachedGone", "지금은 없는 단계까지 진행했습니다."),
            ("reachedNothing", "단계를 하나도 열지 않고 멈췄습니다."),
        ],
        statuses: &[
            ("blocked", "막힘"),
            ("done", "완료"),
            ("in_progress", "진행 중"),
            ("rejected", "기각"),
            ("todo", "할 일"),
        ],
    },
    Wording {
        language: "nl",
        says: &[
            ("commentAdded", "{who} heeft op {what} gereageerd"),
            ("commentAddedBare", "{who} heeft {what} toegevoegd"),
            ("commentRemoved", "{who} heeft een reactie op {what} ingetrokken"),
            ("commentRemovedBare", "{who} heeft {what} ingetrokken"),
            ("decisionAccepted", "{who} heeft {what} afgeschreven"),
            ("decisionRejected", "{who} heeft {what} afgewezen"),
            ("statusChanged", "{who} heeft {what} op {state} gezet"),
            ("statusChangedBare", "{who} heeft de status van {what} gewijzigd"),
            ("subject.commentAdded", "Reactie geplaatst"),
            ("subject.commentRemoved", "Reactie ingetrokken"),
            ("subject.count", "{n} updates"),
            ("subject.countOne", "{n} update"),
            ("subject.decisionAccepted", "Besluit afgeschreven"),
            ("subject.decisionRejected", "Besluit afgewezen"),
            ("subject.statusChanged", "Taak op {state}"),
            ("subject.statusChangedBare", "Taakstatus gewijzigd"),
            ("subject.taskAssigned", "Taak opnieuw toegewezen"),
            ("subject.taskCreated", "Taak aangemaakt"),
            ("subject.taskDeleted", "Taak verwijderd"),
            ("subject.taskDone", "Taak afgerond"),
            ("subject.taskDue", "Taak op einddatum"),
            ("subject.taskDueTomorrow", "Taak morgen op einddatum"),
            ("subject.taskMoved", "Taak verplaatst"),
            ("subject.taskRejected", "Taak vervallen"),
            ("taskAssigned", "{who} heeft {what} aan {state} toegewezen"),
            ("taskAssignedBare", "{who} heeft {what} toegewezen"),
            ("taskCreated", "{who} heeft {what} aangemaakt"),
            ("taskDeleted", "{who} heeft {what} verwijderd"),
            ("taskDone", "{who} heeft {what} afgerond"),
            ("taskDue", "De deadline van {what} is bereikt"),
            ("taskDueTomorrow", "De deadline van {what} is morgen"),
            ("taskMoved", "{who} heeft {what} naar {state} verplaatst"),
            ("taskMovedBare", "{who} heeft {what} naar een ander project verplaatst"),
            ("taskRejected", "{who} heeft besloten {what} niet te doen"),
            ("test", "Testbericht van Amenbo — dit project meldt hier."),
            ("unknown", "{who} heeft iets met {what} gedaan ({event})"),
        ],
        runs: &[
            ("canceled", "Een automatiseringsrun is geannuleerd."),
            ("completed", "Een automatiseringsrun is voltooid."),
            ("crashed", "Een automatiseringsrun is mislukt: een stap eindigde zonder te rapporteren — het programma stopte, of Amenbo werd herstart terwijl de stap liep."),
            ("halted", "Een automatiseringsrun is gestopt om een mens te roepen: een stap ging door een uitgang die om een mens vraagt."),
            ("leftTaskOpen", "Een automatiseringsrun is mislukt: de run ging verder zonder de taak te sluiten die hij had genomen."),
            ("line", "{why} {reached} (run {run})"),
            ("maxTimes", "Een automatiseringsrun is mislukt: een weg terug is zo vaak genomen als is toegestaan."),
            ("noAgent", "Een automatiseringsrun is mislukt: de agent die een stap vroeg, kon niet worden gestart."),
            ("noInput", "Een automatiseringsrun is mislukt: een verplichte invoer van een stap was leeg."),
            ("noWayOn", "Een automatiseringsrun is mislukt: er was geen stap meer om te openen."),
            ("reached", "De run kwam tot „{step}”."),
            ("reachedGone", "De run kwam tot een stap die niet meer bestaat."),
            ("reachedNothing", "De run stopte voordat er een stap werd geopend."),
        ],
        statuses: &[
            ("blocked", "Geblokkeerd"),
            ("done", "Klaar"),
            ("in_progress", "Bezig"),
            ("rejected", "Afgewezen"),
            ("todo", "Te doen"),
        ],
    },
    Wording {
        language: "pl",
        says: &[
            ("commentAdded", "{who} skomentował(a) {what}"),
            ("commentAddedBare", "{who} dodał(a) {what}"),
            ("commentRemoved", "{who} wycofał(a) komentarz do {what}"),
            ("commentRemovedBare", "{who} wycofał(a) {what}"),
            ("decisionAccepted", "{who} dopisał(a) {what} do końca"),
            ("decisionRejected", "{who} odrzucił(a) {what}"),
            ("statusChanged", "{who} zmienił(a) {what} na {state}"),
            ("statusChangedBare", "{who} zmienił(a) status {what}"),
            ("subject.commentAdded", "Dodano komentarz"),
            ("subject.commentRemoved", "Wycofano komentarz"),
            ("subject.count", "Aktualizacje: {n}"),
            ("subject.countOne", "Aktualizacja: {n}"),
            ("subject.decisionAccepted", "Decyzja dopisana"),
            ("subject.decisionRejected", "Odrzucono decyzję"),
            ("subject.statusChanged", "Zadanie: {state}"),
            ("subject.statusChangedBare", "Zmieniono status zadania"),
            ("subject.taskAssigned", "Zmieniono przypisanie"),
            ("subject.taskCreated", "Utworzono zadanie"),
            ("subject.taskDeleted", "Usunięto zadanie"),
            ("subject.taskDone", "Ukończono zadanie"),
            ("subject.taskDue", "Termin zadania"),
            ("subject.taskDueTomorrow", "Termin zadania jutro"),
            ("subject.taskMoved", "Przeniesiono zadanie"),
            ("subject.taskRejected", "Odrzucono zadanie"),
            ("taskAssigned", "{who} przypisał(a) {what} do {state}"),
            ("taskAssignedBare", "{who} przypisał(a) {what}"),
            ("taskCreated", "{who} utworzył(a) {what}"),
            ("taskDeleted", "{who} usunął(-ęła) {what}"),
            ("taskDone", "{who} ukończył(a) {what}"),
            ("taskDue", "Termin {what} nadszedł"),
            ("taskDueTomorrow", "Termin {what} przypada jutro"),
            ("taskMoved", "{who} umieścił(a) {what} w {state}"),
            ("taskMovedBare", "{who} umieścił(a) {what} w innym projekcie"),
            ("taskRejected", "{who} postanowił(a) nie robić {what}"),
            ("test", "Wiadomość testowa z Amenbo — ten projekt raportuje tutaj."),
            ("unknown", "{who} zrobił(a) coś z {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Uruchomienie automatyzacji zostało anulowane."),
            ("completed", "Uruchomienie automatyzacji zostało zakończone."),
            ("crashed", "Uruchomienie automatyzacji nie powiodło się: krok zakończył się bez raportu — jego program się zakończył albo Amenbo zostało ponownie uruchomione w trakcie."),
            ("halted", "Uruchomienie automatyzacji zatrzymało się, aby wezwać człowieka: krok wyszedł wyjściem, które wzywa człowieka."),
            ("leftTaskOpen", "Uruchomienie automatyzacji nie powiodło się: poszło dalej, nie zamykając zadania, które wzięło."),
            ("line", "{why} {reached} (uruchomienie {run})"),
            ("maxTimes", "Uruchomienie automatyzacji nie powiodło się: drogę powrotną wybrano tyle razy, ile jest dozwolone."),
            ("noAgent", "Uruchomienie automatyzacji nie powiodło się: nie udało się uruchomić agenta, o którego prosił krok."),
            ("noInput", "Uruchomienie automatyzacji nie powiodło się: wymagane wejście kroku było puste."),
            ("noWayOn", "Uruchomienie automatyzacji nie powiodło się: nie został żaden krok do otwarcia."),
            ("reached", "Doszło do „{step}”."),
            ("reachedGone", "Doszło do kroku, którego już nie ma."),
            ("reachedNothing", "Zatrzymało się przed otwarciem jakiegokolwiek kroku."),
        ],
        statuses: &[
            ("blocked", "Zablokowane"),
            ("done", "Gotowe"),
            ("in_progress", "W toku"),
            ("rejected", "Odrzucone"),
            ("todo", "Do zrobienia"),
        ],
    },
    Wording {
        language: "pt-BR",
        says: &[
            ("commentAdded", "{who} comentou em {what}"),
            ("commentAddedBare", "{who} adicionou {what}"),
            ("commentRemoved", "{who} retirou um comentário de {what}"),
            ("commentRemovedBare", "{who} retirou {what}"),
            ("decisionAccepted", "{who} terminou de escrever {what}"),
            ("decisionRejected", "{who} recusou {what}"),
            ("statusChanged", "{who} mudou {what} para {state}"),
            ("statusChangedBare", "{who} mudou o status de {what}"),
            ("subject.commentAdded", "Comentário adicionado"),
            ("subject.commentRemoved", "Comentário retirado"),
            ("subject.count", "{n} atualizações"),
            ("subject.countOne", "{n} atualização"),
            ("subject.decisionAccepted", "Decisão escrita"),
            ("subject.decisionRejected", "Decisão rejeitada"),
            ("subject.statusChanged", "Tarefa para {state}"),
            ("subject.statusChangedBare", "Status da tarefa alterado"),
            ("subject.taskAssigned", "Tarefa reatribuída"),
            ("subject.taskCreated", "Tarefa criada"),
            ("subject.taskDeleted", "Tarefa excluída"),
            ("subject.taskDone", "Tarefa concluída"),
            ("subject.taskDue", "Tarefa vencida"),
            ("subject.taskDueTomorrow", "Tarefa vence amanhã"),
            ("subject.taskMoved", "Tarefa movida"),
            ("subject.taskRejected", "Tarefa recusada"),
            ("taskAssigned", "{who} atribuiu {what} a {state}"),
            ("taskAssignedBare", "{who} definiu o responsável de {what}"),
            ("taskCreated", "{who} criou {what}"),
            ("taskDeleted", "{who} excluiu {what}"),
            ("taskDone", "{who} concluiu {what}"),
            ("taskDue", "O prazo de {what} chegou"),
            ("taskDueTomorrow", "O prazo de {what} é amanhã"),
            ("taskMoved", "{who} moveu {what} para {state}"),
            ("taskMovedBare", "{who} moveu {what} para outro projeto"),
            ("taskRejected", "{who} decidiu não fazer {what}"),
            ("test", "Mensagem de teste do Amenbo — este projeto reporta aqui."),
            ("unknown", "{who} fez algo em {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Uma execução de automação foi cancelada."),
            ("completed", "Uma execução de automação foi concluída."),
            ("crashed", "Uma execução de automação falhou: um passo terminou sem relatar — o programa saiu, ou o Amenbo foi reiniciado enquanto ele estava em andamento."),
            ("halted", "Uma execução de automação parou para chamar uma pessoa: um passo saiu por uma saída que pede uma pessoa."),
            ("leftTaskOpen", "Uma execução de automação falhou: ela seguiu sem fechar a tarefa que tinha pegado."),
            ("line", "{why} {reached} (execução {run})"),
            ("maxTimes", "Uma execução de automação falhou: um caminho de volta foi tomado tantas vezes quanto é permitido."),
            ("noAgent", "Uma execução de automação falhou: não foi possível iniciar o agente que um passo pediu."),
            ("noInput", "Uma execução de automação falhou: uma entrada obrigatória de um passo estava vazia."),
            ("noWayOn", "Uma execução de automação falhou: não restava nenhum passo para abrir."),
            ("reached", "Ela chegou até \"{step}\"."),
            ("reachedGone", "Ela chegou até um passo que não existe mais."),
            ("reachedNothing", "Ela parou antes de abrir um passo."),
        ],
        statuses: &[
            ("blocked", "Bloqueada"),
            ("done", "Concluída"),
            ("in_progress", "Em andamento"),
            ("rejected", "Recusada"),
            ("todo", "A fazer"),
        ],
    },
    Wording {
        language: "ru",
        says: &[
            ("commentAdded", "{who} прокомментировал {what}"),
            ("commentAddedBare", "{who} добавил {what}"),
            ("commentRemoved", "{who} отозвал комментарий к {what}"),
            ("commentRemovedBare", "{who} отозвал {what}"),
            ("decisionAccepted", "{who} дописал {what}"),
            ("decisionRejected", "{who} отклонил {what}"),
            ("statusChanged", "{who} перевёл {what} в статус {state}"),
            ("statusChangedBare", "{who} изменил статус {what}"),
            ("subject.commentAdded", "Добавлен комментарий"),
            ("subject.commentRemoved", "Отозван комментарий"),
            ("subject.count", "Обновления: {n}"),
            ("subject.countOne", "Обновление: {n}"),
            ("subject.decisionAccepted", "Решение дописано"),
            ("subject.decisionRejected", "Решение отклонено"),
            ("subject.statusChanged", "Задача: {state}"),
            ("subject.statusChangedBare", "Изменён статус задачи"),
            ("subject.taskAssigned", "Сменён исполнитель"),
            ("subject.taskCreated", "Создана задача"),
            ("subject.taskDeleted", "Задача удалена"),
            ("subject.taskDone", "Задача завершена"),
            ("subject.taskDue", "Срок задачи"),
            ("subject.taskDueTomorrow", "Срок задачи завтра"),
            ("subject.taskMoved", "Задача перенесена"),
            ("subject.taskRejected", "Задача отклонена"),
            ("taskAssigned", "{who} назначил {state} ответственным за {what}"),
            ("taskAssignedBare", "{who} назначил ответственного за {what}"),
            ("taskCreated", "{who} создал {what}"),
            ("taskDeleted", "{who} удалил {what}"),
            ("taskDone", "{who} завершил {what}"),
            ("taskDue", "Срок {what} наступил"),
            ("taskDueTomorrow", "Срок {what} — завтра"),
            ("taskMoved", "{who} переместил {what} в {state}"),
            ("taskMovedBare", "{who} переместил {what} в другой проект"),
            ("taskRejected", "{who} решил не делать {what}"),
            ("test", "Тестовое сообщение от Amenbo — этот проект отчитывается сюда."),
            ("unknown", "{who} что-то сделал с {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Запуск автоматизации отменён."),
            ("completed", "Запуск автоматизации завершён."),
            ("crashed", "Запуск автоматизации завершился неудачей: шаг закончился без отчёта — его программа завершилась, или Amenbo перезапустился во время работы."),
            ("halted", "Запуск автоматизации остановился, чтобы позвать человека: шаг вышел через выход, который зовёт человека."),
            ("leftTaskOpen", "Запуск автоматизации завершился неудачей: он пошёл дальше, не закрыв взятую задачу."),
            ("line", "{why} {reached} (запуск {run})"),
            ("maxTimes", "Запуск автоматизации завершился неудачей: путь назад пройден столько раз, сколько разрешено."),
            ("noAgent", "Запуск автоматизации завершился неудачей: не удалось запустить агента, которого просил шаг."),
            ("noInput", "Запуск автоматизации завершился неудачей: обязательный вход шага был пуст."),
            ("noWayOn", "Запуск автоматизации завершился неудачей: не осталось шага, который можно открыть."),
            ("reached", "Он дошёл до «{step}»."),
            ("reachedGone", "Он дошёл до шага, которого больше нет."),
            ("reachedNothing", "Он остановился, не открыв ни одного шага."),
        ],
        statuses: &[
            ("blocked", "Заблокировано"),
            ("done", "Готово"),
            ("in_progress", "В работе"),
            ("rejected", "Отклонено"),
            ("todo", "К выполнению"),
        ],
    },
    Wording {
        language: "th",
        says: &[
            ("commentAdded", "{who} แสดงความเห็นใน {what}"),
            ("commentAddedBare", "{who} เพิ่ม {what}"),
            ("commentRemoved", "{who} ถอนความเห็นใน {what}"),
            ("commentRemovedBare", "{who} ถอน {what}"),
            ("decisionAccepted", "{who} เขียน {what} จนจบแล้ว"),
            ("decisionRejected", "{who} ตีตก {what}"),
            ("statusChanged", "{who} เปลี่ยน {what} เป็น {state}"),
            ("statusChangedBare", "{who} เปลี่ยนสถานะของ {what}"),
            ("subject.commentAdded", "เพิ่มความเห็น"),
            ("subject.commentRemoved", "ถอนความเห็น"),
            ("subject.count", "อัปเดต {n} รายการ"),
            ("subject.countOne", "อัปเดต {n} รายการ"),
            ("subject.decisionAccepted", "เขียนข้อตัดสินจบ"),
            ("subject.decisionRejected", "ปฏิเสธข้อตัดสิน"),
            ("subject.statusChanged", "งานเป็น {state}"),
            ("subject.statusChangedBare", "เปลี่ยนสถานะงาน"),
            ("subject.taskAssigned", "เปลี่ยนผู้รับผิดชอบ"),
            ("subject.taskCreated", "สร้างงาน"),
            ("subject.taskDeleted", "ลบงาน"),
            ("subject.taskDone", "งานเสร็จแล้ว"),
            ("subject.taskDue", "งานถึงกำหนด"),
            ("subject.taskDueTomorrow", "งานถึงกำหนดพรุ่งนี้"),
            ("subject.taskMoved", "ย้ายงาน"),
            ("subject.taskRejected", "ตีตกงาน"),
            ("taskAssigned", "{who} มอบหมาย {what} ให้ {state}"),
            ("taskAssignedBare", "{who} มอบหมาย {what}"),
            ("taskCreated", "{who} สร้าง {what}"),
            ("taskDeleted", "{who} ลบ {what}"),
            ("taskDone", "{who} ทำ {what} เสร็จแล้ว"),
            ("taskDue", "{what} ถึงกำหนดแล้ว"),
            ("taskDueTomorrow", "{what} ถึงกำหนดพรุ่งนี้"),
            ("taskMoved", "{who} ย้าย {what} ไปที่ {state}"),
            ("taskMovedBare", "{who} ย้าย {what} ไปโปรเจกต์อื่น"),
            ("taskRejected", "{who} ตัดสินใจไม่ทำ {what}"),
            ("test", "ข้อความทดสอบจาก Amenbo — โปรเจกต์นี้จะรายงานมาที่นี่"),
            ("unknown", "{who} ทำบางอย่างกับ {what} ({event})"),
        ],
        runs: &[
            ("canceled", "การทำงานของออโตเมชันถูกยกเลิก"),
            ("completed", "การทำงานของออโตเมชันเสร็จสิ้น"),
            ("crashed", "การทำงานของออโตเมชันล้มเหลว: ขั้นตอนหนึ่งจบโดยไม่รายงาน — โปรแกรมของขั้นตอนนั้นปิดไป หรือ Amenbo ถูกเริ่มใหม่ระหว่างที่ทำงานอยู่"),
            ("halted", "การทำงานของออโตเมชันหยุดเพื่อเรียกคน: ขั้นตอนหนึ่งออกทางทางออกที่เรียกคน"),
            ("leftTaskOpen", "การทำงานของออโตเมชันล้มเหลว: ทำต่อไปโดยไม่ปิดงานที่รับไว้"),
            ("line", "{why} {reached} (การทำงาน {run})"),
            ("maxTimes", "การทำงานของออโตเมชันล้มเหลว: ทางย้อนกลับถูกใช้ครบจำนวนครั้งที่อนุญาตแล้ว"),
            ("noAgent", "การทำงานของออโตเมชันล้มเหลว: เริ่มเอเจนต์ที่ขั้นตอนหนึ่งขอไม่ได้"),
            ("noInput", "การทำงานของออโตเมชันล้มเหลว: อินพุตที่จำเป็นของขั้นตอนหนึ่งว่างอยู่"),
            ("noWayOn", "การทำงานของออโตเมชันล้มเหลว: ไม่มีขั้นตอนเหลือให้เปิด"),
            ("reached", "ทำไปถึง \"{step}\""),
            ("reachedGone", "ทำไปถึงขั้นตอนที่ไม่มีอยู่แล้ว"),
            ("reachedNothing", "หยุดก่อนเปิดขั้นตอนใด ๆ"),
        ],
        statuses: &[
            ("blocked", "ติดขัด"),
            ("done", "เสร็จแล้ว"),
            ("in_progress", "กำลังทำ"),
            ("rejected", "ตีตก"),
            ("todo", "รอทำ"),
        ],
    },
    Wording {
        language: "tr",
        says: &[
            ("commentAdded", "{who}, {what} kaydına yorum yaptı"),
            ("commentAddedBare", "{who}, {what} ekledi"),
            ("commentRemoved", "{who}, {what} kaydındaki yorumu geri aldı"),
            ("commentRemovedBare", "{who}, {what} geri aldı"),
            ("decisionAccepted", "{who}, {what} kararını yazıp bitirdi"),
            ("decisionRejected", "{who}, {what} kararını reddetti"),
            ("statusChanged", "{who}, {what} kaydını {state} durumuna geçirdi"),
            ("statusChangedBare", "{who}, {what} kaydının durumunu değiştirdi"),
            ("subject.commentAdded", "Yorum eklendi"),
            ("subject.commentRemoved", "Yorum geri alındı"),
            ("subject.count", "{n} güncelleme"),
            ("subject.countOne", "{n} güncelleme"),
            ("subject.decisionAccepted", "Karar yazıldı"),
            ("subject.decisionRejected", "Karar reddedildi"),
            ("subject.statusChanged", "Görev: {state}"),
            ("subject.statusChangedBare", "Görev durumu değişti"),
            ("subject.taskAssigned", "Görev ataması değişti"),
            ("subject.taskCreated", "Görev oluşturuldu"),
            ("subject.taskDeleted", "Görev silindi"),
            ("subject.taskDone", "Görev bitti"),
            ("subject.taskDue", "Görev süresi geldi"),
            ("subject.taskDueTomorrow", "Görev süresi yarın"),
            ("subject.taskMoved", "Görev taşındı"),
            ("subject.taskRejected", "Görevden vazgeçildi"),
            ("taskAssigned", "{who}, {what} kaydını {state} kullanıcısına verdi"),
            ("taskAssignedBare", "{who}, {what} kaydının sorumlusunu belirledi"),
            ("taskCreated", "{who}, {what} kaydını oluşturdu"),
            ("taskDeleted", "{who}, {what} kaydını sildi"),
            ("taskDone", "{who}, {what} kaydını bitirdi"),
            ("taskDue", "{what} kaydının teslim tarihi geldi"),
            ("taskDueTomorrow", "{what} kaydının teslim tarihi yarın"),
            ("taskMoved", "{who}, {what} kaydını {state} projesine taşıdı"),
            ("taskMovedBare", "{who}, {what} kaydını başka bir projeye taşıdı"),
            ("taskRejected", "{who}, {what} kaydını yapmamaya karar verdi"),
            ("test", "Amenbo'dan test mesajı — bu proje buraya bildiriyor."),
            ("unknown", "{who}, {what} üzerinde bir işlem yaptı ({event})"),
        ],
        runs: &[
            ("canceled", "Bir otomasyon çalıştırması iptal edildi."),
            ("completed", "Bir otomasyon çalıştırması tamamlandı."),
            ("crashed", "Bir otomasyon çalıştırması başarısız oldu: bir adım rapor vermeden bitti — programı kapandı ya da adım sürerken Amenbo yeniden başlatıldı."),
            ("halted", "Bir otomasyon çalıştırması bir insanı çağırmak için durdu: bir adım, insan isteyen bir çıkıştan çıktı."),
            ("leftTaskOpen", "Bir otomasyon çalıştırması başarısız oldu: aldığı görevi kapatmadan devam etti."),
            ("line", "{why} {reached} (çalıştırma {run})"),
            ("maxTimes", "Bir otomasyon çalıştırması başarısız oldu: bir geri dönüş yolu izin verilen sayıda kullanıldı."),
            ("noAgent", "Bir otomasyon çalıştırması başarısız oldu: bir adımın istediği ajan başlatılamadı."),
            ("noInput", "Bir otomasyon çalıştırması başarısız oldu: bir adımın zorunlu girdisi boştu."),
            ("noWayOn", "Bir otomasyon çalıştırması başarısız oldu: açılacak adım kalmadı."),
            ("reached", "\"{step}\" adımına kadar geldi."),
            ("reachedGone", "Artık var olmayan bir adıma kadar geldi."),
            ("reachedNothing", "Hiçbir adım açmadan durdu."),
        ],
        statuses: &[
            ("blocked", "Engelli"),
            ("done", "Bitti"),
            ("in_progress", "Sürüyor"),
            ("rejected", "Reddedildi"),
            ("todo", "Yapılacak"),
        ],
    },
    Wording {
        language: "uk",
        says: &[
            ("commentAdded", "{who} прокоментував {what}"),
            ("commentAddedBare", "{who} додав {what}"),
            ("commentRemoved", "{who} відкликав коментар до {what}"),
            ("commentRemovedBare", "{who} відкликав {what}"),
            ("decisionAccepted", "{who} дописав {what}"),
            ("decisionRejected", "{who} відхилив {what}"),
            ("statusChanged", "{who} перевів {what} у статус {state}"),
            ("statusChangedBare", "{who} змінив статус {what}"),
            ("subject.commentAdded", "Додано коментар"),
            ("subject.commentRemoved", "Відкликано коментар"),
            ("subject.count", "Оновлення: {n}"),
            ("subject.countOne", "Оновлення: {n}"),
            ("subject.decisionAccepted", "Рішення дописано"),
            ("subject.decisionRejected", "Рішення відхилено"),
            ("subject.statusChanged", "Завдання: {state}"),
            ("subject.statusChangedBare", "Змінено статус завдання"),
            ("subject.taskAssigned", "Змінено виконавця"),
            ("subject.taskCreated", "Створено завдання"),
            ("subject.taskDeleted", "Завдання видалено"),
            ("subject.taskDone", "Завдання завершено"),
            ("subject.taskDue", "Строк завдання"),
            ("subject.taskDueTomorrow", "Строк завдання завтра"),
            ("subject.taskMoved", "Завдання перенесено"),
            ("subject.taskRejected", "Завдання відхилено"),
            ("taskAssigned", "{who} призначив {state} відповідальним за {what}"),
            ("taskAssignedBare", "{who} призначив відповідального за {what}"),
            ("taskCreated", "{who} створив {what}"),
            ("taskDeleted", "{who} видалив {what}"),
            ("taskDone", "{who} завершив {what}"),
            ("taskDue", "Термін {what} настав"),
            ("taskDueTomorrow", "Термін {what} — завтра"),
            ("taskMoved", "{who} перемістив {what} до {state}"),
            ("taskMovedBare", "{who} перемістив {what} до іншого проєкту"),
            ("taskRejected", "{who} вирішив не робити {what}"),
            ("test", "Тестове повідомлення від Amenbo — цей проєкт звітує сюди."),
            ("unknown", "{who} щось зробив з {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Запуск автоматизації скасовано."),
            ("completed", "Запуск автоматизації завершено."),
            ("crashed", "Запуск автоматизації завершився невдачею: крок закінчився без звіту — його програма завершилася, або Amenbo перезапустився під час роботи."),
            ("halted", "Запуск автоматизації зупинився, щоб покликати людину: крок вийшов через вихід, який кличе людину."),
            ("leftTaskOpen", "Запуск автоматизації завершився невдачею: він пішов далі, не закривши взяте завдання."),
            ("line", "{why} {reached} (запуск {run})"),
            ("maxTimes", "Запуск автоматизації завершився невдачею: шлях назад пройдено стільки разів, скільки дозволено."),
            ("noAgent", "Запуск автоматизації завершився невдачею: не вдалося запустити агента, якого просив крок."),
            ("noInput", "Запуск автоматизації завершився невдачею: обов’язковий вхід кроку був порожній."),
            ("noWayOn", "Запуск автоматизації завершився невдачею: не залишилося кроку, який можна відкрити."),
            ("reached", "Він дійшов до «{step}»."),
            ("reachedGone", "Він дійшов до кроку, якого більше немає."),
            ("reachedNothing", "Він зупинився, не відкривши жодного кроку."),
        ],
        statuses: &[
            ("blocked", "Заблоковано"),
            ("done", "Готово"),
            ("in_progress", "У роботі"),
            ("rejected", "Відхилено"),
            ("todo", "До виконання"),
        ],
    },
    Wording {
        language: "vi",
        says: &[
            ("commentAdded", "{who} đã bình luận về {what}"),
            ("commentAddedBare", "{who} đã thêm {what}"),
            ("commentRemoved", "{who} đã rút lại bình luận về {what}"),
            ("commentRemovedBare", "{who} đã rút lại {what}"),
            ("decisionAccepted", "{who} đã viết xong {what}"),
            ("decisionRejected", "{who} đã bác {what}"),
            ("statusChanged", "{who} đã chuyển {what} sang {state}"),
            ("statusChangedBare", "{who} đã đổi trạng thái của {what}"),
            ("subject.commentAdded", "Đã thêm bình luận"),
            ("subject.commentRemoved", "Đã thu hồi bình luận"),
            ("subject.count", "{n} cập nhật"),
            ("subject.countOne", "{n} cập nhật"),
            ("subject.decisionAccepted", "Đã viết xong quyết định"),
            ("subject.decisionRejected", "Đã bác quyết định"),
            ("subject.statusChanged", "Công việc: {state}"),
            ("subject.statusChangedBare", "Đã đổi trạng thái công việc"),
            ("subject.taskAssigned", "Đã đổi người phụ trách"),
            ("subject.taskCreated", "Đã tạo công việc"),
            ("subject.taskDeleted", "Đã xóa công việc"),
            ("subject.taskDone", "Đã hoàn thành công việc"),
            ("subject.taskDue", "Công việc đến hạn"),
            ("subject.taskDueTomorrow", "Công việc đến hạn ngày mai"),
            ("subject.taskMoved", "Đã chuyển công việc"),
            ("subject.taskRejected", "Đã bác công việc"),
            ("taskAssigned", "{who} đã giao {what} cho {state}"),
            ("taskAssignedBare", "{who} đã giao {what}"),
            ("taskCreated", "{who} đã tạo {what}"),
            ("taskDeleted", "{who} đã xoá {what}"),
            ("taskDone", "{who} đã hoàn thành {what}"),
            ("taskDue", "{what} đã đến hạn"),
            ("taskDueTomorrow", "{what} đến hạn vào ngày mai"),
            ("taskMoved", "{who} đã chuyển {what} sang dự án {state}"),
            ("taskMovedBare", "{who} đã chuyển {what} sang dự án khác"),
            ("taskRejected", "{who} đã quyết định không làm {what}"),
            ("test", "Tin nhắn thử từ Amenbo — dự án này sẽ báo về đây."),
            ("unknown", "{who} đã tác động đến {what} ({event})"),
        ],
        runs: &[
            ("canceled", "Một lần chạy tự động hoá đã bị hủy."),
            ("completed", "Một lần chạy tự động hoá đã hoàn tất."),
            ("crashed", "Một lần chạy tự động hoá đã thất bại: một bước kết thúc mà không báo cáo — chương trình của nó đã thoát, hoặc Amenbo được khởi động lại khi bước đang chạy."),
            ("halted", "Một lần chạy tự động hoá đã dừng để gọi một người: một bước đã đi ra qua lối ra yêu cầu một người."),
            ("leftTaskOpen", "Một lần chạy tự động hoá đã thất bại: nó đi tiếp mà không đóng tác vụ đã nhận."),
            ("line", "{why} {reached} (lần chạy {run})"),
            ("maxTimes", "Một lần chạy tự động hoá đã thất bại: một đường quay lại đã được đi đủ số lần cho phép."),
            ("noAgent", "Một lần chạy tự động hoá đã thất bại: không khởi động được agent mà một bước yêu cầu."),
            ("noInput", "Một lần chạy tự động hoá đã thất bại: một đầu vào bắt buộc của bước bị trống."),
            ("noWayOn", "Một lần chạy tự động hoá đã thất bại: không còn bước nào để mở."),
            ("reached", "Nó đã đi đến \"{step}\"."),
            ("reachedGone", "Nó đã đi đến một bước không còn tồn tại."),
            ("reachedNothing", "Nó đã dừng trước khi mở bước nào."),
        ],
        statuses: &[
            ("blocked", "Bị chặn"),
            ("done", "Xong"),
            ("in_progress", "Đang làm"),
            ("rejected", "Bị bác"),
            ("todo", "Cần làm"),
        ],
    },
    Wording {
        language: "zh-Hans",
        says: &[
            ("commentAdded", "{who} 评论了 {what}"),
            ("commentAddedBare", "{who} 添加了 {what}"),
            ("commentRemoved", "{who} 撤回了对 {what} 的评论"),
            ("commentRemovedBare", "{who} 撤回了 {what}"),
            ("decisionAccepted", "{who} 写完了 {what}"),
            ("decisionRejected", "{who} 否决了 {what}"),
            ("statusChanged", "{who} 把 {what} 改为{state}"),
            ("statusChangedBare", "{who} 修改了 {what} 的状态"),
            ("subject.commentAdded", "添加评论"),
            ("subject.commentRemoved", "撤回评论"),
            ("subject.count", "{n} 项更新"),
            ("subject.countOne", "{n} 项更新"),
            ("subject.decisionAccepted", "决定写完"),
            ("subject.decisionRejected", "否决决定"),
            ("subject.statusChanged", "任务改为{state}"),
            ("subject.statusChangedBare", "任务状态变更"),
            ("subject.taskAssigned", "变更负责人"),
            ("subject.taskCreated", "创建任务"),
            ("subject.taskDeleted", "删除任务"),
            ("subject.taskDone", "完成任务"),
            ("subject.taskDue", "任务到期"),
            ("subject.taskDueTomorrow", "任务明天到期"),
            ("subject.taskMoved", "移动任务"),
            ("subject.taskRejected", "否决任务"),
            ("taskAssigned", "{who} 把 {what} 分配给了 {state}"),
            ("taskAssignedBare", "{who} 分配了 {what}"),
            ("taskCreated", "{who} 创建了 {what}"),
            ("taskDeleted", "{who} 删除了 {what}"),
            ("taskDone", "{who} 完成了 {what}"),
            ("taskDue", "{what} 已到期"),
            ("taskDueTomorrow", "{what} 明天到期"),
            ("taskMoved", "{who} 把 {what} 移动到了 {state}"),
            ("taskMovedBare", "{who} 把 {what} 移动到了另一个项目"),
            ("taskRejected", "{who} 决定不做 {what}"),
            ("test", "来自 Amenbo 的测试消息——这个项目会报告到这里。"),
            ("unknown", "{who} 对 {what} 做了操作（{event}）"),
        ],
        runs: &[
            ("canceled", "自动化执行已取消。"),
            ("completed", "自动化执行已完成。"),
            ("crashed", "自动化执行失败：某个步骤没有报告就结束了——它的程序退出了，或者 Amenbo 在它运行时重启了。"),
            ("halted", "自动化执行已停下来呼叫人：某个步骤从呼叫人的出口离开了。"),
            ("leftTaskOpen", "自动化执行失败：它没有关闭已领取的任务就继续前进了。"),
            ("line", "{why}{reached}（执行 {run}）"),
            ("maxTimes", "自动化执行失败：某条返回路径已走到允许的次数。"),
            ("noAgent", "自动化执行失败：无法启动步骤要求的代理。"),
            ("noInput", "自动化执行失败：步骤的必填输入为空。"),
            ("noWayOn", "自动化执行失败：没有可以打开的下一个步骤。"),
            ("reached", "进行到了“{step}”。"),
            ("reachedGone", "进行到了一个已不存在的步骤。"),
            ("reachedNothing", "在打开任何步骤之前就停下了。"),
        ],
        statuses: &[
            ("blocked", "受阻"),
            ("done", "已完成"),
            ("in_progress", "进行中"),
            ("rejected", "已否决"),
            ("todo", "待办"),
        ],
    },
    Wording {
        language: "zh-Hant",
        says: &[
            ("commentAdded", "{who} 評論了 {what}"),
            ("commentAddedBare", "{who} 新增了 {what}"),
            ("commentRemoved", "{who} 撤回了對 {what} 的評論"),
            ("commentRemovedBare", "{who} 撤回了 {what}"),
            ("decisionAccepted", "{who} 寫完了 {what}"),
            ("decisionRejected", "{who} 否決了 {what}"),
            ("statusChanged", "{who} 把 {what} 改成{state}"),
            ("statusChangedBare", "{who} 修改了 {what} 的狀態"),
            ("subject.commentAdded", "新增評論"),
            ("subject.commentRemoved", "撤回評論"),
            ("subject.count", "{n} 項更新"),
            ("subject.countOne", "{n} 項更新"),
            ("subject.decisionAccepted", "決定寫完"),
            ("subject.decisionRejected", "否決決定"),
            ("subject.statusChanged", "任務改為{state}"),
            ("subject.statusChangedBare", "任務狀態變更"),
            ("subject.taskAssigned", "變更負責人"),
            ("subject.taskCreated", "建立任務"),
            ("subject.taskDeleted", "刪除任務"),
            ("subject.taskDone", "完成任務"),
            ("subject.taskDue", "任務到期"),
            ("subject.taskDueTomorrow", "任務明天到期"),
            ("subject.taskMoved", "移動任務"),
            ("subject.taskRejected", "否決任務"),
            ("taskAssigned", "{who} 把 {what} 指派給了 {state}"),
            ("taskAssignedBare", "{who} 指派了 {what}"),
            ("taskCreated", "{who} 建立了 {what}"),
            ("taskDeleted", "{who} 刪除了 {what}"),
            ("taskDone", "{who} 完成了 {what}"),
            ("taskDue", "{what} 已到期"),
            ("taskDueTomorrow", "{what} 明天到期"),
            ("taskMoved", "{who} 把 {what} 移動到了 {state}"),
            ("taskMovedBare", "{who} 把 {what} 移動到了另一個專案"),
            ("taskRejected", "{who} 決定不做 {what}"),
            ("test", "來自 Amenbo 的測試訊息——這個專案會報告到這裡。"),
            ("unknown", "{who} 對 {what} 做了操作（{event}）"),
        ],
        runs: &[
            ("canceled", "自動化執行已取消。"),
            ("completed", "自動化執行已完成。"),
            ("crashed", "自動化執行失敗：某個步驟沒有回報就結束了——它的程式結束了，或 Amenbo 在它執行時重新啟動了。"),
            ("halted", "自動化執行已停下來呼叫人：某個步驟從呼叫人的出口離開了。"),
            ("leftTaskOpen", "自動化執行失敗：它沒有關閉已領取的任務就繼續前進了。"),
            ("line", "{why}{reached}（執行 {run}）"),
            ("maxTimes", "自動化執行失敗：某條返回路徑已走到允許的次數。"),
            ("noAgent", "自動化執行失敗：無法啟動步驟要求的代理。"),
            ("noInput", "自動化執行失敗：步驟的必填輸入是空的。"),
            ("noWayOn", "自動化執行失敗：沒有可以開啟的下一個步驟。"),
            ("reached", "進行到了「{step}」。"),
            ("reachedGone", "進行到了一個已不存在的步驟。"),
            ("reachedNothing", "在開啟任何步驟之前就停下了。"),
        ],
        statuses: &[
            ("blocked", "受阻"),
            ("done", "已完成"),
            ("in_progress", "進行中"),
            ("rejected", "已否決"),
            ("todo", "待辦"),
        ],
    },
];
