package main

// Building the catalog fixtures from a checkout of the catalog repository.
//
// `fixtures refresh` copies the outside world, and the catalog is the one face that copying cannot
// always answer for: the published catalog is generated by the catalog repository's own CI, so while
// it lists nothing there is nothing to copy, and the market, the detail view and the update banner
// have no material to be looked at with. The manifests are there all along — the aggregation had just
// never run anywhere a developer could reach.
//
// So this builds the two documents the catalog publishes, out of the reviewed manifests, exactly as
// the catalog's aggregation does — and for the same reason the fixtures are copies and never
// hand-written: what a fixture is worth is that a producer made it. Two properties keep it honest:
//
//   - **The split is amenbo's own.** Which fields are a list entry and which are an install detail is
//     answered by `plugin validate --json`, the same call the catalog's aggregation makes, so this
//     holds no second copy of the schema to fall out of step with. A field amenbo grows rides through.
//   - **What it cannot do, it does not fake.** The catalog signs each distributable with a key only
//     its CI holds. There is no key here, so the details carry the manifest's own `url` / `checksum`
//     and no signature — which is a catalog whose plugins are browsable and do not install. That is
//     what a fixture is for (looking at the market, a detail, the update banner); an install is
//     exercised against the real catalog, and standing that up is `plugin_catalog`'s own e2e.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// catalogV is the envelope version the catalog publishes under — the aggregation's `CATALOG_V`, and
// what a client reads to know it can parse what it fetched.
const catalogV = 1

// officialOwner is the only repository owner whose manifest may claim the official badge. The badge is
// the catalog's curation, never a submitter's self-declaration, so a claim from anyone else is dropped
// rather than published — the same rule the catalog's aggregation enforces, and the fixture would lie
// about the market's trust picture without it.
const officialOwner = "ShiroDoromoto"

// validateManifest runs amenbo's validator over one manifest and hands back the two documents it split
// it into. A package-level variable so a test can answer for the validator without a Rust build — every
// other path here is the real one.
var validateManifest = runValidateManifest

// published is one plugin as the catalog publishes it: the list entry, and the detail document the
// entry's `detail_sum` names — carried with the exact text the detail is written as, because the digest
// is of those bytes and not of a second rendering that could differ by a space.
type published struct {
	name       string
	entry      map[string]any
	detailText []byte
}

// aggregateCatalog builds the catalog envelope and every detail document from the manifests under
// `<repoDir>/plugins`, validating each with `amenboBin`.
//
// A manifest the validator refuses is dropped with its reason on stderr and the rest are still built —
// the same as the catalog's own run, where one bad submission must not take the catalog down with it.
// Returning no entries at all is an error, though: an empty catalog is indistinguishable from a healthy
// one that lists nothing, and writing it over the fixtures would be a fake world nobody meant to build.
func aggregateCatalog(repoDir, amenboBin string) ([]byte, map[string][]byte, error) {
	manifests, err := filepath.Glob(filepath.Join(repoDir, "plugins", "*.yaml"))
	if err != nil {
		return nil, nil, err
	}
	sort.Strings(manifests)
	if len(manifests) == 0 {
		return nil, nil, fmt.Errorf("no manifests under %s", filepath.Join(repoDir, "plugins"))
	}
	featured := readFeatured(filepath.Join(repoDir, "featured.txt"))

	var built []published
	for _, path := range manifests {
		one, err := buildDocuments(repoDir, amenboBin, path, featured)
		if err != nil {
			logf("! %s: %v", filepath.Base(path), err)
			continue
		}
		built = append(built, one)
	}
	if len(built) == 0 {
		return nil, nil, fmt.Errorf("every manifest under %s was rejected", repoDir)
	}

	entries := make([]any, 0, len(built))
	details := make(map[string][]byte, len(built))
	for _, p := range built {
		entries = append(entries, p.entry)
		details[p.name] = p.detailText
	}
	catalog, err := encodeDocument(map[string]any{
		"catalog_v": catalogV,
		// The published catalog stamps the run that generated it, so the fixture does too — a capture
		// that says when it was taken is how a stale fake world is told from a fresh one.
		"generated_at": time.Now().UTC().Format("2006-01-02T15:04:05Z"),
		"plugins":      entries,
	})
	if err != nil {
		return nil, nil, err
	}
	return catalog, details, nil
}

// buildDocuments turns one manifest into what the catalog publishes for it.
//
// Everything the validator handed back rides through untouched; what is added is what only the
// aggregation can know — the digest of the detail as written, when the manifest first landed, and
// whether the curation list recommends it.
func buildDocuments(repoDir, amenboBin, path string, featured map[string]bool) (published, error) {
	entry, detail, err := validateManifest(amenboBin, path)
	if err != nil {
		return published{}, err
	}
	name, _ := entry["name"].(string)
	if name == "" {
		return published{}, fmt.Errorf("the validator reported no name")
	}
	// The file name is the identity a reviewer sees in the diff, so it may not disagree with the
	// manifest — and a detail is fetched by the name the entry carries, so a disagreement here is a
	// fixture whose detail can never be found.
	if stem := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path)); stem != name {
		return published{}, fmt.Errorf("file name does not match the manifest name (%s vs name: %q)", filepath.Base(path), name)
	}
	if official, _ := entry["official"].(bool); official && repoOwner(entry) != officialOwner {
		return published{}, fmt.Errorf("official: true is the catalog's to grant and %q is not the amenbo team", repoOwner(entry))
	}

	detailText, err := encodeDocument(detail)
	if err != nil {
		return published{}, err
	}
	sum := sha256.Sum256(detailText)
	entry["detail_sum"] = "sha256:" + hex.EncodeToString(sum[:])
	entry["added_at"] = addedAt(repoDir, path)
	entry["featured"] = featured[name]
	return published{name: name, entry: entry, detailText: detailText}, nil
}

// repoOwner is the owner half of an entry's `owner/name` — who the official badge would be granted to.
func repoOwner(entry map[string]any) string {
	repo, _ := entry["repo"].(string)
	owner, _, _ := strings.Cut(repo, "/")
	return owner
}

// runValidateManifest is the real validator call: `amenbo --json plugin validate <path>`, reporting
// what it refused rather than guessing around it.
//
// Publishing amenbo's own reading of a manifest is what lets this hold no list of fields to copy and no
// idea of which document each belongs in. A build too old to split a manifest is refused for the same
// reason — a document assembled from a guess is the silent drop this arrangement exists to end.
func runValidateManifest(amenboBin, path string) (map[string]any, map[string]any, error) {
	// Captured rather than run through the shared helper: a refused manifest is reported as JSON on
	// stdout *and* exits non-zero, so the report has to survive the failure to be the reason.
	cmd := exec.Command(amenboBin, "--json", "plugin", "validate", path)
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	runErr := cmd.Run()
	var report struct {
		OK         bool           `json:"ok"`
		Entry      map[string]any `json:"entry"`
		Detail     map[string]any `json:"detail"`
		ParseError string         `json:"parse_error"`
		Problems   []struct {
			Location string `json:"location"`
			Message  string `json:"message"`
		} `json:"problems"`
	}
	if err := decodeDocument(stdout.Bytes(), &report); err != nil {
		said := strings.TrimSpace(stderr.String())
		if said == "" {
			said = strings.TrimSpace(stdout.String())
		}
		if runErr != nil && said == "" {
			said = runErr.Error()
		}
		return nil, nil, fmt.Errorf("amenbo plugin validate did not report: %s", said)
	}
	if !report.OK {
		if report.ParseError != "" {
			return nil, nil, fmt.Errorf("not a valid manifest — %s", report.ParseError)
		}
		problems := make([]string, 0, len(report.Problems))
		for _, p := range report.Problems {
			problems = append(problems, p.Location+": "+p.Message)
		}
		return nil, nil, fmt.Errorf("invalid manifest — %s", strings.Join(problems, "; "))
	}
	if report.Entry == nil || report.Detail == nil {
		return nil, nil, fmt.Errorf("validate reported ok but no entry/detail — the amenbo build is too old to split a manifest")
	}
	return report.Entry, report.Detail, nil
}

// readFeatured reads the curation list: the plugins this catalog recommends, one name per line, with
// blanks and `#` comments ignored. A missing file means nothing is recommended yet, which is a state
// and not a failure. It is a set and not a ranking — the order of the lines says nothing.
func readFeatured(path string) map[string]bool {
	names := map[string]bool{}
	body, err := os.ReadFile(path)
	if err != nil {
		return names
	}
	for _, line := range strings.Split(string(body), "\n") {
		if name := strings.TrimSpace(strings.SplitN(line, "#", 2)[0]); name != "" {
			names[name] = true
		}
	}
	return names
}

// addedAt is when a manifest first landed, from the checkout's git history — the "new" axis of the
// market. A client holds the catalog and not the repository, so this date exists only because the
// aggregation writes it down. Nil outside a checkout, or for a manifest not committed yet.
func addedAt(repoDir, path string) any {
	out, err := run(repoDir, "git", "log", "--diff-filter=A", "--format=%aI", "--", path)
	if err != nil {
		return nil
	}
	lines := strings.Fields(out)
	if len(lines) == 0 {
		return nil
	}
	// The last line is the oldest: when it landed, not when it was last moved.
	return lines[len(lines)-1]
}

// encodeDocument writes one published document the way the catalog writes it — sorted keys, two-space
// indent, a trailing newline, and no HTML escaping. Both files go through here, so `detail_sum` is a
// digest of exactly the bytes the detail file holds.
func encodeDocument(document any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(document); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// decodeDocument reads JSON with numbers left as they were written. A catalog carries version numbers
// and sizes that must be republished as themselves: decoded into float64 and written back, `payload_v:
// 1` is one rendering away from `1e+00`.
func decodeDocument(body []byte, into any) error {
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.UseNumber()
	return dec.Decode(into)
}
