// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityItemDto = { id: number, 
/**
 * Which id sequence this row's `id` was drawn from (`amenbo_core::activity::Seq::rank`). The
 * timeline merges sources that number independently, so `id` alone names no row: a task comment
 * and a decision comment can carry the same one (`AMB-D-388`). A front end that identifies rows —
 * to de-duplicate a page boundary, or to key a list — has to pair the two.
 */
seq: number, at: string, ago: string, kind: "system" | "comment", author: ActorDto, target: ActivityTargetDto, event?: EventDto, text?: string, 
/**
 * Comment rows only: relative time of a later in-place edit of the body. Absent when it was
 * never edited. No revision history is kept, so this is the only hint a reader gets that the
 * body is not what they read a moment ago.
 */
editedAgo?: string, };

export type ActivityTargetDto = { 
/**
 * Decisions are destinations too (`decision.deleted` names a decision in the ledger's decision
 * column). If the type only said task/project, the front end's branch would drop decisions on
 * the floor.
 */
type: "task" | "project" | "decision", id: number, title: string, 
/**
 * Is the target still around? Only a live target can be a destination — rows for deleted tasks,
 * projects and decisions stay in the ledger but have nowhere to open, so it is this, not the
 * type, that decides whether the row is clickable.
 */
live: boolean, };

export type ActorDto = { name: string, kind: "human" | "ai", 
/**
 * Optional avatar image for the facet (data URL). The roster loads it from config; other
 * ActorDto uses (assignee, author) leave it unset. Omitted when unset, and the front end draws
 * an identicon instead.
 */
avatar?: string, };

/**
 * One row of the collapsible "Archived (N)" section at the foot of the sidebar. These never ride
 * in the snapshot's `ProjectDto` (which comes from `project_overview` — active projects only), so
 * they are fetched over a dedicated read path, `project_list_archived`. Restoring navigates to the
 * settings screen by this id and calls `project_set_archived`.
 */
export type ArchivedProjectDto = { id: number, name: string, color: string, };

/**
 * One attachment on a task or decision record, for the GUI's viewer. The blob's bytes do not ride
 * along — only the metadata needed to branch on `mime` and to assemble the stream URL
 * (`blobHash`). `present` says whether the blob's bytes are on this machine (metadata survives
 * without them, and then it is false; there is no way to get them back, so the viewer cannot open
 * it). In `url` mode, `url` is set and the blob metadata is empty.
 */
export type AttachmentDto = { id: number, kind: "blob" | "url", blobHash: string | null, filename: string | null, mime: string | null, sizeBytes: bigint | null, url: string | null, 
/**
 * Are the blob's bytes on this machine? (Meaningless in `url` mode, where it is always false.)
 */
present: boolean, createdByKind: "human" | "ai" | null, };

/**
 * What [`run_backup`] returns: the camelCase DTO of core's
 * [`amenbo_core::archive::BackupReport`].
 */
export type BackupReportDto = { 
/**
 * Path of the archive that was written.
 */
path: string, 
/**
 * Size of the archive, in bytes.
 */
bytes: number, };

/**
 * One bound folder, as listed by the folder manager on the project settings screen. `path` is the
 * absolute path where the `.amenbo` pointer was placed; `exists` says whether that folder is still
 * there (false means moved or deleted — stale, and we offer a way to clean it up). Same shape as
 * the CLI's `project show` `bound_folders` (`bound_folders_json`).
 * `mismatch` is the verdict "that folder's `.amenbo` belongs to a different store"
 * ([`SlugMismatchDto`]). `legacy` means "the pointer is in the old format (`project_id` is not
 * readable as an integer)" — both are fixed by the same relink (rewriting the pointer in the
 * current format). A pointer with no `project_id` cannot mismatch, so the two are exclusive.
 * `pointer_missing` means "the folder is there, but it has no readable `.amenbo`" — the registry
 * points at this project, yet an AI started in that folder will not resolve here (it walks up to a
 * parent, or falls back to `init` recovery). Exclusive with the other two (no pointer, nothing to
 * inspect inside it), and the fix is the same relink.
 */
export type BoundFolderDto = { path: string, exists: boolean, mismatch: SlugMismatchDto | null, legacy: boolean, pointerMissing: boolean, };

/**
 * The payload of the `data-progress` event: the camelCase DTO of core's
 * [`amenbo_core::progress::Progress`]. `phase` is the stable string from [`phase_str`], which the
 * GUI localizes. The startup migration ([`crate::migrate`]) reports itself in the same shape — one
 * way of showing progress is enough.
 */
export type DataProgressDto = { 
/**
 * What it is doing (`snapshotting`, `verifying`, `copying`, ...; the GUI localizes it).
 */
phase: string, 
/**
 * Units completed (from 0).
 */
done: number, 
/**
 * Total units, when known.
 */
total: number | null, };

/**
 * One permanent comment on a decision record, for the GUI. Task comments ride in the per-task
 * `task_activity` (kind=comment), but decisions have no activity path, so they get a read DTO of
 * their own. The author's facet is resolved to a display name from config, and the relative time
 * `ago` is worded here (the front end does nothing but render).
 */
export type DecisionCommentDto = { id: number, ago: string, author: ActorDto, text: string, 
/**
 * Relative time of a later edit of the body. Absent when it was never edited (same meaning and
 * same treatment as [`ActivityItemDto::edited_ago`] on task comments).
 */
editedAgo?: string, };

/**
 * One decision record. The real data behind the list, the detail view and the cross-links.
 */
export type DecisionDto = { id: number, 
/**
 * Conversational ref (`D-<n>`, a numbering space of its own, separate from tasks). The display
 * form of `id`.
 */
ref: string, title: string, body: string, 
/**
 * proposed / accepted / rejected. "Superseded" is not a status — look at `current`.
 */
status: "proposed" | "accepted" | "rejected", 
/**
 * Is it current? (derived projection, never stored): true unless a live `supersedes` edge
 * points at it.
 */
current: boolean, 
/**
 * The project it lives under (the id is an integer key).
 */
project: ProjectRefDto | null, 
/**
 * Decisions this one replaced (supersession, forward). One decision can replace several.
 */
supersedes: Array<DecisionRefDto>, 
/**
 * Decisions that replaced this one (reverse lookup).
 */
supersededBy: Array<DecisionRefDto>, 
/**
 * Decisions this one partially revised (amends, forward; the target stays current).
 */
amends: Array<DecisionRefDto>, 
/**
 * Decisions that partially revised this one (reverse lookup).
 */
amendedBy: Array<DecisionRefDto>, 
/**
 * Decisions this one takes as a premise (builds_on, forward) — read them first. They stay current.
 */
buildsOn: Array<PremiseRefDto>, 
/**
 * Decisions that take this one as a premise (reverse lookup) — what would need revisiting if
 * this one were overturned (the blast radius).
 */
builtOnBy: Array<DecisionRefDto>, decidedAt: string | null, decidedBy: PlainRefDto | null, 
/**
 * Linked tasks (cross-link), carrying status — is the work this decision created still open?
 */
linkedTasks: Array<LinkedTaskRefDto>, createdAt: string, };

/**
 * What `decision_page` returns: the decisions on the page, plus the total count before paging.
 */
export type DecisionPageDto = { decisions: Array<DecisionDto>, totalMatched: number, };

/**
 * A reference to a record a decision points at, or is pointed at by (id + display name +
 * conversational ref). For cross-link display: `D-<n>` when the target is a decision, `#<n>` when
 * it is a task (the numbering spaces are separate). Both ids are integer keys.
 */
export type DecisionRefDto = { id: number, 
/**
 * `null` when a forward edge dangles (a supersedes / amends target no longer live); the screen
 * composes the placeholder in `config.language`. Reverse edges always carry a name.
 */
name: string | null, ref?: string, };

/**
 * One unified dimension (classification axis), values included, so the GUI's dimension editor and
 * assignment selects render from real data. `role` is `none` or `time_axis` (phase); `ordered`
 * says whether the values have an order.
 */
export type DimensionDto = { id: number, name: string, notes: string, role: "none" | "time_axis", ordered: boolean, values: Array<DimensionValueDto>, };

/**
 * The per-task assigned value for one project × dimension (`taskId`→`valueId`). The board uses it
 * to bundle tasks by value on the chosen dimension (browsing/grouping).
 */
export type DimensionTaskValueDto = { taskId: number, valueId: number, };

/**
 * One value of a dimension (a choice on the axis). Ordered dimensions arrive in `order_key` order.
 */
export type DimensionValueDto = { id: number, name: string, 
/**
 * Start of the period, `YYYY-MM-DD` (inclusive). Omitted means an open start. A period is the
 * payload of `role: time_axis`, not a generic attribute of a value — reads pass it straight
 * through, and the gatekeeper for showing the date fields sits in the GUI.
 */
startOn?: string, 
/**
 * End of the period, `YYYY-MM-DD` (inclusive). Omitted means "ongoing" (an open end).
 */
endOn?: string, };

/**
 * What `doctor_fix` returns: what was cleaned up, and how much of it.
 */
export type DoctorFixDto = { reclaimedBlobs: number, freedBytes: number, forgottenBindings: number, };

/**
 * One issue on the doctor screen (the same shape as core's
 * [`amenbo_core::validate::DoctorIssue`]). **No prose sentence rides along**: core returns only a
 * `kind` (the id of a message template) and `params` (what differs), and the surface composes the
 * sentence a person reads (the GUI localizes it by `config.language`; the CLI is always English).
 * The GUI's message table, and the affordances for how to fix each issue, live in
 * `src/core/i18n.ts`, and they point at affordances that really exist in the GUI (the repair button
 * under Settings > Integrity, the folder list in project settings).
 */
export type DoctorIssueDto = { kind: string, severity: string, target: string, params: { [key in string]: string }, };

/**
 * What `doctor_report` returns.
 */
export type DoctorReportDto = { ok: boolean, errors: number, warnings: number, issues: Array<DoctorIssueDto>, };

export type EventDto = { kind: string, text: string, };

/**
 * What [`run_export`] returns: the directory it wrote to, how big it is, and how many attachments
 * were carried out.
 */
export type ExportReportDto = { path: string, 
/**
 * Total bytes of the directory that was written (`export.json` plus the attachment files). This
 * is the number the completion message shows in KB — count only the JSON and a bundle carrying
 * heavy attachments would claim to be far smaller than it is.
 */
bytes: number, 
/**
 * How many attachment files were written into `attachments/`.
 */
attachments: number, 
/**
 * How many attachments could not be carried out because their bytes are gone (we do not drop
 * them silently).
 */
missing: number, };

/**
 * One bound repository the banner has something to say about — the raw material for its wording, never
 * the sentence, as with [`HookOfferDto`].
 *
 * Its two lists are two different things: [`HookNoticeDto::unwired`] is a standing state (the lint is not
 * running in these slots, and `hooks install` wires them — coexisting with another tool's hook where one
 * is there), while [`HookNoticeDto::restored`] is a transient event (a block of ours was found damaged or
 * stale this session and put back). A repository appears when either list is non-empty.
 */
export type HookNoticeDto = { 
/**
 * The project's name, so the banner can say which one it is about.
 */
projectName: string, 
/**
 * The git repository this notice is about, which is also what identifies it.
 */
dir: string, 
/**
 * What this build is called on the command line, for the same reason [`HookOfferDto::cmd`]
 * carries it: the dev channel answers `amenbo-dev` and the wording must not spell either in.
 */
cmd: string, 
/**
 * Slots with no block of ours (empty, or another tool's hook without amenbo's block), which
 * `hooks install` wires.
 */
unwired: Array<string>, 
/**
 * Slots whose block of ours was found damaged or stale this session and restored — something had
 * changed or removed it (a tool regenerating its hook, a hand-edit). Empty in the ordinary case.
 */
restored: Array<string>, };

/**
 * The question waiting to be put to the user: may amenbo wire its lint into your git hooks?
 *
 * **There is one of it, ever** — not one per repository. It carries only what the wording needs, which is
 * the name of this build, and nothing about where an answer would land. Which repositories are bound,
 * which slots are empty, which a stranger holds, whether the hooks directory is one the whole team shares
 * — all of that is `amenbo_core::hooks::install`'s to act on, and none of it is a fork in the user's
 * road: nobody wants an AMB-T-… in their commits *here* but not *there*, so a screen that laid the
 * machinery out — or listed the folders — would be asking them to solve amenbo's problem. What is still
 * unwired afterwards is the setup banner's to report ([`HookNoticeDto`]), where it is a statement rather
 * than a question.
 */
export type HookOfferDto = { 
/**
 * What this build of amenbo is called on the command line, which is what its hooks will actually
 * run and what its guidance tells the user to type. The dev channel answers `amenbo-dev`, so the
 * name travels rather than being spelled into the wording.
 */
cmd: string, };

/**
 * A reference to a task a decision spawned. A [`DecisionRefDto`] plus **status**, so the screen can
 * answer "is this decision's work finished yet?". Completed ones are muted on the screen side.
 */
export type LinkedTaskRefDto = { id: number, name: string, ref?: string, status: "todo" | "in_progress" | "done" | "blocked" | "rejected", };

/**
 * [`amenbo_core::migrate::MigrationReport`] as the completion panel reads it.
 */
export type MigrationDoneDto = { 
/**
 * The version the store came from.
 */
from: number, 
/**
 * The version it is at now.
 */
to: number, 
/**
 * Where the pre-migration backup is kept — the only way back (there is no downgrade).
 */
backupPath: string | null, 
/**
 * The pre-migration backups from earlier migrations that this run's own backup superseded, and which
 * it therefore deleted. Shown, never silent.
 */
superseded: Array<string>, };

/**
 * [`amenbo_core::migrate::Pending`] as the screen reads it: the two versions, the steps between them, and
 * the disk the pre-migration backup needs. Bytes, not MiB — the rounding belongs on the side that has the
 * reader.
 */
export type MigrationPendingDto = { 
/**
 * The format version the store carries now.
 */
from: number, 
/**
 * The version the chain will carry it to.
 */
to: number, 
/**
 * How many steps stand between the two.
 */
steps: number, 
/**
 * Upper bound on the finished archive.
 */
archiveBytes: number, 
/**
 * Transient peak on top of it (the staged snapshot, deleted once appended).
 */
stagingBytes: number, 
/**
 * What must be free for the backup to complete.
 */
requiredBytes: number, 
/**
 * What is actually free where the backup lands.
 */
availableBytes: number, };

/**
 * The camelCase DTO of a version-chain run (core's
 * [`amenbo_core::store_engine::migrate::Run`]).
 */
export type MigrationRunDto = { 
/**
 * The format version the store carried before the run. `number` on the TS side (the default
 * `bigint` cannot be interpolated into a sentence).
 */
from: number, 
/**
 * The format version it carries now.
 */
to: number, 
/**
 * Names of the steps that were applied, in order.
 */
applied: Array<string>, };

/**
 * What the startup migration is doing, for the migration screen.
 */
export type MigrationStatusDto = { 
/**
 * `idle` (nothing to carry forward — no screen) / `running` / `done` / `failed`. A stable string the
 * front switches on; never shown as it is.
 */
stage: string, 
/**
 * What the run is about to do, once core has announced it (`running`, before the first byte is
 * written).
 */
pending: MigrationPendingDto | null, 
/**
 * The latest tick of the run — the pre-migration backup, then the chain's steps — so a window that
 * mounts mid-run has a bar to draw.
 */
progress: DataProgressDto | null, 
/**
 * What the run did (`done`).
 */
report: MigrationDoneDto | null, 
/**
 * Why the run failed (`failed`). The same structured error every store open now refuses with, so the
 * screen localises it exactly like any other (`errLabel`).
 */
error: { code: string; message: string; message_en: string; fields: Record<string, unknown> | null } | null, };

/**
 * Where one task sits (project only — classification lives on the dimension axes). The real data
 * behind the project row in the task detail view.
 */
export type PlacementDto = { project: ProjectRefDto, };

/**
 * A reference with no entity key behind it (a decision's `decided_by` — an opaque token that
 * cannot be looked up).
 */
export type PlainRefDto = { id: string, name: string, };

/**
 * The plugin market view: every entry across the merged catalogs, plus which catalogs answered.
 */
export type PluginCatalogDto = { entries: Array<PluginEntryDto>, sources: Array<PluginCatalogSourceDto>, 
/**
 * How many entries the merge dropped (a manifest the door refused, or a name a later catalog
 * repeated). A count, not the rows: the list's job is to show what a catalog *is* shedding, and
 * the reasons belong to the CLI's `plugin catalog list` (`AMB-D-354`).
 */
dropped: number, };

/**
 * One catalog that fed the merged list — the official one first, then each registered third-party
 * one in registration order.
 */
export type PluginCatalogSourceDto = { url: string, official: boolean, 
/**
 * Whether it answered at all — from the network or, failing that, its cache. `false` contributes
 * nothing to the list, and is what the front end tells the user about rather than failing the view.
 */
reachable: boolean, 
/**
 * How many entries it offered, before cross-catalog de-duplication.
 */
offered: number, };

/**
 * One setting a plugin's author declared, and what this machine currently holds for it
 * (`AMB-D-356`) — everything the generic form needs to draw a row and nothing amenbo judges for
 * itself.
 *
 * The two text tiers are carried separately rather than resolved into one effective value, because
 * the form edits a tier: a project override that is absent has to read as absent, with the machine
 * default it falls back to shown beside it.
 *
 * **A secret's value is never here.** The author's flag is what routes it to the user-area secret
 * file, and a value read back into a webview would be a copy of it in a place `AMB-D-356` keeps it
 * out of — so a secret carries whether it is held, and that is all a form needs to mask it.
 */
export type PluginConfigFieldDto = { 
/**
 * The key the author declared — what a write names, and what a refusal quotes back.
 */
key: string, 
/**
 * The author's own label for the field, drawn as the form's caption.
 */
label: string, 
/**
 * Whether the author marked it secret. The form masks it and stores it once for the device; a
 * text field gets the two tiers instead.
 */
secret: boolean, 
/**
 * Whether the author marked it required. An enable is refused while one of these has no value,
 * so the form says which before the switch does.
 */
required: boolean, 
/**
 * The text machine default, as stored — absent when unset, and always absent for a secret.
 */
machineValue?: string, 
/**
 * The text override held by the project the request named — absent when unset, when no project
 * was named, and always for a secret.
 */
projectValue?: string, 
/**
 * Whether a secret is held for this key on this device. Always false for a text field, whose
 * values say it themselves.
 */
secretSet: boolean, };

/**
 * One entry of the plugin market list. Only what the list draws: identity, the one-line
 * description, and the axes it is filtered on (`AMB-D-347`). Nothing an install needs — the
 * signature, the checksum and the asset map are the detail's, not the list's (`AMB-D-385`).
 */
export type PluginEntryDto = { 
/**
 * The plugin's name, which is its identity in the catalog.
 */
name: string, desc: string, author: string, 
/**
 * `owner/name` — the GitHub coordinates a detail view reads stars and README from, lazily.
 */
repo: string, 
/**
 * The operating systems it supports, as the manifest spells them (`macos` / `windows` / `linux`).
 */
os: Array<string>, category: string, 
/**
 * The official badge: catalog-authoritative, never the manifest author's claim (`AMB-D-347`).
 */
official: boolean, 
/**
 * Whether the official catalog is what served this entry — reviewed onto the official index. The
 * other axis of the same trust picture as `official`, and not derivable from it: an official
 * plugin is always listed, a listed one is written by anybody who passed review, and an entry
 * from a third-party catalog is neither. Which catalog exactly is the `sources` list's business.
 */
listed: boolean, 
/**
 * Whether the official index recommends it — hand curation (`AMB-D-347`), for the "featured"
 * ordering and the badge beside the trust layer. A third axis again: what a plugin is for, rather
 * than who wrote it or who reviewed it. Core has already discounted a third-party catalog's claim
 * on its own entries, so this is answered, not raw.
 */
featured: boolean, 
/**
 * When the catalog first listed it (`YYYY-MM-DD…`), for the "new" ordering. Absent on a catalog
 * that does not record it.
 */
addedAt?: string, };

/**
 * One plugin this machine holds, as the market draws its state on top of the catalog entry of the same
 * name (`AMB-D-351`). Installed and enabled are two facts, not one: an installed plugin that fires
 * nothing is the ordinary state.
 */
export type PluginInstallDto = { 
/**
 * The plugin's name — the key the market joins this row onto a catalog entry by.
 */
name: string, 
/**
 * The level its one switch sits at, as the author declared it (`AMB-D-379`): `project` or `machine`.
 */
scope: "project" | "machine", 
/**
 * Whether it fires at the gate the request named — `null` when there is no answer to give: a
 * project-scoped plugin asked about without a project is not "off", it is unanswered.
 */
enabled?: boolean, 
/**
 * Whether this device has already answered the run-arbitrary-code question for it (`AMB-D-351`).
 * The consent is the device's whichever gate moves, and it is asked **once** — this is what tells a
 * first enable from every later one.
 */
consented: boolean, 
/**
 * Whether this build can speak to it at all (`AMB-D-359`). An open gate on an incompatible plugin
 * fires nothing, and amenbo updates underneath an install, so this is not derivable from `enabled`.
 */
compatible: boolean, 
/**
 * Why not, when `compatible` is false — the mismatch named, rather than left to the log.
 */
incompatibleReason?: string, 
/**
 * The settings the author declared, in that order, each with what this machine holds for it
 * (`AMB-D-356`). Empty for a plugin that declares none, which is the form's own answer to
 * whether there is anything to configure.
 */
config: Array<PluginConfigFieldDto>, 
/**
 * Whether the build the last update replaced is still retained beside this one, so a rollback
 * has somewhere to go (`AMB-D-359`). An update retains exactly one build and a rollback consumes
 * it, so this is false for a plugin that was never updated and false again once it is used.
 */
rollback: boolean, };

/**
 * What an uninstall actually found and removed (`AMB-D-357`) — the receipt the face reports from.
 *
 * Every piece is reported separately because the point of the receipt is that a plugin is more than its
 * binary: the settings and the secrets are the part a user does not picture going, and saying so
 * afterwards is what makes "a re-install starts clean" believable.
 */
export type PluginRemovedDto = { 
/**
 * The plugin was enabled, and its gate has been closed on the way out.
 */
wasEnabled: boolean, 
/**
 * A consent record existed and is gone — a re-install asks again (`AMB-D-351`).
 */
consent: boolean, 
/**
 * Machine-default settings existed and are gone.
 */
machineDefaults: boolean, 
/**
 * Secrets existed and have been purged (`AMB-D-357`'s non-negotiable).
 */
secrets: boolean, 
/**
 * How many per-project setting rows were deleted, across every project.
 */
projectOverrides: number, 
/**
 * How many per-project gate answers were deleted, across every project.
 */
projectGates: number, 
/**
 * The plugin's home under `plugins/` existed and has been removed.
 */
directory: boolean, 
/**
 * The plugin had runs in the execution log and they have been purged (`AMB-D-387`).
 */
runsLog: boolean, 
/**
 * Whether anything at all was found. `false` is not a failure: the name held nothing on this machine.
 */
anything: boolean, };

/**
 * What GitHub says about one plugin's repository — the figures the catalog deliberately does not
 * carry (`AMB-D-347`). Every one is optional on its own: the requests behind them fail
 * independently, and a repository with no release has no download count to report.
 */
export type PluginRepoFactsDto = { 
/**
 * `number` on the TS side (the default `bigint` has no `toLocaleString` grouping to draw it with,
 * and a star count is nowhere near the range that motivates one).
 */
stars?: number, 
/**
 * The current release's downloads, summed over its assets. Whatever else pulls an asset (CI,
 * mirrors) is in there too, so it is a sense of scale rather than a user count (`AMB-D-347`).
 */
downloads?: number, 
/**
 * The README as Markdown, for the front end's renderer (which allows no raw HTML).
 */
readme?: string, 
/**
 * GitHub refused because too many requests came from this address. A different thing to tell the
 * user than a failure: the answer is to wait, not to check the network.
 */
rateLimited: boolean, };

/**
 * One installed plugin the catalog holds a different build of (`AMB-D-359`) — an offer the face can act
 * on, not a diff of two manifests.
 */
export type PluginUpdateDto = { 
/**
 * The plugin's name — how the face names it and how an apply asks for it.
 */
name: string, 
/**
 * What the **new** build says it is, for a line the user can recognise it by.
 */
desc: string, 
/**
 * The offered build's identity for this machine (its asset digest — the same thing detection
 * compared). A face keys a dismissal by it, so a *newer* build surfaces again on its own.
 */
availableChecksum?: string, 
/**
 * Why this one needs a decision before it can be applied, or absent when it can just be applied
 * (`AMB-D-359`: send the user to a screen only when judgment is required). `incompatible` — the
 * offered build cannot run on this amenbo; `settings` — it declares `required` settings this machine
 * has no value for, and the plugin is enabled.
 */
hold?: "incompatible" | "settings", 
/**
 * The settings behind a `settings` hold, named so the face can say which to fill in.
 */
missing: Array<string>, };

/**
 * How one plugin fared in [`plugin_update_apply_all`] — a failure is a row, not the end of the run.
 */
export type PluginUpdateOutcomeDto = { 
/**
 * The plugin this row is about.
 */
name: string, 
/**
 * Whether its build was replaced.
 */
applied: boolean, 
/**
 * Why not, when it was not — core's own sentence, which is the one that knows the reason.
 */
error?: string, };

/**
 * What [`repair_pointers`] returns: how many folders were fixed, and how many were left waiting on
 * a human's judgement.
 */
export type PointerRepairDto = { 
/**
 * Folders whose pointer was rewritten, or written back, in the current format.
 */
repaired: Array<string>, 
/**
 * Folders left untouched because their owner could not be determined uniquely (the human
 * rebinds them through "open folder").
 */
unresolved: Array<string>, };

/**
 * Premises that moved under a task **after it was reserved** (`AMB-D-366`, `AMB-D-373`) — the holder-side
 * surface. Each list is a way readiness was withdrawn since the task went `in_progress`: a blocker that
 * has not ended pinned on, a decision linked but not yet settled, or a decision that was already linked
 * and has stopped being settled. Carried on the card only when there is a change to show (see
 * [`TaskCardDto::premise_change`]), so the screen draws the note exactly when it matters.
 */
export type PremiseChangeDto = { 
/**
 * Not-done blockers whose dependency edge was added after the reservation, in edge order.
 */
addedBlockers: Array<TaskRefDto>, 
/**
 * Unsettled decisions linked after the reservation, in link order.
 */
addedDecisions: Array<DecisionRefDto>, 
/**
 * Decisions already linked that stopped being settled after the reservation, in link order.
 */
reopenedDecisions: Array<DecisionRefDto>, };

/**
 * A reference to a premise decision (the far end of builds_on). It is more than a
 * [`DecisionRefDto`] because it carries **whether the premise is still alive** — surfacing on
 * screen the decisions that stand on a rotten premise (the whole reason this type exists).
 * `superseded_by` is the conversational ref (`AMB-D-<n>`) of the decision that overturned the premise,
 * and is omitted when the premise is current (currency is not stored anywhere else — whether this
 * field is empty *is* the answer).
 */
export type PremiseRefDto = { id: number, 
/**
 * `null` when the premise target dangles (a `builds_on` onto a decision no longer live); the screen
 * composes the placeholder in `config.language`.
 */
name: string | null, ref?: string, 
/**
 * Ref (`D-<n>`) of the decision that overturned the premise. Absent means the premise is current.
 */
supersededBy?: string, };

export type ProjectDto = { id: number, name: string, color: string, view: "list" | "board" | "calendar" | "timeline", 
/**
 * Open task count (todo/in_progress/blocked — anything but done, live only). The sidebar's
 * count badge.
 */
openCount: number, 
/**
 * Proposed (under-discussion) decision count — decisions still awaiting a ruling. Feeds the
 * sidebar row and the header decision button's under-discussion badge.
 */
proposedDecisionCount: number, 
/**
 * Unified dimensions (classification axes). Empty means none are in use. Task classification
 * happens on these axes and nowhere else.
 */
dimensions: Array<DimensionDto>, };

/**
 * A reference to a project (id + display name). The id is an integer key.
 */
export type ProjectRefDto = { id: number, name: string, };

/**
 * The editable fields of one project, so the project settings screen can prefill its form.
 * The snapshot's `ProjectDto` does not carry notes/archived (every project rides in it — keep it
 * light), so we fetch them with `project_get` only when the settings screen opens. `archived` is
 * included (unarchiving is driven from this screen too).
 */
export type ProjectSettingsDto = { id: number, name: string, notes: string, color: string, view: "list" | "board" | "calendar" | "timeline", archived: boolean, };

/**
 * What a reference in a body resolves to (`kind` — task or decision — and the entity's id). The GUI
 * branches on it to decide which detail pane a body link opens.
 */
export type RefTargetDto = { kind: "task" | "decision", 
/**
 * The entity's primary key (an integer for both tasks and decisions). `kind` says which table
 * it points into.
 */
id: number, };

/**
 * What [`run_restore`] returns: the camelCase DTO of core's
 * [`amenbo_core::archive::RestoreReport`].
 */
export type RestoreReportDto = { 
/**
 * Where the old source of truth was set aside when it was replaced. None when nothing was
 * replaced (a fresh creation).
 */
previousSavedTo: string | null, 
/**
 * How many attachment blobs were written (blobs the destination already had, by hash, are not
 * counted).
 */
blobs: number, 
/**
 * How many older rollback points this restore's set-aside copy overtook and deleted. It is a
 * report so that nothing is deleted silently, so the screen shows it only when it is non-zero.
 */
superseded: number, 
/**
 * What the version chain did to the staged store. **Some only when it actually ran**, so a null
 * check is all the front end needs to say "the archive you restored is not in the shape it was
 * taken in".
 */
migration: MigrationRunDto | null, };

/**
 * What `resync_managed_blocks` returns. `scanned` is how many folders that actually exist were
 * walked; `updated` lists the `(dir, file)` pairs rewritten to the current version — only the ones
 * whose content really changed.
 */
export type ResyncReportDto = { scanned: number, updated: Array<ResyncedDto>, };

export type ResyncedDto = { dir: string, file: string, };

/**
 * The slug in `.amenbo` disagrees with what the store actually holds
 * ([`amenbo_core::binding::SlugMismatch`]). The CLI prints an English warning in its location
 * header; the GUI hands over the raw material only and lets i18n compose the wording (same verdict,
 * said differently). **Resolution is not blocked** (the id is authoritative) — we report it and
 * nudge a relink (`project_bind_folder`), nothing more.
 */
export type SlugMismatchDto = { 
/**
 * Primary key of the project the pointer names (whatever this number leads to, it is not the
 * project whose slug was recorded).
 * `number` on the TS side (the default `bigint` cannot be interpolated into the warning text).
 */
projectId: number, 
/**
 * The slug that was written in `.amenbo`.
 */
recorded: string, 
/**
 * The slug of the project `project_id` actually points at (it may not have one).
 */
actual: string | null, };

export type Snapshot = { 
/**
 * The user's language (config.json, global). Decides how the GUI localizes its UI labels. Null
 * when unset.
 */
language: string | null, 
/**
 * How dates are written (config.json, global) — a BCP-47 tag. Null means the one that goes
 * with `language`, which is what most people want; a value is the reader whose two answers
 * differ. Passed through as written: whether a tag is usable is the formatter's judgement, and
 * the front end falls back to the language's rather than failing to draw a date.
 */
dateLocale: string | null, 
/**
 * First-run setup completed (config.json). False makes the GUI show first-run setup.
 */
onboarded: boolean, 
/**
 * This person's roster — the two facets that come from config (human / ai). It is the one
 * supply line for every roster in the GUI: the assignee picker (unassigned / human name / AI
 * name), the display name and avatar in settings, and display-name resolution. `kind` is the
 * facet (`human`/`ai`); `name` is the effective display name from `config.human_name` /
 * `ai_name`.
 */
roster: Array<ActorDto>, projects: Array<ProjectDto>, activity: Array<ActivityItemDto>, 
/**
 * Findings of the read-only integrity check run at startup. If anything is wrong, the GUI
 * raises a warning banner (it never repairs anything by itself). A store with
 * `config.startup_integrity_check` off adds nothing here.
 */
startupHealth: StartupHealthDto, 
/**
 * Whether an update exists. If the published `latest.json` names a version newer than the one
 * running, `updateAvailable=true` — the material for the GUI's "an update is available (open
 * the installer)" banner.
 */
versionStatus: VersionStatusDto, 
/**
 * Level of perf instrumentation (the explicit value of `config.perf_log` — `off`,
 * `budget-only` or `verbose`). Null when unset, and the front end falls back to the dev-build
 * default of on (budget-only).
 */
perfLog: string | null, 
/**
 * Update checking on or off (`config.update_check`, default true). Exposed so the settings
 * screen's toggle can reflect the current value. When off, upstream latest.json is never
 * queried, so `update_available` can never be raised.
 */
updateCheck: boolean, };

/**
 * One bound folder whose managed block is out of date. `version` is the version of that folder's
 * block; `current` is this binary's version ([`amenbo_core::agents::MANAGED_BLOCK_VERSION`]).
 */
export type StaleBlockDto = { dir: string, file: string, version: number, current: number, };

/**
 * The startup integrity check, shaped for the GUI: it feeds a read-only warning banner. Empty means
 * no warning (the counterpart of the CLI's stderr warning).
 */
export type StartupHealthDto = { 
/**
 * The problems doctor found (orphaned or dangling references, and so on). No prose sentence
 * rides along — the GUI composes one from the kind and params in `config.language`
 * (`src/core/i18n.ts`), so we hand these over as the same [`DoctorIssueDto`] the doctor screen
 * uses.
 */
issues: Array<DoctorIssueDto>, };

/**
 * For the "location" line under Settings > Data. Returns the real, OS-independent path (the
 * app-data root).
 */
export type StoreLocationsDto = { 
/**
 * Absolute path of the app-data root (the parent directory of the single `store.sqlite`).
 */
root: string, };

export type TaskCardDto = { id: number, title: string, 
/**
 * The name it goes by on screen, `#<n>` (the display form of `id`).
 */
ref: string, notes: string, projectId: number | null, status: "todo" | "in_progress" | "done" | "blocked" | "rejected", assignee: ActorDto | null, priority: "high" | "medium" | "low" | null, due: string | null, dueLabel: string | null, 
/**
 * Completion timestamp (RFC3339 UTC). Used to sort the Done column newest-first, among other
 * things. None while the task is still open.
 */
completedAt: string | null, comments: number, 
/**
 * Can it be reserved? — no open blockers, every decision it rests on settled, and the declared
 * start day arrived: the three reasons [`amenbo_core::view::ReserveBlocker`] enumerates.
 */
ready: boolean, 
/**
 * Dependencies: blockers that are not done yet (id + name). Drives the "waiting on X" line in
 * the detail pane. Empty means it can be started.
 */
blockedBy: Array<TaskRefDto>, 
/**
 * Where the task sits (with the project's display name), so the detail pane's project row
 * renders from real data. Absent when the task is unplaced (inbox).
 */
placement: PlacementDto | null, createdBy: ActorDto | null, 
/**
 * The decision records that motivated this task (cross-link). Symmetric with
 * `DecisionDto.linked_tasks`; drives navigation from the task detail view to the decision record.
 */
linkedDecisions: Array<DecisionRefDto>, 
/**
 * Those `linked_decisions` that are not settled yet as grounds. Together with `blocked_by` they
 * determine `ready` (both empty means ready). The reason a reservation was refused
 * (`not_ready`) only ever appears in a toast that vanishes in seconds, so we name the decisions
 * that are holding it back, letting the detail pane hold the same fact permanently.
 */
blockedByDecisions: Array<DecisionRefDto>, 
/**
 * The declared start day, when it is still ahead (`YYYY-MM-DD`) — the third reason `ready` is
 * false, beside `blocked_by` and `blocked_by_decisions`. Always serialized, `null` when the start
 * day is no reason, so every `ready: false` the GUI draws carries a reason it can name on screen.
 */
notStartedUntil: string | null, 
/**
 * Premises pinned on **after this task was reserved** (`AMB-D-366`, the holder-side surface): a
 * blocker or an unsettled decision added since it went `in_progress`, silently withdrawing readiness
 * the holder never asked to give up. Present only for an `in_progress` task that actually acquired
 * one — `null` for every other status and when nothing changed — so the surface (a chip on the row,
 * a firm warn when the holder leaves `in_progress`) draws exactly when it should.
 */
premiseChange?: PremiseChangeDto, };

/**
 * One git commit SHA recorded on a task. amenbo keeps the SHA as an opaque string — it
 * never reads git, verifies the commit, or knows which forge it lives on; the AI does that with
 * `git show <sha>`. `createdByKind` is who recorded it (the GUI's actor is always human).
 */
export type TaskCommitDto = { id: number, 
/**
 * The full commit SHA, lower-case hex (40 for SHA-1, 64 for SHA-256).
 */
sha: string, createdByKind: "human" | "ai" | null, };

/**
 * One task × dimension assignment (`valueId` is set on the `dimensionId` axis). The detail pane's
 * assignment selects use it to reflect the current value.
 */
export type TaskDimensionAssignmentDto = { dimensionId: number, valueId: number, };

/**
 * What `task_page` returns: the task cards on the page, plus the total number of matches before
 * paging. The front end sizes its pager or virtual scroller from `total_matched` and draws only the
 * window in `tasks` (it never holds them all).
 */
export type TaskPageDto = { tasks: Array<TaskCardDto>, 
/**
 * Total number of matches, before paging (limit/offset) is applied.
 */
totalMatched: number, 
/**
 * The offset that was applied (how many were skipped).
 */
offset: number, 
/**
 * The limit that was applied (page size). None means no cap — everything from `offset` on.
 */
limit: number | null, };

/**
 * A reference to a task (id + title). The id is an integer key.
 */
export type TaskRefDto = { id: number, name: string, };

/**
 * The **update available** state, for the GUI. Takes the store's `version_status` and raises
 * `update_available` when upstream (the published `latest.json`) names a version newer than the one
 * running. That is what puts up the GUI's "an update is available" banner and its "open the
 * installer" affordance.
 */
export type VersionStatusDto = { 
/**
 * Version of the GUI binary that is running.
 */
appVersion: string, 
/**
 * A newer version exists in the published distribution.
 */
updateAvailable: boolean, 
/**
 * The version being offered (for display; the first one found). `None` means no update.
 */
newerVersion: string | null, };
