// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityItemDto = { id: number, 
/**
 * Which id sequence this row's `id` was drawn from (`amenbo_core::activity::Seq::rank`). The
 * timeline merges sources that number independently, so `id` alone names no row: a task comment
 * and a decision comment can carry the same one (`AMB-D-388`). A front end that identifies rows —
 * to de-duplicate a page boundary, or to key a list — has to pair the two.
 */
seq: number, at: string, kind: "system" | "comment", author: ActorDto, target: ActivityTargetDto, event?: EventDto, text?: string, 
/**
 * Comment rows only: when the body was later edited in place. Absent when it was never edited.
 * No revision history is kept, so this is the only hint a reader gets that the body is not what
 * they read a moment ago.
 */
editedAt?: string, };

export type ActivityTargetDto = { 
/**
 * Decisions are destinations too (`decision.deleted` names a decision in the ledger's decision
 * column). If the type only said task/project, the front end's branch would drop decisions on
 * the floor.
 */
type: "task" | "project" | "decision", id: number, title: string, 
/**
 * Is the target still around? Only a live target can be a destination — rows for deleted tasks,
 * projects and decisions stay in the ledger but have nowhere to open, so it is this, not the
 * type, that decides whether the row is clickable.
 */
live: boolean, };

export type ActorDto = { name: string, kind: "human" | "ai", 
/**
 * Optional avatar image for the facet (data URL). The roster loads it from config; other
 * ActorDto uses (assignee, author) leave it unset. Omitted when unset, and the front end draws
 * an identicon instead.
 */
avatar?: string, 
/**
 * The talk window session this write came from, when the row records one. Set only where an
 * ActorDto is an activity row's **author**; a roster entry or an assignee names a facet, not an
 * act, and leaves it unset. Two AI sessions share one facet, so this is the only thing that tells
 * them apart — and it is read, never inferred: absent means unknown (`AMB-T-3549`).
 */
session?: string, };

/**
 * What in a project was left in the middle by a pane that has gone.
 *
 * Two kinds, kept apart because opening one is not opening the other: a task opens on the ledger's
 * task face and a decision on its decision face. What they have in common is the question — nothing is
 * at either, and Amenbo is asking rather than deciding (`AMB-D-748`).
 */
export type AdriftDto = { 
/**
 * Reservations nothing is working on any more.
 */
tasks: Array<AdriftRowDto>, 
/**
 * Proposals nobody settled.
 */
decisions: Array<AdriftRowDto>, };

/**
 * One record an empty slot asks about: what to call it, and what it is called.
 *
 * It carries what the row draws and nothing else. A card would carry a body and a status the row
 * never shows, and this is read once per screen — the answer is what to put in front of a person, not
 * the record itself, which is a press away on the face that owns it.
 */
export type AdriftRowDto = { 
/**
 * The primary key, which is what a press hands to the face that opens it.
 */
id: number, 
/**
 * The name it goes by on screen (`AMB-T-<n>` / `AMB-D-<n>`), which is also what says which of the
 * two kinds a row is — the refs are two numbering spaces and a reader knows them apart.
 */
ref: string, title: string, };

/**
 * The whole catalog and this project's folders — what the settings screen's "take the request" face is
 * drawn from (`AMB-D-670`).
 *
 * **Two lists, not rows.** [`agent_hook_project_wiring`](crate::commands::agent_hook_project_wiring) answers with the tools a folder is waiting on,
 * so its unit is a pairing and a tool nothing waits for is left out. This one is the reader coming to
 * fetch text, so the tool is theirs to pick out of the whole catalog and the folders are the same
 * wherever they paste it — pairing them would be inventing an order the reader already knows.
 */
export type AgentHookRequestsDto = { 
/**
 * Every harness Amenbo knows, in catalog order, each with the text that asks for its wiring.
 */
tools: Array<AgentHookToolDto>, 
/**
 * This project's bound folders — where the picked tool's request is pasted. Empty for a project
 * nothing is bound to.
 */
dirs: Array<string>, };

/**
 * One AI harness a folder could start its session on `amenbo agent` with, and the text that would do it
 * ([`amenbo_core::harness`]).
 *
 * The request travels with the row rather than being fetched on a click, because the surface it is on
 * both shows it and copies it: text fetched on the click would be text nobody read, and a button that
 * had to go and ask first could hand over an empty clipboard with no second chance to notice. It is a
 * few hundred bytes per unwired tool.
 */
export type AgentHookToolDto = { 
/**
 * The catalog's own id for it (`claude-code`), which is also what `agent-hook snippet` takes.
 */
tool: string, 
/**
 * The product's name for itself, for the sentence.
 */
label: string, 
/**
 * The file the configuration goes into, relative to the folder.
 */
pasteInto: string, 
/**
 * What the reader is handed: the request to give the AI they work with, carrying the configuration
 * and this build's launch command ([`amenbo_core::harness::request`]).
 */
request: string, };

/**
 * One harness a project is still waiting to be wired to, and the folders waiting for it — what the
 * project screen's standing row is drawn from (`AMB-D-459`).
 *
 * **One text, many folders.** The request for a harness is the same wherever it is pasted; only the path
 * it goes into changes. So the tool is carried once and the folders are a list beside it, rather than the
 * text being repeated per folder — which is what kept the startup banner from being readable at four
 * folders.
 */
export type AgentHookWiringDto = { 
/**
 * The harness, with the text that asks for its wiring.
 */
tool: AgentHookToolDto, 
/**
 * This project's folders where that tool is not wired. Never empty — a tool nothing is waiting for
 * is left out rather than carried with an empty list.
 */
dirs: Array<string>, };

/**
 * One row of the collapsible "Archived (N)" section at the foot of the sidebar. These never ride
 * in the snapshot's `ProjectDto` (which comes from `project_overview` — active projects only), so
 * they are fetched over a dedicated read path, `project_list_archived`. Restoring navigates to the
 * settings screen by this id and calls `project_set_archived`.
 */
export type ArchivedProjectDto = { id: number, name: string, color: string, };

/**
 * One attachment on a task or decision record, for the GUI's viewer. The blob's bytes do not ride
 * along — only the metadata needed to branch on `mime` and to assemble the stream URL
 * (`blobHash`). `present` says whether the blob's bytes are on this machine (metadata survives
 * without them, and then it is false; there is no way to get them back, so the viewer cannot open
 * it). In `url` mode, `url` is set and the blob metadata is empty.
 */
export type AttachmentDto = { id: number, kind: "blob" | "url", blobHash: string | null, filename: string | null, mime: string | null, sizeBytes: bigint | null, url: string | null, 
/**
 * Are the blob's bytes on this machine? (Meaningless in `url` mode, where it is always false.)
 */
present: boolean, createdByKind: "human" | "ai" | null, };

/**
 * What [`run_backup`](crate::commands::run_backup) returns: the camelCase DTO of core's
 * [`amenbo_core::archive::BackupReport`].
 */
export type BackupReportDto = { 
/**
 * Path of the archive that was written.
 */
path: string, 
/**
 * Size of the archive, in bytes.
 */
bytes: number, };

/**
 * One bound folder, as listed by the folder manager on the project settings screen. `path` is the
 * absolute path where the `.amenbo` pointer was placed; `exists` says whether that folder is still
 * there (false means moved or deleted — stale, and we offer a way to clean it up). Same shape as
 * the CLI's `project show` `bound_folders` (`bound_folders_json`).
 * `mismatch` is the verdict "that folder's `.amenbo` belongs to a different store"
 * ([`SlugMismatchDto`]). `legacy` means "the pointer is in the old format (`project_id` is not
 * readable as an integer)" — both are fixed by the same relink (rewriting the pointer in the
 * current format). A pointer with no `project_id` cannot mismatch, so the two are exclusive.
 * `pointer_missing` means "the folder is there, but it has no readable `.amenbo`" — the registry
 * points at this project, yet an AI started in that folder will not resolve here (it walks up to a
 * parent, or falls back to `init` recovery). Exclusive with the other two (no pointer, nothing to
 * inspect inside it), and the fix is the same relink.
 * `foreign` is the one finding that says the folder is **refused** rather than merely suspect
 * ([`ForeignStoreDto`], `AMB-D-685`): the pointer names another store, so a command run there stops
 * before it reads anything. The row would otherwise look healthy, which is the whole reason it is
 * carried here — and the fix is again the same relink, this build claiming the folder for itself.
 */
export type BoundFolderDto = { path: string, exists: boolean, mismatch: SlugMismatchDto | null, legacy: boolean, pointerMissing: boolean, foreign: ForeignStoreDto | null, };

/**
 * The payload of the `data-progress` event: the camelCase DTO of core's
 * [`amenbo_core::progress::Progress`]. `phase` is the stable string from `phase_str`, which the
 * GUI localizes. The startup migration ([`crate::migrate`]) reports itself in the same shape — one
 * way of showing progress is enough.
 */
export type DataProgressDto = { 
/**
 * What it is doing (`snapshotting`, `verifying`, `copying`, ...; the GUI localizes it).
 */
phase: string, 
/**
 * Units completed (from 0).
 */
done: number, 
/**
 * Total units, when known.
 */
total: number | null, };

/**
 * One permanent comment on a decision record, for the GUI. Task comments ride in the per-task
 * `task_activity` (kind=comment), but decisions have no activity path, so they get a read DTO of
 * their own. The author's facet is resolved to a display name from config; the times are sent as
 * they are, for the front end to word.
 */
export type DecisionCommentDto = { id: number, at: string, author: ActorDto, text: string, 
/**
 * When the body was later edited. Absent when it was never edited (same meaning and same
 * treatment as [`ActivityItemDto::edited_at`] on task comments).
 */
editedAt?: string, };

/**
 * One decision record. The real data behind the list, the detail view and the cross-links.
 */
export type DecisionDto = { id: number, 
/**
 * Conversational ref (`D-<n>`, a numbering space of its own, separate from tasks). The display
 * form of `id`.
 */
ref: string, title: string, body: string, 
/**
 * proposed / accepted / rejected. "Superseded" is not a status — it is an edge, and
 * `superseded_by` is where it is read.
 */
status: "proposed" | "accepted" | "rejected", 
/**
 * The project it lives under (the id is an integer key).
 */
project: ProjectRefDto | null, 
/**
 * Decisions this one replaced (supersession, forward). One decision can replace several.
 */
supersedes: Array<DecisionRefDto>, 
/**
 * Decisions that replaced this one (reverse lookup).
 */
supersededBy: Array<DecisionRefDto>, 
/**
 * Decisions this one partially revised (amends, forward; the target stays current).
 */
amends: Array<DecisionRefDto>, 
/**
 * Decisions that partially revised this one (reverse lookup).
 */
amendedBy: Array<DecisionRefDto>, 
/**
 * Decisions this one takes as a premise (builds_on, forward) — read them first. They stay current.
 */
buildsOn: Array<PremiseRefDto>, 
/**
 * Decisions that take this one as a premise (reverse lookup) — what would need revisiting if
 * this one were overturned (the blast radius).
 */
builtOnBy: Array<DecisionRefDto>, decidedAt: string | null, decidedBy: PlainRefDto | null, 
/**
 * Linked tasks (cross-link), carrying status — is the work this decision created still open?
 */
linkedTasks: Array<LinkedTaskRefDto>, createdAt: string, 
/**
 * When it last changed in any way — a body edit and a status transition alike. The pane hides it
 * where it only repeats `created_at` or `decided_at`, so it reads as "changed since".
 */
updatedAt: string, };

/**
 * What `decision_page` returns: the decisions on the page, plus the total count before paging.
 */
export type DecisionPageDto = { decisions: Array<DecisionDto>, totalMatched: number, };

/**
 * A reference to a record a decision points at, or is pointed at by (id + display name +
 * conversational ref). For cross-link display: `D-<n>` when the target is a decision, `#<n>` when
 * it is a task (the numbering spaces are separate). Both ids are integer keys.
 */
export type DecisionRefDto = { id: number, 
/**
 * `null` when a forward edge dangles (a supersedes / amends target no longer live); the screen
 * composes the placeholder in `config.language`. Reverse edges always carry a name.
 */
name: string | null, ref?: string, };

/**
 * One unified dimension (classification axis), values included, so the GUI's dimension editor and
 * assignment selects render from real data. `role` is `none` or `time_axis` (phase); `ordered`
 * says whether the values have an order; `showOnCard` says whether a task's value on this axis
 * belongs on its card (`AMB-D-651`) — the axis's own answer, so it reads the same on every device;
 * `required` says the axis refuses to be left empty (`AMB-D-734`), which the detail pane reads to
 * hold "finish creating" back rather than letting the write be refused at the door; `slug` is the
 * readable key the axis and each of its values answer to outside Amenbo (`AMB-D-735`).
 */
export type DimensionDto = { id: number, name: string, 
/**
 * The axis's readable key (`AMB-D-735`), the counterpart of a value's. Omitted only for a row
 * still being written; every saved axis carries one.
 */
slug?: string, notes: string, role: "none" | "time_axis", ordered: boolean, showOnCard: boolean, required: boolean, values: Array<DimensionValueDto>, };

/**
 * The per-task assigned value for one project × dimension (`taskId`→`valueId`). The board uses it
 * to bundle tasks by value on the chosen dimension (browsing/grouping).
 */
export type DimensionTaskValueDto = { taskId: number, valueId: number, };

/**
 * One value of a dimension (a choice on the axis). Ordered dimensions arrive in `order_key` order.
 */
export type DimensionValueDto = { id: number, name: string, 
/**
 * The value's readable key (`AMB-D-735`) — what names it outside Amenbo, where its display name
 * cannot go. Omitted only for a row still being written; every saved value carries one.
 */
slug?: string, 
/**
 * Start of the period, `YYYY-MM-DD` (inclusive). Omitted means an open start. A period is the
 * payload of `role: time_axis`, not a generic attribute of a value — reads pass it straight
 * through, and the gatekeeper for showing the date fields sits in the GUI.
 */
startOn?: string, 
/**
 * End of the period, `YYYY-MM-DD` (inclusive). Omitted means "ongoing" (an open end).
 */
endOn?: string, };

/**
 * What `doctor_fix` returns: what was cleaned up, and how much of it.
 */
export type DoctorFixDto = { reclaimedBlobs: number, freedBytes: number, forgottenBindings: number, };

/**
 * One issue on the doctor screen (the same shape as core's
 * [`amenbo_core::validate::DoctorIssue`]). **No prose sentence rides along**: core returns only a
 * `kind` (the id of a message template) and `params` (what differs), and the surface composes the
 * sentence a person reads (the GUI localizes it by `config.language`; the CLI is always English).
 * The GUI's message table, and the affordances for how to fix each issue, live in
 * `src/core/i18n/locales/`, and they point at affordances that really exist in the GUI (the repair button
 * under Settings > Integrity, the folder list in project settings).
 */
export type DoctorIssueDto = { kind: string, severity: string, target: string, params: { [key in string]: string }, };

/**
 * What `doctor_report` returns.
 */
export type DoctorReportDto = { ok: boolean, errors: number, warnings: number, issues: Array<DoctorIssueDto>, };

/**
 * A system event as the GUI needs it: the kind names the sentence template, and the rest are the
 * values that go into it. No prose — the wording lives in the GUI's dictionary, in the reader's
 * language, and the target's own name comes from [`ActivityTargetDto::title`] beside this.
 */
export type EventDto = { kind: string, 
/**
 * `task.status_changed`: the status the task moved to.
 */
status?: string, 
/**
 * `task.assigned`: the facet the task went to. Absent means the assignee was taken away, which
 * is a different sentence rather than a missing value.
 */
toKind?: string, 
/**
 * `project.deleted`: how much went with the project. Both are always sent together, so the
 * sentence can say "none of either" without having to tell absent from zero.
 */
tasks?: number, decisions?: number, };

/**
 * What [`run_export`](crate::commands::run_export) returns: the directory it wrote to, how big it is, and how many attachments
 * were carried out.
 */
export type ExportReportDto = { path: string, 
/**
 * Total bytes of the directory that was written (`export.json` plus the attachment files). This
 * is the number the completion message shows in KB — count only the JSON and a bundle carrying
 * heavy attachments would claim to be far smaller than it is.
 */
bytes: number, 
/**
 * How many attachment files were written into `attachments/`.
 */
attachments: number, 
/**
 * How many attachments could not be carried out because their bytes are gone (we do not drop
 * them silently).
 */
missing: number, };

/**
 * One application a file could be opened with, as the file face draws a row of the chooser it has
 * to draw itself (`crate::open_with`).
 *
 * It exists only where the operating system has no chooser of its own — macOS. The path is what
 * names the application when one is picked, and it is checked against this same list on the way
 * back: what the face was offered is the whole of what it may ask for.
 */
export type FolderAppDto = { 
/**
 * What the machine calls it — the localised name, spelled the way a file manager spells it.
 */
name: string, 
/**
 * The application bundle itself, which is what opening with it names.
 */
path: string, 
/**
 * Whether this is the one the file would have opened with anyway, which is why it is first.
 */
usual: boolean, };

/**
 * A file that changed lately, as the file face's second row draws it (`crate::folder`).
 *
 * The path is the segments from the folder the face is rooted at, so the row can be opened by
 * handing the same list back — nothing here is a path a caller has to take apart.
 */
export type FolderChangedDto = { 
/**
 * The segments from the root, the file's own name last.
 */
path: Array<string>, 
/**
 * When it was last written (RFC3339 UTC).
 */
modified: string, };

/**
 * What the file face's second row is drawn from: the rows, and whether they are the whole story
 * (`crate::folder_watch`).
 *
 * `partial` is the one thing the rows cannot say for themselves. A watch is a set of watches, one
 * per folder, and the kernel's limit is per user — so some may be refused while the rest work.
 * Drawn as a whole watch, that reads as "nothing has changed" in the half nobody is watching.
 */
export type FolderChangesDto = { 
/**
 * The files written to most recently, newest first.
 */
changed: Array<FolderChangedDto>, 
/**
 * Whether some of the folder is unwatched — a walk that stopped at its cap, or a watch the
 * kernel refused.
 */
partial: boolean, };

/**
 * One name inside a folder, as the file face draws a row of its tree (`crate::folder`).
 *
 * It says what the row is and nothing about what is under it: a folder answers for its own
 * children only when it is opened, so a tree that is still folded costs one directory read.
 */
export type FolderEntryDto = { 
/**
 * The name on its own — one segment, never a path.
 */
name: string, 
/**
 * Whether opening it lists more names.
 */
isDir: boolean, };

/**
 * What a file has to show for itself, as far as a panel can show it (`crate::folder`).
 *
 * Exactly one of `text` and `image` is filled, and both are empty for a file that is neither —
 * what a reader is then told is that it cannot be read here, which is the honest answer for a
 * binary. Text is cut at a cap, because a panel is not a pager and a very long file would be paid
 * for in full to draw a screen of it.
 */
export type FolderFileDto = { 
/**
 * The text, where the head of the file holds no NUL byte.
 */
text?: string, 
/**
 * True when `text` stops short of the file's end.
 */
truncated: boolean, 
/**
 * The picture, where the bytes say they are one and there are few enough of them to carry.
 */
image?: FolderImageDto, };

/**
 * A picture out of a folder, carried whole so the webview can draw it without a URL of its own.
 *
 * The bytes come over the command seam rather than through [`crate::fileproto`], because that door
 * is fenced by a session's folder and this face is rooted at the project's (`AMB-T-3602`).
 */
export type FolderImageDto = { 
/**
 * The type the bytes themselves say they are — read off the first of them, never off the name.
 */
mime: string, 
/**
 * The whole picture, base64-encoded, for a `data:` URL.
 */
base64: string, };

/**
 * That folder's `.amenbo` was written by a build of another channel
 * ([`amenbo_core::binding::DirBinding::mismatched_store`]) — production against `amenbo-dev`, or a
 * throwaway `amenbo-dev-<task>`. The CLI refuses outright there (`pointer_other_store`); the GUI,
 * having no cwd to be refused in, says so on the row instead. Both names travel, because the
 * sentence needs the pair: whose the folder is, and who is looking at it. `running` is the same for
 * every row of a listing (it is this build's own name) and is repeated on each rather than read from
 * a second call — the row then holds everything its wording needs, the way [`SlugMismatchDto`] does.
 */
export type ForeignStoreDto = { 
/**
 * The store name written in the folder's `.amenbo`.
 */
recorded: string, 
/**
 * The store name of the build that is listing it.
 */
running: string, };

/**
 * What one frame of the talk window is called, and who called it that — which is what says whether
 * the next naming may replace it ([`amenbo_core::frames`]).
 */
export type FrameNameDto = { 
/**
 * The frame it is the name of. Names belong to frames, never to the session running in one.
 */
frame: string, name: string, by: "typed" | "session" | "person", };

/**
 * One bound repository the banner has something to say about — the raw material for its wording, never
 * the sentence, as with [`HookOfferDto`].
 *
 * Its two lists are two different things: [`HookNoticeDto::unwired`] is a standing state (the lint is not
 * running in these slots, and `hooks install` wires them — coexisting with another tool's hook where one
 * is there), while [`HookNoticeDto::restored`] is a transient event (a block of ours was found damaged or
 * stale this session and put back). A repository appears when either list is non-empty.
 */
export type HookNoticeDto = { 
/**
 * The project's name, so the banner can say which one it is about.
 */
projectName: string, 
/**
 * The git repository this notice is about, which is also what identifies it.
 */
dir: string, 
/**
 * What this build is called on the command line, for the same reason [`HookOfferDto::cmd`]
 * carries it: the dev channel answers `amenbo-dev` and the wording must not spell either in.
 */
cmd: string, 
/**
 * Slots with no block of ours (empty, or another tool's hook without Amenbo's block), which
 * `hooks install` wires.
 */
unwired: Array<string>, 
/**
 * Slots whose block of ours was found damaged or stale this session and restored — something had
 * changed or removed it (a tool regenerating its hook, a hand-edit). Empty in the ordinary case.
 */
restored: Array<string>, };

/**
 * The question waiting to be put to the user: may Amenbo wire its lint into your git hooks?
 *
 * **There is one of it, ever** — not one per repository. It carries only what the wording needs, which is
 * the name of this build, and nothing about where an answer would land. Which repositories are bound,
 * which slots are empty, which a stranger holds, whether the hooks directory is one the whole team shares
 * — all of that is `amenbo_core::hooks::install`'s to act on, and none of it is a fork in the user's
 * road: nobody wants an AMB-T-… in their commits *here* but not *there*, so a screen that laid the
 * machinery out — or listed the folders — would be asking them to solve Amenbo's problem. What is still
 * unwired afterwards is the setup banner's to report ([`HookNoticeDto`]), where it is a statement rather
 * than a question.
 */
export type HookOfferDto = { 
/**
 * What this build of Amenbo is called on the command line, which is what its hooks will actually
 * run and what its guidance tells the user to type. The dev channel answers `amenbo-dev`, so the
 * name travels rather than being spelled into the wording.
 */
cmd: string, };

/**
 * A reference to a task a decision spawned. A [`DecisionRefDto`] plus **status**, so the screen can
 * answer "is this decision's work finished yet?". Completed ones are muted on the screen side.
 */
export type LinkedTaskRefDto = { id: number, name: string, ref?: string, status: "todo" | "in_progress" | "done" | "blocked" | "rejected", };

/**
 * One app Amenbo can be reached from over MCP, as a screen draws its row (`AMB-D-672`,
 * `AMB-D-673`, `AMB-D-681`).
 */
export type McpAppDto = { 
/**
 * The catalog's own id for it (`claude-desktop`).
 */
app: string, 
/**
 * The product's name for itself, for the row.
 */
label: string, 
/**
 * Whether Amenbo writes this one a file to open, rather than handing over a request
 * (`AMB-D-672`). It is what decides which button the row draws.
 */
writesFile: boolean, 
/**
 * Whether this app already holds Amenbo's server (`AMB-D-673`).
 */
configured: boolean, 
/**
 * The folders those entries reach. Shown beside "set up", because set up for *which* folders is
 * the half a reader cannot work out for themselves — and it is what the row's ticks open on.
 */
folders: Array<string>, 
/**
 * The entries this app still holds under a name Amenbo used to write (`AMB-D-679`), each with
 * the request that clears it. They are drawn apart from the row's own state: an old entry is not
 * this app being set up, it is something to take away.
 */
stale: Array<McpStaleDto>, };

/**
 * One project a reader can let an app reach.
 */
export type McpProjectDto = { id: number, 
/**
 * Its name as its owner wrote it — what the tick is labelled with.
 */
name: string, 
/**
 * The folder a server would be pointed at. It is drawn beside the name because two projects can
 * read alike and their folders never do, and because it is what the entry will actually carry.
 */
folder: string, };

/**
 * The two texts a row hands over, for the projects ticked on it right now.
 *
 * They are fetched as the ticks move rather than when a button is pressed: the surface both shows a
 * text and copies it, and a button that had to go and ask first could hand over an empty clipboard
 * with no second chance to notice. Empty for the app Amenbo writes a file for — there is no request
 * to give anybody there, and the button beside it writes the file instead.
 */
export type McpRequestDto = { add: string, remove: string, };

/**
 * Everything the screen that connects an AI draws (`AMB-D-681`): the projects a server can be
 * pointed at, and one row per app.
 *
 * The two are asked for together because the screen reads them against each other — a row's ticks
 * are the projects whose folder that app already reaches, and neither half says that on its own.
 */
export type McpSetupDto = { 
/**
 * The projects that can be reached at all: the ones with a folder bound. A project with none
 * has nowhere to point a server, and a tick beside it would write an entry naming nothing.
 */
projects: Array<McpProjectDto>, 
/**
 * Every app Amenbo knows, in the catalog's order.
 */
apps: Array<McpAppDto>, };

/**
 * One entry left behind under a name Amenbo no longer writes, as a row offers to clear it.
 *
 * The request travels with it for the reason [`McpRequestDto`]'s do not have to: nothing the reader
 * picks changes it, so it is settled the moment the row is drawn.
 */
export type McpStaleDto = { 
/**
 * The name it is filed under — what tells two of these apart, and what the request names.
 */
name: string, 
/**
 * The folder its arguments bind it to, where it names one.
 */
folder: string | null, 
/**
 * The request that asks the reader's AI to delete it and nothing else.
 */
removeRequest: string, };

/**
 * [`amenbo_core::migrate::MigrationReport`] as the completion panel reads it.
 */
export type MigrationDoneDto = { 
/**
 * The version the store came from.
 */
from: number, 
/**
 * The version it is at now.
 */
to: number, 
/**
 * Where the pre-migration backup is kept — the only way back (there is no downgrade).
 */
backupPath: string | null, 
/**
 * The pre-migration backups from earlier migrations that this run's own backup superseded, and which
 * it therefore deleted. Shown, never silent.
 */
superseded: Array<string>, };

/**
 * [`amenbo_core::migrate::Pending`] as the screen reads it: the two versions, the steps between them, and
 * the disk the pre-migration backup needs. Bytes, not MiB — the rounding belongs on the side that has the
 * reader.
 */
export type MigrationPendingDto = { 
/**
 * The format version the store carries now.
 */
from: number, 
/**
 * The version the chain will carry it to.
 */
to: number, 
/**
 * How many steps stand between the two.
 */
steps: number, 
/**
 * Upper bound on the finished archive.
 */
archiveBytes: number, 
/**
 * Transient peak on top of it (the staged snapshot, deleted once appended).
 */
stagingBytes: number, 
/**
 * What must be free for the backup to complete.
 */
requiredBytes: number, 
/**
 * What is actually free where the backup lands.
 */
availableBytes: number, };

/**
 * The camelCase DTO of a version-chain run (core's
 * [`amenbo_core::store_engine::migrate::Run`]).
 */
export type MigrationRunDto = { 
/**
 * The format version the store carried before the run. `number` on the TS side (the default
 * `bigint` cannot be interpolated into a sentence).
 */
from: number, 
/**
 * The format version it carries now.
 */
to: number, 
/**
 * Names of the steps that were applied, in order.
 */
applied: Array<string>, };

/**
 * What the startup migration is doing, for the migration screen.
 */
export type MigrationStatusDto = { 
/**
 * `idle` (nothing to carry forward — no screen) / `running` / `done` / `failed`. A stable string the
 * front switches on; never shown as it is.
 */
stage: string, 
/**
 * What the run is about to do, once core has announced it (`running`, before the first byte is
 * written).
 */
pending: MigrationPendingDto | null, 
/**
 * The latest tick of the run — the pre-migration backup, then the chain's steps — so a window that
 * mounts mid-run has a bar to draw.
 */
progress: DataProgressDto | null, 
/**
 * What the run did (`done`).
 */
report: MigrationDoneDto | null, 
/**
 * Why the run failed (`failed`). The same structured error every store open now refuses with, so the
 * screen localises it exactly like any other (`errLabel`).
 */
error: { code: string; message_en: string; fields: Record<string, unknown> | null } | null, };

/**
 * Where one task sits (project only — classification lives on the dimension axes). The real data
 * behind the project row in the task detail view.
 */
export type PlacementDto = { project: ProjectRefDto, };

/**
 * A reference with no entity key behind it (a decision's `decided_by` — an opaque token that
 * cannot be looked up).
 */
export type PlainRefDto = { id: string, name: string, };

/**
 * **One operation the settings form may raise** (`AMB-D-664`) — a button, and whatever that press has to
 * ask for before it can run.
 *
 * `cmd` is not shown to anyone: it is the name the press hands back, and the only thing Amenbo will
 * raise a call by ([`plugin_settings_action`](crate::commands::plugin_settings_action)). What is drawn is the label, plain — no Markdown and no
 * link, like every other author string on this screen (`AMB-D-656`).
 */
export type PluginActionDto = { 
/**
 * The declared call this button raises, as the manifest wrote it — the form's handle on it, never a
 * line a caller composes (`AMB-D-522`).
 */
cmd: string, 
/**
 * The words on the button, in the author's language.
 */
label: string, 
/**
 * Those words in the reader's language, when their author wrote them (`AMB-D-620`). Beside the base
 * label, never over it — the form picks (`AMB-D-623`).
 */
labelI18n?: string, 
/**
 * What this press asks for and nothing keeps (`AMB-D-664`). Empty is the ordinary operation, which
 * runs on the values already saved.
 */
ask: Array<PluginAskDto>, 
/**
 * When this button is offered (`AMB-D-727`). Empty is an operation with no condition on it.
 */
when: Array<PluginWhenDto>, };

/**
 * What pressing one of a plugin's declared operations did (`AMB-D-664`) — the whole of what the form
 * draws afterwards.
 *
 * **The exit code is still the whole verdict** (`AMB-D-353`), and the author's one line on stderr is
 * still the sentence beside the button. What a run may now add to that is a set of parts to draw
 * (`AMB-D-727`) — a QR to hold a phone up to, an address with a copy button — which is what gets anybody
 * through a setup that a sentence cannot. Anything past those is on the execution log, where every run
 * of this plugin already is (`AMB-D-361`).
 */
export type PluginActionRanDto = { 
/**
 * Whether the run exited successfully. `false` changes nothing — a failed operation is a line on the
 * screen, not a state the form has to recover from.
 */
ok: boolean, 
/**
 * The author's own line, as written to stderr and drawn plain. Absent when the run said nothing.
 */
message?: string, 
/**
 * What the run asked to have drawn, in the order it wrote them (`AMB-D-727`). Empty covers both a
 * run that asked for nothing and one whose stdout is not an answer this build reads — an
 * operation's stdout was never consumed before this, so a plugin writing something else there is
 * drawn exactly as it always was.
 */
show: Array<PluginShowPartDto>, };

/**
 * **One value an operation asks for at the press** (`AMB-D-664`) — a box drawn only while the press is
 * being made, whose answer is handed to that one run and stored nowhere.
 */
export type PluginAskDto = { 
/**
 * The name the value travels under — what the press hands back beside it, and never something the
 * form stores.
 */
key: string, 
/**
 * The label beside the box, in the author's language.
 */
label: string, 
/**
 * That label in the reader's language, when their author wrote one (`AMB-D-620`).
 */
labelI18n?: string, 
/**
 * Whether the box hides what is typed into it — the author's declaration, as on a secret setting
 * (`AMB-D-356`). Here it decides only what the screen shows: there is no store to route it to.
 */
secret: boolean, };

/**
 * The plugin market view: every entry across the merged catalogs, plus which catalogs answered.
 */
export type PluginCatalogDto = { entries: Array<PluginEntryDto>, sources: Array<PluginCatalogSourceDto>, 
/**
 * How many entries the merge dropped (a manifest the door refused, or a name a later catalog
 * repeated). A count, not the rows: the list's job is to show what a catalog *is* shedding, and
 * the reasons belong to the CLI's `plugin catalog list` (`AMB-D-354`).
 */
dropped: number, };

/**
 * What registering a catalog would mean, worked out before anything is written (`AMB-D-389`) — the
 * material the consent screen puts in front of the user. Asking changes nothing on disk.
 */
export type PluginCatalogProbeDto = { 
/**
 * The URL as it would be registered (trimmed) — what the agreement is about.
 */
url: string, 
/**
 * What to call it when the user names nothing: the host serving it, or the name a record already
 * registered under this URL carries.
 */
suggestedName: string, 
/**
 * The fingerprint of the key this catalog publishes. `None` is a catalog that publishes none:
 * browsable, and nothing on it installs.
 */
fingerprint: string | null, 
/**
 * Whether this URL is already registered — a second registration changes nothing but the name,
 * unless it is bringing a key the record does not have yet.
 */
registered: boolean, 
/**
 * Whether going ahead would pin a key that is not pinned yet. This is the one case that adds a
 * trust root rather than a bookmark, so it is the one the screen must take consent for.
 */
pinsANewKey: boolean, };

/**
 * What a check was measured against (`AMB-D-359`) — the other half of its verdict, so a face can frame the
 * rows it is about to draw.
 *
 * The freshness boundary makes "nothing has changed" and "nothing had changed an hour ago" the same empty
 * list, and the two states that read no catalog at all are opposites — nothing to compare, or nothing
 * reachable to compare against — so `read` keeps five arms rather than folding any of them together.
 */
export type PluginCatalogReadDto = { 
/**
 * How the catalog behind the verdict was read. `fetched` — asked and answered, so the rows are the
 * index as it stands; `cached` — inside the freshness window, so **no request was made**; `offline` —
 * one was made and failed, so a copy of that age stood in; `notNeeded` — nothing is installed, so no
 * catalog was read; `unavailable` — one was wanted and neither fetched nor cached, so nothing below is
 * a verdict.
 */
read: "fetched" | "cached" | "offline" | "notNeeded" | "unavailable", 
/**
 * How old the copy that answered is, for the two arms a cache stood in on. Absent everywhere else —
 * a fetch has no age to report, and the arms that read no catalog have no copy at all.
 *
 * Seconds in a `u32`, which the face reads as a plain number: an age this does not fit is a hundred
 * years of cache, and saturating there says "as stale as it gets", which is the only reading anyone
 * wants from it.
 */
ageSeconds?: number, };

/**
 * One catalog that fed the merged list — the official one first, then each registered third-party
 * one in registration order.
 */
export type PluginCatalogSourceDto = { url: string, 
/**
 * What to call it: the name given at registration, or Amenbo's own for the official catalog.
 */
name: string, 
/**
 * The fingerprint of the key this catalog's plugins are trusted on (`AMB-D-389`). `None` is a
 * catalog that published none — browsable, and nothing on it installs.
 */
fingerprint: string | null, official: boolean, 
/**
 * Whether it answered at all — from the network or, failing that, its cache. `false` contributes
 * nothing to the list, and is what the front end tells the user about rather than failing the view.
 */
reachable: boolean, 
/**
 * How many entries it offered, before cross-catalog de-duplication.
 */
offered: number, };

/**
 * What the author's own check said about the values, for the screen that shows the form (`AMB-D-664`).
 *
 * It rides back with the gate because the check is what an enable raises: the switch is where the run
 * happens, and the form is where its sentences belong. A verdict may say yes and still have something to
 * say, which is why this is not a failure report.
 */
export type PluginCheckDto = { 
/**
 * Whether the check said the values are usable. `false` with the gate shut is the refusal.
 */
ok: boolean, 
/**
 * Whether the check answered at all. `false` is a run that said nothing this build can read — the
 * fail-closed silence (`AMB-D-354`), which carries no sentence of the author's and so gets Amenbo's.
 */
answered: boolean, 
/**
 * The one sentence about the settings as a whole, for the head of the form. Absent when the check
 * wrote none.
 */
message?: string, 
/**
 * One sentence per setting the check spoke about, keyed by the setting's own key — drawn beside the
 * box it names. Core has already dropped any key the manifest does not declare.
 */
fields: Record<string, string>, 
/**
 * What the check asked to have drawn, in the order it wrote them (`AMB-D-727`). A check runs before
 * anybody has filled anything in, which is where a way to the page that issues the token is worth
 * the most. Empty is a check that asked for nothing, which is every one written before this existed.
 */
show: Array<PluginShowPartDto>, };

/**
 * One setting a plugin's author declared, and what this machine currently holds for it
 * (`AMB-D-356`) — everything the generic form needs to draw a row and nothing Amenbo judges for
 * itself.
 *
 * The value is the one the project on screen holds, and nothing stands under it (`AMB-D-434`): absent
 * reads as absent, which is what lets the form draw "not provided" and clear a field.
 *
 * **A secret's value is never here.** The author's flag is what routes it to `plugin_secret`, and a
 * value read back into a webview would be a copy of it in a place `AMB-D-356` keeps it out of — so a
 * secret carries whether it is held, and that is all a form needs to mask it.
 */
export type PluginConfigFieldDto = { 
/**
 * The key the author declared — what a write names, and what a refusal quotes back.
 */
key: string, 
/**
 * The author's own label for the field, drawn as the form's caption.
 */
label: string, 
/**
 * Whether the author marked it secret. The form masks it and never reads it back.
 */
secret: boolean, 
/**
 * Whether the author marked it required. An enable is refused while one of these has no value,
 * so the form says which before the switch does.
 */
required: boolean, 
/**
 * The text value the project the request named holds, as stored — absent when unset, when no
 * project was named, and always for a secret.
 */
value?: string, 
/**
 * Whether that project holds a secret for this key. Always false for a text field, whose value
 * says it itself.
 */
secretSet: boolean, 
/**
 * Which of the three answers this project is giving (`AMB-D-415`), read by core so the form and the
 * CLI cannot each decide for themselves what the stored string means: `chosen` (a value is held),
 * `none` (a choice answered with none of its candidates), `unanswered` (nothing is held, and the
 * author's default is what a run receives).
 *
 * A form that could not tell the last two apart would draw the same empty boxes for "declined" and
 * "not been here yet", and offer no way back to the default.
 */
state: "chosen" | "none" | "unanswered", };

/**
 * One candidate a setting offers (`AMB-D-415`): the value stored when it is ticked, and the words the
 * author wants beside its checkbox. Two audiences, so two strings — the plugin reads `value`, the user
 * reads `label`.
 */
export type PluginConfigOptionDto = { value: string, label: string, 
/**
 * The candidate's label in the reader's language, when its author wrote one (`AMB-D-621`). Beside
 * the base label, never over it (`AMB-D-623`). The `value` has no counterpart here: it is what
 * travels to the plugin, so it is the same in every language.
 */
labelI18n?: string, 
/**
 * When this candidate is offered (`AMB-D-727`). Empty is a candidate with no condition on it, which
 * is every one written before the key existed.
 */
when: Array<PluginWhenDto>, };

/**
 * What the catalog's **detail document** says about one plugin — the half of its entry that is fetched
 * for the one plugin someone opened, never for the list (`AMB-D-385`).
 *
 * It answers what a reader wants before installing and the list deliberately does not carry: what it
 * will watch, what it will want to be told, and whether this build of Amenbo can speak to it at all. The install coordinates in the same document — the URL, the checksum,
 * the signature — are not here: they are the install path's, verified there over the bytes served
 * (`AMB-D-371`), and a face that displayed them would invite reading them as the assurance they are not.
 */
export type PluginDetailDto = { 
/**
 * The observation events it subscribes to (`AMB-D-383`), by name — what installing it means it will
 * be woken for.
 */
events: Array<string>, 
/**
 * The form it declares, in the author's order — the settings it will want filled in, and the parts
 * drawn between them (`AMB-D-727`).
 */
config: Array<PluginFormEntryDto>, 
/**
 * **What the plugin is, in its author's own words** (`AMB-D-638`) — the Markdown the detail draws
 * as its body. Absent is a plugin whose author wrote none, and the face falls back to the
 * repository's README there; where this is present the README is neither drawn nor fetched.
 */
about?: string, 
/**
 * The same text in the reader's language, when its author wrote one (`AMB-D-621`). Beside the base
 * text, never over it: choosing between the two is the front end's (`AMB-D-623`).
 */
aboutI18n?: string, 
/**
 * **What layer its author declared it lives at** (`AMB-D-601`) — a project's, or the device's. It is
 * read here rather than off the list because the declaration rides in the detail document, and this
 * is the face that draws one: a device-wide plugin reads every project on this machine, which is the
 * thing worth knowing *before* it is taken on.
 */
scope: "project" | "machine", 
/**
 * Whether this build of Amenbo can run it (`AMB-D-359`). Asked here so the answer arrives before an
 * install rather than at the enable that would refuse.
 */
compatible: boolean, 
/**
 * Why not, when `compatible` is false — core's own sentence, the same one the installed screen shows.
 */
incompatibleReason?: string, };

/**
 * The device's own row, for a plugin its author declared the machine's (`AMB-D-601`) — the same three
 * readings a crossing carries, with no project to key them by.
 *
 * It is a shape of its own rather than a [`PluginProjectRowDto`] with a hole in it: a device row is not a
 * crossing that lost its project, it is the one row a machine-wide plugin has, and a face handed a
 * project-shaped row would have gone looking for the project it names.
 */
export type PluginDeviceRowDto = { 
/**
 * Whether the plugin fires on this device — the one gate it has (`AMB-D-601`).
 */
enabled: boolean, 
/**
 * Whether the device holds a value for any setting the author declares.
 */
hasValue: boolean, 
/**
 * Whether a `required` setting is empty here — the reason an enable would be refused.
 */
requiredUnset: boolean, };

/**
 * One entry of the plugin market list. Only what the list draws: identity, the one-line
 * description, and the axes it is filtered on (`AMB-D-347`). Nothing an install needs — the
 * signature, the checksum and the asset map are the detail's, not the list's (`AMB-D-385`).
 */
export type PluginEntryDto = { 
/**
 * The plugin's name, which is its identity in the catalog.
 */
name: string, 
/**
 * What to call it on screen, when the catalog published one (`AMB-D-739`). It rides **beside**
 * `name` rather than replacing it, the same way `descI18n` rides beside `desc`: which of the two a
 * row draws is the front end's, and absent — a plugin whose author wrote none — is the ordinary
 * case, where the name is what a reader has always seen.
 */
title?: string, desc: string, 
/**
 * The same line in the reader's language, when the catalog published one for this plugin
 * (`AMB-D-622`). It rides **beside** the base line rather than replacing it: choosing between the
 * two is the front end's (`AMB-D-623`), and absent is the ordinary case — a plugin nobody
 * translated, a language nobody published, or a reader reading the base language itself.
 */
descI18n?: string, author: string, 
/**
 * `owner/name` — the GitHub coordinates a detail view reads stars and README from, lazily.
 */
repo: string, 
/**
 * The operating systems it supports, as the manifest spells them (`macos` / `windows` / `linux`).
 */
os: Array<string>, category: string, 
/**
 * The official badge: catalog-authoritative, never the manifest author's claim (`AMB-D-347`).
 */
official: boolean, 
/**
 * Whether the official catalog is what served this entry — reviewed onto the official index. The
 * other axis of the same trust picture as `official`, and not derivable from it: an official
 * plugin is always listed, a listed one is written by anybody who passed review, and an entry
 * from a third-party catalog is neither.
 */
listed: boolean, 
/**
 * The URL of the catalog that served it — the identity the source filter narrows on, since a name
 * is the user's and two catalogs may share one.
 */
source: string, 
/**
 * What that catalog is called. Carried on the entry rather than looked up in `sources`, because it
 * is what the row wears on the free layer (`AMB-D-389`): a registered catalog is a trust root with
 * a name, not an anonymous "other".
 */
sourceName: string, 
/**
 * Whether the official index recommends it — hand curation (`AMB-D-347`), for the "featured"
 * ordering and the badge beside the trust layer. A third axis again: what a plugin is for, rather
 * than who wrote it or who reviewed it. Core has already discounted a third-party catalog's claim
 * on its own entries, so this is answered, not raw.
 */
featured: boolean, 
/**
 * When the catalog first listed it (`YYYY-MM-DD…`), for the "new" ordering. Absent on a catalog
 * that does not record it.
 */
addedAt?: string, };

/**
 * **One entry on a plugin's settings form** (`AMB-D-727`) — a setting somebody fills in, or a part
 * Amenbo draws where it stands.
 *
 * The list is the author's declared order, because where a part sits is what it is for: the way to the
 * page that issues a token belongs above the box the token goes in, and two lists side by side cannot
 * say that.
 *
 * A third party's `qr` and `link` are gone before this is built — core drops them (`AMB-D-727`), so a
 * face draws whatever reaches it.
 */
export type PluginFormEntryDto = { "kind": "field", 
/**
 * The setting.
 */
field: PluginWantedSettingDto, } | { "kind": "part", 
/**
 * What is left of the author's condition on it (`AMB-D-727`) — the platform's half already
 * settled, so what remains reads another setting's answer and is re-read as the form changes,
 * exactly as a setting's own is. Empty is a part drawn unconditionally.
 */
when: Array<PluginWhenDto>, 
/**
 * What to draw.
 */
part: PluginShowPartDto, };

/**
 * Where a gate ended up, and what closing it threw away (`AMB-D-399`) — what [`plugin_set_enabled`](crate::commands::plugin_set_enabled)
 * answers with.
 *
 * The count is here because the discard is real and invisible: disabling a plugin drops whatever was
 * waiting on its queue, and those events are not caught up on when it comes back. The CLI has said so
 * since the drop existed; without this the switch on screen threw the same work away without a word.
 */
export type PluginGateMovedDto = { 
/**
 * Whether the plugin fires at that gate now.
 */
enabled: boolean, 
/**
 * How many queued events the disable dropped. Zero on an enable, and on a disable that found an
 * empty queue — the ordinary case, which a face is meant to pass over in silence.
 */
droppedQueued: number, 
/**
 * What the author's own check said, when an enable raised one (`AMB-D-664`). Absent on a disable —
 * nothing is checked on the way out — and on a plugin that declares no check.
 *
 * A verdict here with `enabled: false` is the refusal: the gate did not move, and the reason is the
 * author's sentences rather than one of Amenbo's.
 */
check?: PluginCheckDto, };

/**
 * One plugin this machine holds, as the market draws its state on top of the catalog entry of the same
 * name (`AMB-D-351`). Installed and enabled are two facts, not one: an installed plugin that fires
 * nothing is the ordinary state.
 */
export type PluginInstallDto = { 
/**
 * The plugin's name — the key the market joins this row onto a catalog entry by.
 */
name: string, 
/**
 * What to call it on screen (`AMB-D-739`), read off the manifest kept beside the binary rather than
 * the catalog — so an installed plugin has a name to draw with no catalog fetch and none reachable.
 * This row is the one place the name is all there is: the installed list draws no description under
 * it. Absent is a plugin whose author wrote none, and the name stands as it always did.
 */
title?: string, 
/**
 * Every "project × plugin" intersection this plugin has a row at (`AMB-D-447`) — the projects holding
 * its gate open, and the projects holding a value while it is off. Empty means nowhere, which is an
 * answer; a truth value read from one project is not, because it hides the projects it is still
 * firing in (`AMB-D-412`).
 */
projects: Array<PluginProjectRowDto>, 
/**
 * **The device's row**, and only for a plugin whose author declared it the machine's (`AMB-D-601`).
 * `None` is the ordinary plugin, whose rows are the projects' — so a face reads which of the two
 * lists to draw off the declaration and never off an empty one, which every freshly installed plugin
 * has. Without it a machine-wide plugin's gate has nowhere on screen to be read or moved: it crosses
 * no project, so `projects` is rightly empty for it, and the row it does have was not in this answer.
 */
device?: PluginDeviceRowDto, 
/**
 * **What layer its author declared it lives at** (`AMB-D-601`) — read off the manifest that was
 * installed, so it says what *this* build of the plugin declares rather than what the catalog now
 * carries. It is not a switch and there is nothing to set: the declaration is what makes
 * `plugin enable` mean one thing, and the face says so in words beside the gate it is about to open.
 */
scope: "project" | "machine", 
/**
 * Whether this build can speak to it at all (`AMB-D-359`). An open gate on an incompatible plugin
 * fires nothing, and Amenbo updates underneath an install, so this is not derivable from a gate.
 */
compatible: boolean, 
/**
 * Why not, when `compatible` is false — the mismatch named, rather than left to the log.
 */
incompatibleReason?: string, 
/**
 * The form the author declared, in that order — its settings, and the parts drawn between them
 * (`AMB-D-727`). Empty for a plugin that declares nothing, which is the form's own answer to whether
 * there is anything to configure. What is held for a key is one project's (`AMB-D-434`) and comes
 * from [`plugin_config_read`](crate::commands::plugin_config_read).
 */
config: Array<PluginFormEntryDto>, 
/**
 * The operations the author declared, in that order (`AMB-D-664`) — the buttons the settings form
 * draws beside those fields. Empty is a plugin whose form is fields and a save, as every form was.
 */
actions: Array<PluginActionDto>, };

/**
 * One "project × plugin" intersection, as both plugin faces draw a row for it (`AMB-D-447`) — the state
 * of that one crossing, read with the install rather than one project at a time.
 */
export type PluginProjectRowDto = { 
/**
 * The project this row is for.
 */
project: number, 
/**
 * Whether the plugin fires in it (`AMB-D-434`).
 */
enabled: boolean, 
/**
 * Whether it holds a value for any setting the author declares. Off with values is an ordinary state,
 * so this is a fact of its own and not a reading of the gate.
 */
hasValue: boolean, 
/**
 * Whether a `required` setting is empty here — the reason an enable at this crossing would be
 * refused (`AMB-D-351`), said before the switch is pressed rather than after.
 */
requiredUnset: boolean, };

/**
 * What an uninstall actually found and removed (`AMB-D-357`) — the receipt the face reports from.
 *
 * Every piece is reported separately because the point of the receipt is that a plugin is more than its
 * binary: the settings and the secrets are the part a user does not picture going, and saying so
 * afterwards is what makes "a re-install starts clean" believable.
 */
export type PluginRemovedDto = { 
/**
 * The plugin was enabled somewhere, and its gates have been closed on the way out.
 */
wasEnabled: boolean, 
/**
 * Secrets existed and have been purged (`AMB-D-357`'s non-negotiable).
 */
secrets: boolean, 
/**
 * How many setting rows were deleted, across every project.
 */
projectValues: number, 
/**
 * How many per-project gate answers were deleted, across every project.
 */
projectGates: number, 
/**
 * The plugin's home under `plugins/` existed and has been removed.
 */
directory: boolean, 
/**
 * The plugin had runs in the execution log and they have been purged (`AMB-D-387`).
 */
runsLog: boolean, 
/**
 * Whether anything at all was found. `false` is not a failure: the name held nothing on this machine.
 */
anything: boolean, };

/**
 * What GitHub says about one plugin's repository — the figures the catalog deliberately does not
 * carry (`AMB-D-347`). Every one is optional on its own: the requests behind them fail
 * independently, and a repository with no release has no download count to report.
 */
export type PluginRepoFactsDto = { 
/**
 * `number` on the TS side (the default `bigint` has no `toLocaleString` grouping to draw it with,
 * and a star count is nowhere near the range that motivates one).
 */
stars?: number, 
/**
 * The current release's downloads, summed over its assets. Whatever else pulls an asset (CI,
 * mirrors) is in there too, so it is a sense of scale rather than a user count (`AMB-D-347`).
 */
downloads?: number, 
/**
 * The README as Markdown, for the front end's renderer (which allows no raw HTML).
 */
readme?: string, 
/**
 * GitHub refused because too many requests came from this address. A different thing to tell the
 * user than a failure: the answer is to wait, not to check the network.
 */
rateLimited: boolean, };

/**
 * One thing a plugin's own run asked to have drawn on the settings form (`AMB-D-727`) — the vocabulary
 * a check's verdict and an operation's answer both come back in.
 *
 * **The author supplies strings; Amenbo draws.** There is no markup here and no image: a `qr` carries
 * the text to encode and a `link` a destination and the words on the button, so what appears on screen
 * is the form's own, in the form's own paint. That is what keeps a plugin a child process
 * (`AMB-D-346`) and what keeps a reader able to tell Amenbo's words from a stranger's.
 *
 * `qr` and `link` reach a face only for an official plugin (`AMB-D-727`); core drops a third party's
 * before this is built, so nothing on this side has to know the rule.
 */
export type PluginShowPartDto = { "kind": "text", 
/**
 * The author's words.
 */
text: string, } | { "kind": "heading", 
/**
 * The author's words.
 */
text: string, } | { "kind": "note", 
/**
 * The author's words.
 */
text: string, } | { "kind": "list", 
/**
 * The lines.
 */
items: Array<string>, } | { "kind": "copy", 
/**
 * What the button copies, and what is drawn beside it.
 */
text: string, } | { "kind": "qr", 
/**
 * What the code encodes. The drawing is the screen's.
 */
text: string, } | { "kind": "link", 
/**
 * Where it goes — `http` or `https`, which core has already held it to.
 */
url: string, 
/**
 * The words on the button.
 */
label: string, };

/**
 * One installed plugin the catalog holds a different build of (`AMB-D-359`) — an offer the face can act
 * on, not a diff of two manifests.
 */
export type PluginUpdateDto = { 
/**
 * The plugin's name — how the face names it and how an apply asks for it.
 */
name: string, 
/**
 * What the **offered** build calls itself on screen (`AMB-D-739`), when it carries one. It comes off
 * the same documents the offer was read from, like the line below it, so the row names the build
 * being offered rather than the one installed.
 */
title?: string, 
/**
 * What the **new** build says it is, for a line the user can recognise it by.
 */
desc: string, 
/**
 * That line in the reader's language, when the offered build carries one (`AMB-D-622`) — beside the
 * base line, for the face to pick from (`AMB-D-623`). It comes off the same documents the offer was
 * read from, so it describes the build being offered and not the one installed.
 */
descI18n?: string, 
/**
 * The offered entry's identity — the digest of the detail document it was published as, which is the
 * same thing detection compared (`AMB-D-438`). A face keys a dismissal by it, so a catalog that moves
 * the entry again mints a new one and the offer returns. It has to be this and not the asset's digest:
 * an update that changes no binary is a real update, and keying on the executable would let one
 * dismissal bury every later manifest-only change behind the same id.
 */
availableDetailSum?: string, 
/**
 * Why this one needs a decision before it can be applied, or absent when it can just be applied
 * (`AMB-D-359`: send the user to a screen only when judgment is required). `incompatible` — the
 * offered build cannot run on this Amenbo; `settings` — it declares `required` settings this machine
 * has no value for, and the plugin is enabled.
 */
hold?: "incompatible" | "settings", 
/**
 * The settings behind a `settings` hold, named so the face can say which to fill in.
 */
missing: Array<string>, };

/**
 * How one plugin fared in [`plugin_update_apply_all`](crate::commands::plugin_update_apply_all) — a failure is a row, not the end of the run.
 */
export type PluginUpdateOutcomeDto = { 
/**
 * The plugin this row is about.
 */
name: string, 
/**
 * Whether its build was replaced.
 */
applied: boolean, 
/**
 * Why not, when it was not — core's own sentence, which is the one that knows the reason.
 */
error?: string, };

/**
 * How far a check goes for its catalog (`AMB-D-462`) — the wire form of
 * [`amenbo_core::plugin_update::Reach`].
 *
 * It crosses the boundary because only the caller knows which trigger it is. The face re-asks from several
 * (a focus return, a plugin screen opening, a button somebody pressed) and they do not want the same read,
 * so a command that picked one for everybody would be wrong for the rest.
 */
export type PluginUpdateReachDto = "incidental" | "now";

/**
 * A check's whole answer: what has moved, and what that was measured against.
 */
export type PluginUpdatesDto = { 
/**
 * Every installed plugin the catalog holds a different build of.
 */
updates: Array<PluginUpdateDto>, 
/**
 * How current that list is — see [`PluginCatalogReadDto`].
 */
catalog: PluginCatalogReadDto, };

/**
 * One setting a plugin will ask for, as its author declared it — and nothing a store holds for it.
 *
 * This is what the market shows **before** anything is installed (`AMB-D-385`), and it is also what an
 * installed row carries: a value belongs to one project (`AMB-D-434`), and neither of those faces is
 * standing in one. What is held is read for a named project, through [`plugin_config_read`](crate::commands::plugin_config_read).
 */
export type PluginWantedSettingDto = { 
/**
 * The key the author declared, which is what a later `plugin config set` names.
 */
key: string, 
/**
 * The author's label for it, which is what the form will caption.
 */
label: string, 
/**
 * That caption in the reader's language, when its author wrote one (`AMB-D-621`). Beside the base
 * label rather than over it, like every other translated field here (`AMB-D-623`).
 */
labelI18n?: string, 
/**
 * The paragraph the author wrote under this field (`AMB-D-656`), and it in the reader's language —
 * the same two halves, picked the same way. Absent means the label is the whole of it.
 *
 * **Plain text at every step.** It is drawn as written, with no Markdown and no link: the form is
 * where a credential is typed, and a destination its author chose does not belong on that screen.
 */
help?: string, helpI18n?: string, 
/**
 * The example the author wrote for the empty input, and it in the reader's language (`AMB-D-656`).
 * Shown inside the box and never stored — it is not a [`default_value`](Self::default_value), which
 * is a value a run really receives (`AMB-D-474`).
 */
placeholder?: string, placeholderI18n?: string, 
/**
 * Whether the plugin writes this value rather than the user (`AMB-D-656`). The form draws the value
 * with no input and no clear button beside it: what is there was generated by the plugin's own
 * setup, and a button that takes it back is a way to break the plugin, not a way to correct it.
 */
readonly: boolean, 
/**
 * Whether it is a secret — worth knowing before installing, since it means a credential will have
 * to be handed over for the plugin to do anything.
 */
secret: boolean, 
/**
 * Whether an enable is refused until it is filled in (`AMB-D-356`).
 */
required: boolean, 
/**
 * What kind of answer the field takes (`AMB-D-415`) — a line the user types, or any number of the
 * candidates below. It rides with the declaration rather than with the held value because it is the
 * same wherever you stand: it says what to *draw*, and a form is drawn before a project is picked.
 */
fieldType: "text" | "multi", 
/**
 * The candidates a `multi` field offers, in the author's order. Empty for a text field, which is the
 * form's own answer to whether there is a choice to draw.
 */
options: Array<PluginConfigOptionDto>, 
/**
 * The value in force while nobody has answered (`AMB-D-415`) — what a run receives, and what the
 * form ticks and captions as the default. Absent means an unanswered field is simply unanswered.
 */
defaultValue?: string, 
/**
 * When this setting is drawn (`AMB-D-727`). Empty is a setting with no condition on it, which is
 * every one written before the key existed — and also one whose only condition was the platform,
 * already settled and held.
 */
when: Array<PluginWhenDto>, };

/**
 * **One condition still to be judged, on the answers the form is holding** (`AMB-D-727`).
 *
 * The platform's half of a `when` is already settled by the time this arrives: what this build's OS hides
 * is not in the list at all ([`amenbo_core::plugin_when::after_platform`]), and no face here ever learns
 * an OS name. What is left reads another setting, and it is left to the form because the form is where
 * the answers are while it is open — someone ticking Cloudflare expects its fields the same moment, and
 * the store has not been told yet.
 *
 * Read as an `and`: everything listed has to hold. A setting answers with `has` when `has` is among its
 * values, which for a `multi` setting is one of the comma-joined answers (`AMB-D-415`) and for a text one
 * is the whole of it.
 */
export type PluginWhenDto = { 
/**
 * The key of the setting whose answer this reads.
 */
field: string, 
/**
 * The value looked for among that setting's answers.
 */
has: string, };

/**
 * What [`repair_pointers`](crate::commands::repair_pointers) returns: how many folders were fixed, and how many were left waiting on
 * a human's judgement.
 */
export type PointerRepairDto = { 
/**
 * Folders whose pointer was rewritten, or written back, in the current format.
 */
repaired: Array<string>, 
/**
 * Folders left untouched because their owner could not be determined uniquely (the human
 * rebinds them through "open folder").
 */
unresolved: Array<string>, };

/**
 * Premises that moved under a task **after it was reserved** (`AMB-D-366`, `AMB-D-373`) — the holder-side
 * surface. Each list is a way readiness was withdrawn since the task went `in_progress`: a blocker that
 * has not ended pinned on, a decision linked but not yet settled, or a decision that was already linked
 * and has stopped being settled. Carried on the card only when there is a change to show (see
 * [`TaskCardDto::premise_change`]), so the screen draws the note exactly when it matters.
 */
export type PremiseChangeDto = { 
/**
 * Not-done blockers whose dependency edge was added after the reservation, in edge order.
 */
addedBlockers: Array<TaskRefDto>, 
/**
 * Unsettled decisions linked after the reservation, in link order.
 */
addedDecisions: Array<DecisionRefDto>, 
/**
 * Decisions already linked that stopped being settled after the reservation, in link order.
 */
reopenedDecisions: Array<DecisionRefDto>, };

/**
 * A reference to a premise decision (the far end of builds_on). It is more than a
 * [`DecisionRefDto`] because it carries **whether the premise is still alive** — surfacing on
 * screen the decisions that stand on a rotten premise (the whole reason this type exists).
 * `superseded_by` is the conversational ref (`AMB-D-<n>`) of the decision that overturned the premise,
 * and is omitted when the premise is current (currency is not stored anywhere else — whether this
 * field is empty *is* the answer).
 */
export type PremiseRefDto = { id: number, 
/**
 * `null` when the premise target dangles (a `builds_on` onto a decision no longer live); the screen
 * composes the placeholder in `config.language`.
 */
name: string | null, ref?: string, 
/**
 * Ref (`D-<n>`) of the decision that overturned the premise. Absent means the premise is current.
 */
supersededBy?: string, };

export type ProjectDto = { id: number, name: string, color: string, view: "list" | "board" | "calendar" | "timeline", 
/**
 * Open task count (todo/in_progress/blocked — anything but done, live only). The sidebar's
 * count badge.
 */
openCount: number, 
/**
 * Proposed (under-discussion) decision count — decisions still awaiting a ruling. Feeds the
 * sidebar row and the header decision button's under-discussion badge.
 */
proposedDecisionCount: number, 
/**
 * Unified dimensions (classification axes). Empty means none are in use. Task classification
 * happens on these axes and nowhere else.
 */
dimensions: Array<DimensionDto>, };

/**
 * A reference to a project (id + display name). The id is an integer key.
 */
export type ProjectRefDto = { id: number, name: string, };

/**
 * The editable fields of one project, so the project settings screen can prefill its form.
 * The snapshot's `ProjectDto` does not carry notes/archived (every project rides in it — keep it
 * light), so we fetch them with `project_get` only when the settings screen opens. `archived` is
 * included (unarchiving is driven from this screen too).
 */
export type ProjectSettingsDto = { id: number, name: string, notes: string, color: string, view: "list" | "board" | "calendar" | "timeline", archived: boolean, };

/**
 * One chunk of a terminal's output, on its way to the pane drawing it (the payload of the talk
 * window's `pty://output` event).
 *
 * The bytes travel base64-encoded because they are not text: an escape sequence is split wherever
 * the read ended, and a multi-byte character with it, and only the emulator that reassembles them
 * may decode. Anything that turned them into a string here would corrupt exactly the chunks that
 * crossed a boundary.
 */
export type PtyChunkDto = { 
/**
 * The session whose terminal this came out of.
 */
session: string, 
/**
 * The chunk, base64-encoded.
 */
base64: string, };

/**
 * A terminal this process has open, as a pane putting itself up is told about it.
 *
 * It answers both of the pane's ways in: the terminal it just started, and the one it found already
 * running and adopted (`crate::pty::pty_sessions`). `started_at` is here because a pane cannot work
 * it out — a session that changed windows started when it started, and the moment the pane went up
 * says nothing about it.
 */
export type PtySessionDto = { 
/**
 * The id the terminal was opened under.
 */
session: string, 
/**
 * When the terminal was started (RFC3339 UTC).
 */
startedAt: string, 
/**
 * The folder the terminal is running in, as the filesystem spells it — `None` for one opened
 * without any.
 *
 * It is here for the pane that **adopts** this session: where a terminal runs was settled when it
 * started, and a frame that took one over rather than starting it has no other way to learn it. A
 * frame that does not know would have to ask the person for the folder again the next time it has
 * a terminal to start, which is the one flow the face has asked for twice.
 */
folder: string | null, };

/**
 * What a reference resolves to (`kind` — task or decision — and the entity's id). The GUI branches
 * on it to decide which detail pane a link opens.
 *
 * It is the answer to `resolve_ref` and the payload of the board's `ref-activated` event, which are
 * the two ways a ref becomes a destination: one clicked in a body, and one clicked in a pane of the
 * talk window (`crate::windows::show_ref`). The same shape for both on purpose — a ref that came
 * from the other window is not a second kind of destination, and giving it one would be an invitation
 * for the two to drift over what a click opens.
 */
export type RefTargetDto = { kind: "task" | "decision", 
/**
 * The entity's primary key (an integer for both tasks and decisions). `kind` says which table
 * it points into.
 */
id: number, };

/**
 * What [`run_restore`](crate::commands::run_restore) returns: the camelCase DTO of core's
 * [`amenbo_core::archive::RestoreReport`].
 */
export type RestoreReportDto = { 
/**
 * Where the old source of truth was set aside when it was replaced. None when nothing was
 * replaced (a fresh creation).
 */
previousSavedTo: string | null, 
/**
 * How many attachment blobs were written (blobs the destination already had, by hash, are not
 * counted).
 */
blobs: number, 
/**
 * How many older rollback points this restore's set-aside copy overtook and deleted. It is a
 * report so that nothing is deleted silently, so the screen shows it only when it is non-zero.
 */
superseded: number, 
/**
 * What the version chain did to the staged store. **Some only when it actually ran**, so a null
 * check is all the front end needs to say "the archive you restored is not in the shape it was
 * taken in".
 */
migration: MigrationRunDto | null, };

/**
 * What `resync_managed_blocks` returns. `scanned` is how many folders that actually exist were
 * walked; `updated` lists the `(dir, file)` pairs rewritten to the current version — only the ones
 * whose content really changed.
 */
export type ResyncReportDto = { scanned: number, updated: Array<ResyncedDto>, };

export type ResyncedDto = { dir: string, file: string, };

/**
 * Which face of a record the words landed on — the wire form of
 * [`amenbo_core::query::HitFace`]. Crossing as a name rather than a rank keeps the face something the
 * screen can label and icon; the rank is the engine's business.
 */
export type SearchFaceDto = "title" | "body" | "comment" | "label" | "attachment";

/**
 * One place the words are written: the face, the record that face belongs to, and the excerpt that
 * points at it. The wire form of [`amenbo_core::query::SearchHit`].
 */
export type SearchHitDto = { face: SearchFaceDto, 
/**
 * Which side the record is on — `task` or `decision`. The face alone does not say: a title is either.
 */
kind: string, 
/**
 * The record's ref (`AMB-T-<n>` / `AMB-D-<n>`) — what the row opens, and where the number in it
 * comes from.
 */
ref: string, title: string, 
/**
 * The comment the words are in (`AMB-TC-<n>` / `AMB-DC-<n>`), when the hit is not on the record's
 * own faces.
 */
comment?: string, 
/**
 * The hit's own instant, RFC3339 — a comment's posting time, or when the text it sits in was last
 * written.
 */
at: string, snippet: string, 
/**
 * Where in `snippet` the words landed, for the row to highlight. Sorted and never overlapping, and
 * counted in the excerpt's **characters** — `Array.from(snippet)` splits it in that unit, `snippet[i]`
 * does not.
 *
 * The core says this so that the screen does not have to match anything itself: the folding a match
 * takes (NFKC, case, kana) lives with the index, and a second one on this side would be a second
 * answer to what a term matches (`AMB-D-566`).
 */
matches: Array<SearchMatchDto>, 
/**
 * Where the record this row points at stands — what the row shows past the ref and the title, so the
 * reader can tell a task still to be done from one that is over without opening it. Absent only when
 * the record stopped being readable between the page and the read that fills this in.
 */
standing?: SearchStandingDto, };

/**
 * One placement, in the words a person gave it.
 */
export type SearchLabelDto = { axis: string, value: string, };

/**
 * One run of `snippet` a term landed on — half-open, in characters. The wire form of
 * [`amenbo_core::query::MatchRange`].
 */
export type SearchMatchDto = { start: number, end: number, };

/**
 * One page of hits, and how many there are in all.
 */
export type SearchResultDto = { hits: Array<SearchHitDto>, 
/**
 * How many there are in all — what tells the screen its page left something behind.
 */
totalMatched: number, };

/**
 * A record's state, and — for a task — its priority and what it is filed under. The wire form of
 * [`amenbo_core::query::HitStanding`]; `kind` on the row says which vocabulary `status` is drawn from.
 */
export type SearchStandingDto = { 
/**
 * `todo` / `in_progress` / `done` / `blocked` / `rejected` for a task, `proposed` / `accepted` /
 * `rejected` for a decision.
 */
status: string, 
/**
 * Tasks only, and only where one was set.
 */
priority?: string, 
/**
 * Tasks only, in axis order — empty for a task placed on no axis.
 */
labels: Array<SearchLabelDto>, };

/**
 * One thing an AI said about the session it is running in, on its way to the pane drawing it.
 *
 * It is the surface layer's record ([`amenbo_core::session::Said`]) in the shape the webview reads.
 * The verbs each carry their own body, so the fields below are one verb's or another's: `text` is
 * every verb but `point`, and `target` with `why` is `point` alone.
 */
export type SessionSaidDto = { 
/**
 * The pane it was said in — the same id the terminal was opened under.
 */
session: string, verb: "name" | "note" | "waiting" | "finished" | "point", 
/**
 * When it was said (RFC3339 UTC).
 */
at: string, 
/**
 * The folder the agent was in when it said it. It starts as the one the terminal was opened in
 * and moves with every `cd`, so it is the agent's own rather than the pane's.
 */
cwd?: string, 
/**
 * The line said. Absent on `point`.
 */
text?: string, 
/**
 * What `point` pointed at. Absent on every other verb.
 */
target?: string, 
/**
 * Why it is worth opening. Absent on every other verb.
 */
why?: string, };

/**
 * What the ledger says the session in one pane has been doing — the reservations it is on, and how
 * many it has ended ([`amenbo_core::session_work`]).
 *
 * The tasks come back as ids rather than rows: the pane draws one of them at most, and the same
 * [`crate::commands::tasks_by_ids`] every other screen hydrates with can say the rest. What is being
 * answered here is *whose* they are, which nothing but the ledger knows.
 */
export type SessionWorkDto = { 
/**
 * Reserved and not ended, newest reservation first. One it has stopped on (`blocked`) is still
 * among them — the reservation stands.
 */
holding: Array<number>, 
/**
 * How many it has ended, carried out or decided against. A count, because that is the whole of
 * what the label says about them.
 */
finished: number, };

/**
 * The slug in `.amenbo` disagrees with what the store actually holds
 * ([`amenbo_core::binding::SlugMismatch`]). The CLI prints an English warning in its location
 * header; the GUI hands over the raw material only and lets i18n compose the wording (same verdict,
 * said differently). **Resolution is not blocked** (the id is authoritative) — we report it and
 * nudge a relink (`project_bind_folder`), nothing more.
 */
export type SlugMismatchDto = { 
/**
 * Primary key of the project the pointer names (whatever this number leads to, it is not the
 * project whose slug was recorded).
 * `number` on the TS side (the default `bigint` cannot be interpolated into the warning text).
 */
projectId: number, 
/**
 * The slug that was written in `.amenbo`.
 */
recorded: string, 
/**
 * The slug of the project `project_id` actually points at (it may not have one).
 */
actual: string | null, };

export type Snapshot = { 
/**
 * The user's language (config.json, global). Decides how the GUI localizes its UI labels. Null
 * when unset.
 */
language: string | null, 
/**
 * How dates are written (config.json, global) — a BCP-47 tag. Null means the one that goes
 * with `language`, which is what most people want; a value is the reader whose two answers
 * differ. Passed through as written: whether a tag is usable is the formatter's judgement, and
 * the front end falls back to the language's rather than failing to draw a date.
 */
dateLocale: string | null, 
/**
 * This person's roster — the two facets that come from config (human / ai). It is the one
 * supply line for every roster in the GUI: the assignee picker (unassigned / human name / AI
 * name), the display name and avatar in settings, and display-name resolution. `kind` is the
 * facet (`human`/`ai`); `name` is the effective display name from `config.human_name` /
 * `ai_name`.
 */
roster: Array<ActorDto>, projects: Array<ProjectDto>, activity: Array<ActivityItemDto>, 
/**
 * Findings of the read-only integrity check run at startup. If anything is wrong, the GUI
 * raises a warning banner (it never repairs anything by itself). A store with
 * `config.startup_integrity_check` off adds nothing here.
 */
startupHealth: StartupHealthDto, 
/**
 * Whether an update exists. If the published `latest.json` names a version newer than the one
 * running, `updateAvailable=true` — the material for the GUI's "an update is available (open
 * the installer)" banner.
 */
versionStatus: VersionStatusDto, 
/**
 * Level of perf instrumentation (the explicit value of `config.perf_log` — `off`,
 * `budget-only` or `verbose`). Null when unset, and the front end falls back to the dev-build
 * default of on (budget-only).
 */
perfLog: string | null, 
/**
 * Update checking on or off (`config.update_check`, default true). Exposed so the settings
 * screen's toggle can reflect the current value. When off, upstream latest.json is never
 * queried, so `update_available` can never be raised.
 */
updateCheck: boolean, 
/**
 * Start at login on or off (`config.autostart`, default false). Exposed so the settings screen's
 * switch can reflect the current value. It carries what the user asked for, not a reading of the
 * OS — the registration itself lives outside the app, and only a shipped build ever draws the
 * switch (a development build registers nothing, `AMB-D-547`).
 */
autostart: boolean, 
/**
 * What this device answered about the hourly tick (`config.tick_consent`) — `"yes"`, `"no"`, or
 * null for a device nobody has asked yet (`AMB-D-707`). Exposed so the settings screen's switch
 * can show the answer on record, the way `autostart` above is.
 *
 * Three states and a two-way switch, because the third is not a setting: never having answered is
 * the *absence* of one, and what it means on the machine — no timer registered — is what "off"
 * already says. The difference the null carries is whether the band may still put the question
 * (`AMB-D-718`), which core decides and this screen never asks about.
 */
tickConsent: string | null, 
/**
 * Whether taking the tick's registration away leaves a row behind in the OS's own list
 * ([`amenbo_core::tick::removal_leaves_a_row`] — macOS, and only macOS). A fact about the build,
 * so it rides in the snapshot rather than being asked for: what the settings switch needs it for
 * is the sentence to say the moment it is switched off, and left unsaid the row that stays reads
 * as a removal that failed.
 */
tickRemovalLeavesARow: boolean, 
/**
 * The view a project created without one of its own opens in (`config.default_view`, default
 * board). Exposed so the settings screen can show and change it. It is only the answer nobody
 * gave: a project already carries its own `view`, and this never repaints one.
 */
defaultView: "list" | "board" | "calendar" | "timeline", };

/**
 * One bound folder whose managed block is out of date. `version` is the version of that folder's
 * block; `current` is this binary's version ([`amenbo_core::agents::MANAGED_BLOCK_VERSION`]).
 */
export type StaleBlockDto = { dir: string, file: string, version: number, current: number, };

/**
 * The startup integrity check, shaped for the GUI: it feeds a read-only warning banner. Empty means
 * no warning (the counterpart of the CLI's stderr warning).
 */
export type StartupHealthDto = { 
/**
 * The problems doctor found (orphaned or dangling references, and so on). No prose sentence
 * rides along — the GUI composes one from the kind and params in `config.language`
 * (`src/core/i18n/`), so we hand these over as the same [`DoctorIssueDto`] the doctor screen
 * uses.
 */
issues: Array<DoctorIssueDto>, };

/**
 * For the "location" line under Settings > Data. Returns the real, OS-independent path (the
 * app-data root).
 */
export type StoreLocationsDto = { 
/**
 * Absolute path of the app-data root (the parent directory of the single `store.sqlite`).
 */
root: string, };

/**
 * One frame of a kept arrangement: where it sat, and what it was working on.
 */
export type TalkFrameDto = { 
/**
 * The id its name is kept against (`FrameNameDto`).
 */
id: string, 
/**
 * The project this pane is one of. Absent in an arrangement written before panes belonged to a
 * project, which the window answers for (`app/src/talk/layout.ts`).
 */
project?: number, 
/**
 * The folder its terminal was working in, where it had one.
 */
folder?: string, };

/**
 * The talk window's arrangement, as this device left it (`amenbo_core::frames::SavedLayout`).
 *
 * The shape only: how many panes to a page, the frames in slot order, and the folder each was
 * working in. **What was running is not here** — a session died with the last run, and a pane drawn
 * as though it were still there would be the window saying something untrue (`AMB-T-3607`).
 */
export type TalkLayoutDto = { 
/**
 * How many panes to a page.
 */
count: number, 
/**
 * The next frame id to hand out — ids are never reused, so a name stays on its own frame.
 */
nextId: number, 
/**
 * The project whose panes the face was showing. It is what the window with no rail opens as
 * (`app/src/talk.ts`); absent where nothing has told the face of a project yet.
 */
project?: number, 
/**
 * The frames, in slot order.
 */
frames: Array<TalkFrameDto>, };

export type TaskCardDto = { id: number, title: string, 
/**
 * The name it goes by on screen, `#<n>` (the display form of `id`).
 */
ref: string, notes: string, projectId: number | null, status: "todo" | "in_progress" | "done" | "blocked" | "rejected", assignee: ActorDto | null, priority: "high" | "medium" | "low" | null, due: string | null, 
/**
 * The declared start day (`YYYY-MM-DD`), whether or not it has come. `not_started_until` below is
 * the premise this field can raise; this is the field itself, which is what the pane editing it has
 * to show — a day that has already come is still a value the person put there and may want back.
 */
startOn: string | null, 
/**
 * Completion timestamp (RFC3339 UTC). Used to sort the Done column newest-first, among other
 * things. None while the task is still open.
 */
completedAt: string | null, comments: number, 
/**
 * Can it be reserved? — no open blockers, every decision it rests on settled, the declared start
 * day arrived, and the creation finished: the reasons
 * [`amenbo_core::view::ReserveBlocker`] enumerates.
 */
ready: boolean, 
/**
 * Dependencies: blockers that are not done yet (id + name). Drives the "waiting on X" line in
 * the detail pane. Empty means it can be started.
 */
blockedBy: Array<TaskRefDto>, 
/**
 * Where the task sits (with the project's display name), so the detail pane's project row
 * renders from real data. Absent when the task is unplaced (inbox).
 */
placement: PlacementDto | null, createdBy: ActorDto | null, 
/**
 * The decision records that motivated this task (cross-link). Symmetric with
 * `DecisionDto.linked_tasks`; drives navigation from the task detail view to the decision record.
 */
linkedDecisions: Array<DecisionRefDto>, 
/**
 * Those `linked_decisions` that are not settled yet as grounds. Together with `blocked_by` they
 * determine `ready` (both empty means ready). The reason a reservation was refused
 * (`not_ready`) only ever appears in a toast that vanishes in seconds, so we name the decisions
 * that are holding it back, letting the detail pane hold the same fact permanently.
 */
blockedByDecisions: Array<DecisionRefDto>, 
/**
 * The declared start day, when it is still ahead (`YYYY-MM-DD`) — the third reason `ready` is
 * false, beside `blocked_by` and `blocked_by_decisions`. Always serialized, `null` when the start
 * day is no reason, so every `ready: false` the GUI draws carries a reason it can name on screen.
 */
notStartedUntil: string | null, 
/**
 * Is the task still being put together — the fourth reason `ready` is false (`AMB-D-553`). A draft
 * is drawn on the board like any other card (`AMB-D-555`), so the card has to carry the reason it
 * cannot be picked up, the way `not_started_until` does for the third.
 */
draft: boolean, 
/**
 * Premises pinned on **after this task was reserved** (`AMB-D-366`, the holder-side surface): a
 * blocker or an unsettled decision added since it went `in_progress`, silently withdrawing readiness
 * the holder never asked to give up. Present only for an `in_progress` task that actually acquired
 * one — `null` for every other status and when nothing changed — so the surface (a chip on the row,
 * a firm warn when the holder leaves `in_progress`) draws exactly when it should.
 */
premiseChange?: PremiseChangeDto, 
/**
 * When the task was written (RFC3339 UTC). The detail pane's answer to "how long has this been
 * sitting here" — nothing else on the card dates the task itself.
 */
createdAt: string, 
/**
 * When the task was last written to (RFC3339 UTC). **Any** write moves it — a comment, a due date,
 * a title fix — so it dates the record, not the status: what a status last moved is
 * `status_changed_at`'s to say, and neither is a judgement input (`AMB-D-372`).
 */
updatedAt: string, };

/**
 * One git commit SHA recorded on a task. Amenbo keeps the SHA as an opaque string — it
 * never reads git, verifies the commit, or knows which forge it lives on; the AI does that with
 * `git show <sha>`. `createdByKind` is who recorded it (the GUI's actor is always human).
 */
export type TaskCommitDto = { id: number, 
/**
 * The full commit SHA, lower-case hex (40 for SHA-1, 64 for SHA-256).
 */
sha: string, createdByKind: "human" | "ai" | null, };

/**
 * One task × dimension assignment (`valueId` is set on the `dimensionId` axis). The detail pane's
 * assignment selects use it to reflect the current value.
 */
export type TaskDimensionAssignmentDto = { dimensionId: number, valueId: number, };

/**
 * What `task_page` returns: the task cards on the page, plus the total number of matches before
 * paging. The front end sizes its pager or virtual scroller from `total_matched` and draws only the
 * window in `tasks` (it never holds them all).
 */
export type TaskPageDto = { tasks: Array<TaskCardDto>, 
/**
 * Total number of matches, before paging (limit/offset) is applied.
 */
totalMatched: number, 
/**
 * The offset that was applied (how many were skipped).
 */
offset: number, 
/**
 * The limit that was applied (page size). None means no cap — everything from `offset` on.
 */
limit: number | null, };

/**
 * A reference to a task (id + title). The id is an integer key.
 */
export type TaskRefDto = { id: number, name: string, };

/**
 * The **update available** state, for the GUI. Takes the store's `version_status` and raises
 * `update_available` when upstream (the published `latest.json`) names a version newer than the one
 * running. That is what puts up the GUI's "an update is available" banner and its "open the
 * installer" affordance.
 */
export type VersionStatusDto = { 
/**
 * Version of the GUI binary that is running.
 */
appVersion: string, 
/**
 * A newer version exists in the published distribution.
 */
updateAvailable: boolean, 
/**
 * The version being offered (for display; the first one found). `None` means no update.
 */
newerVersion: string | null, };

/**
 * One agent a folder's pane could be opened with, and what the folder and this machine say about
 * it (`crate::wake`).
 */
export type WakeCandidateDto = { 
/**
 * The catalogued id, which is what a face hands back when the reader picks this one.
 */
id: string, 
/**
 * The product's own name for itself.
 */
label: string, 
/**
 * What it is started as — shown where it is missing, because that is the word to install.
 */
command: string, 
/**
 * Whether this folder shows a trace of the provider being used here.
 */
traced: boolean, 
/**
 * Whether this machine can start it. Never more than that: see `amenbo_core::wake`.
 */
installed: boolean, };

/**
 * Which agent a folder's pane opens with, and what to put to the reader when that is not settled.
 */
export type WakeDto = { 
/**
 * The folder this answers for, canonical — what the face opens the pane in, so that the pane
 * and the answer are about the same folder.
 *
 * Absent where the question was asked about a project rather than about one folder
 * ([`crate::wake::wake_choices`]): a project's folders are several, and none of them is the
 * one a pane that has not been opened yet will run in.
 */
folder?: string, 
/**
 * Every catalogued agent, in catalog order. The install notice is drawn from this, which is why
 * the ones this machine does not have are here too.
 */
candidates: Array<WakeCandidateDto>, 
/**
 * The ids worth offering, in catalog order. Empty means nothing on this machine can be started.
 */
offered: Array<string>, 
/**
 * The id to open with, when nothing needs asking. `None` with a non-empty `offered` is the
 * question; `None` with an empty one is the notice.
 */
settled?: string, 
/**
 * What this project has settled on **as written** ([`amenbo_core::config::Config::agent_for`]),
 * rather than what the rank arrives at.
 *
 * The two come apart on a machine with one agent installed, where `settled` names it and
 * nothing was ever kept. A face asking the reader to change the answer draws this: "nothing
 * kept" and "kept the only one there is" read the same off `settled` and are different answers
 * to the question being put.
 */
kept?: string, };
