#!/usr/bin/env python3
"""Bake the brand mark into the image set each surface needs.

The artwork is never touched. The origins in `assets/brand/` — the designer's paths on no ground —
are the only place a coordinate is written, and everything below them is derived. What this adds is
the packaging each surface demands and the mark itself does not carry: a tile with the corner radius
and the safe-area inset macOS lays its grid on, and the raster sizes `.icns`, `.ico` and a web page
are assembled from.

There are two origins per colour, because one drawing cannot serve every size. `mark.svg` is the
delivered artwork, and it is what everything above 32 pixels is baked from. `mark-small.svg` is the
same figure redrawn for a whole-pixel stroke, and it takes over at 32 and below — see its own header
for why, and `SMALL_MAX` below for where the line is drawn.

Run it from anywhere:

    make brand

The set it writes is tracked, because the bundlers read files and not a build step — so the images
are in the tree whether or not the machine cloning it can rasterize. That is also why nothing here
runs in CI: it wants a browser, a macOS `iconutil` and Pillow, none of which a merge should wait on.
Re-run it by hand when the origin changes, and commit what moves.

Needs macOS (`iconutil`), Google Chrome, and Pillow.
"""
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

try:
    from PIL import Image
except ModuleNotFoundError:  # pragma: no cover - the message is the whole handling
    sys.exit("Pillow is missing — `pip3 install --user Pillow`, then run this again")

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "assets" / "brand"
CHROME = pathlib.Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")

# The macOS icon grid: the tile fills 824 of the 1024 canvas, so a Dock tile stands the same height
# as its neighbours instead of towering over them. The corner radius is the ratio the platform's own
# icons keep.
SAFE = 824 / 1024
RADIUS = 232 / 1024

# Where the small origin takes over. At 32 pixels and below the delivered stroke is under a pixel
# wide and comes out grey, so those sizes are baked from `mark-small.svg` instead.
SMALL_MAX = 32

# At 16 pixels the tile gives up its margin as well. The safe area is a Dock convention, and a Dock
# is not where a 16-pixel icon appears — a browser tab and a taskbar are. Spending a fifth of the
# canvas on a margin there costs the mark the pixel its stroke needs, so below this the tile is
# full-bleed and the mark inside it is the small one at its design size.
FULL_BLEED_MAX = 16

# What each surface is assembled from. The app icon needs every size `.icns` and `.ico` name between
# them; the web set is the mark alone, down to the favicon.
ICON_SIZES = (16, 24, 32, 48, 64, 128, 256, 512, 1024)
WEB_SIZES = (16, 32, 64, 128, 512)

# `iconutil` reads an .iconset by filename, and the names are the contract: one entry per (size,
# label), with the @2x rows pointing at the pixel count twice their label.
ICONSET = (
    (16, "16x16"), (32, "16x16@2x"), (32, "32x32"), (64, "32x32@2x"),
    (128, "128x128"), (256, "128x128@2x"), (256, "256x256"), (512, "256x256@2x"),
    (512, "512x512"), (1024, "512x512@2x"),
)

# The sizes Windows reaches into an .ico for. One file holds them all, so a small shell icon and a
# large one in a properties dialog come out of the same asset.
ICO_SIZES = (16, 24, 32, 48, 64, 256)

GENERATED = "Generated by scripts/gen-brand.py — do not edit"


def inner_of(svg: str) -> tuple[str, str]:
    """An origin's viewBox and its drawing — everything between the `<svg>` tags but the title.

    The drawing is carried whole rather than picked apart, because the two origins are not built
    the same way: the delivered one is a single stroked group, the small one a stroked group and a
    filled one. Anything that reached in for the paths would have to know which it was holding.
    """
    box = re.search(r'viewBox="([^"]+)"', svg).group(1)
    body = re.search(r"</title>(.*)</svg>", svg, re.S).group(1)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    return box, body.strip("\n")


def widen_strokes(body: str, by: float) -> str:
    """Multiply every `stroke-width` in an embedded drawing.

    The inset shrinks the mark and its line with it, and the line is the one thing that must not
    shrink — it is already the first casualty at small sizes. So the weight is given back here,
    leaving the stroke the same fraction of the whole canvas it would be with no inset at all.
    """
    return re.sub(r'stroke-width="([\d.]+)"',
                  lambda m: f'stroke-width="{float(m.group(1)) * by:.6g}"', body)


def icon_svg(origin: str, tile: str, full_bleed: bool) -> str:
    """The app icon: the mark on its tile.

    The mark is placed through a nested `<svg>`, which is a viewport of its own — so the origin
    lands in the box named here whatever its own coordinates were, whether that is the delivered
    mark's or the small one's. That is what lets one function serve both.

    `full_bleed` drops the macOS safe-area margin, for the sizes where the margin costs more than
    the Dock convention is worth (see `FULL_BLEED_MAX`).
    """
    box, body = inner_of(origin)
    side = 1024 * (1 if full_bleed else SAFE)
    at = (1024 - side) / 2
    body = widen_strokes(body, 1024 / side)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <title>amenbo</title>
  <!-- {GENERATED} -->
  <rect x="{at}" y="{at}" width="{side}" height="{side}" rx="{1024 * RADIUS}" fill="{tile}"/>
  <svg x="{at}" y="{at}" width="{side}" height="{side}" viewBox="{box}">
{body}
  </svg>
</svg>
"""


def render(svg: pathlib.Path, out: pathlib.Path, size: int) -> None:
    """Rasterize `svg` at `size` on a transparent ground.

    A browser rather than a converter, because the browser is the renderer the mark is drawn for and
    the one every other surface will show it in — a converter agreeing with itself proves less than
    the engine agreeing with the page. It is pointed at a one-line page rather than the file, since
    that is where the size is stated in pixels.
    """
    with tempfile.TemporaryDirectory() as tmp:
        page = pathlib.Path(tmp) / "page.html"
        page.write_text(
            f'<style>html,body{{margin:0;background:transparent}}img{{width:{size}px;'
            f'height:{size}px;display:block}}</style><img src="{svg.resolve().as_uri()}">'
        )
        subprocess.run(
            [str(CHROME), "--headless", "--disable-gpu", "--hide-scrollbars",
             "--allow-file-access-from-files", "--default-background-color=00000000",
             f"--window-size={size},{size}", f"--screenshot={out}", str(page)],
            check=True, capture_output=True,
        )


def bake_app_icon(out: pathlib.Path, large: str, small: str, tile: str) -> None:
    """One app icon, in every form a bundler asks for: the SVGs, the rasters, `.icns` and `.ico`.

    Three icon SVGs are kept beside the rasters rather than thrown away, because each is what one
    band of sizes was actually baked from: `icon.svg` above 32, `icon-small.svg` at 24 and 32, and
    `icon-small-full.svg` at 16, where the tile gives up its margin.
    """
    out.mkdir(parents=True, exist_ok=True)
    variants = {
        "icon.svg": icon_svg(large, tile, full_bleed=False),
        "icon-small.svg": icon_svg(small, tile, full_bleed=False),
        "icon-small-full.svg": icon_svg(small, tile, full_bleed=True),
    }
    for name, svg in variants.items():
        (out / name).write_text(svg)
    for size in ICON_SIZES:
        if size <= FULL_BLEED_MAX:
            name = "icon-small-full.svg"
        elif size <= SMALL_MAX:
            name = "icon-small.svg"
        else:
            name = "icon.svg"
        render(out / name, out / f"icon-{size}.png", size)

    iconset = out / "icon.iconset"
    iconset.mkdir(exist_ok=True)
    for size, label in ICONSET:
        shutil.copy(out / f"icon-{size}.png", iconset / f"icon_{label}.png")
    subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(out / "icon.icns")], check=True)
    shutil.rmtree(iconset)

    Image.open(out / "icon-256.png").save(out / "icon.ico", sizes=[(s, s) for s in ICO_SIZES])


def bake_web(out: pathlib.Path, origins: dict[str, tuple[pathlib.Path, pathlib.Path]]) -> None:
    """The mark alone, at the sizes a page reaches for, on whatever ground the page already has.

    A favicon is the one place the small origin earns its keep outright: 16 and 32 are the two
    sizes a browser tab picks from.
    """
    out.mkdir(parents=True, exist_ok=True)
    for stem, (large, small) in origins.items():
        for size in WEB_SIZES:
            render(small if size <= SMALL_MAX else large, out / f"{stem}-{size}.png", size)


def main() -> None:
    if not CHROME.exists():
        sys.exit(f"Google Chrome is not at {CHROME} — it is the rasterizer this script uses")

    black, black_small = BRAND / "mark.svg", BRAND / "mark-small.svg"
    white, white_small = BRAND / "mark-inv.svg", BRAND / "mark-small-inv.svg"

    # The production icon is the black mark on a white tile; the dev icon is the inverse, so the two
    # are told apart in a Dock holding both.
    bake_app_icon(BRAND / "app-icon", black.read_text(), black_small.read_text(), "#ffffff")
    bake_app_icon(BRAND / "app-icon-dev", white.read_text(), white_small.read_text(), "#000000")
    bake_web(BRAND / "web", {"mark": (black, black_small), "mark-inv": (white, white_small)})

    print(f"baked into {BRAND}")


if __name__ == "__main__":
    main()
