#!/usr/bin/env python3
"""Bake the brand mark into the image set each surface needs.

The artwork is never touched. The two origins in `assets/brand/` — `mark.svg` and `mark-inv.svg`,
the designer's paths on no ground — are the only place a coordinate is written, and everything
below them is derived. What this adds is the packaging each surface demands and the mark itself
does not carry: a tile with the corner radius and the safe-area inset macOS lays its grid on, and
the raster sizes `.icns`, `.ico` and a web page are assembled from.

Run it from anywhere:

    make brand

The set it writes is tracked, because the bundlers read files and not a build step — so the images
are in the tree whether or not the machine cloning it can rasterize. That is also why nothing here
runs in CI: it wants a browser, a macOS `iconutil` and Pillow, none of which a merge should wait on.
Re-run it by hand when the origin changes, and commit what moves.

Needs macOS (`iconutil`), Google Chrome, and Pillow.
"""
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

try:
    from PIL import Image
except ModuleNotFoundError:  # pragma: no cover - the message is the whole handling
    sys.exit("Pillow is missing — `pip3 install --user Pillow`, then run this again")

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "assets" / "brand"
CHROME = pathlib.Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")

# The macOS icon grid: the tile fills 824 of the 1024 canvas, so a Dock tile stands the same height
# as its neighbours instead of towering over them. The corner radius is the ratio the platform's own
# icons keep.
SAFE = 824 / 1024
RADIUS = 232 / 1024

# What each surface is assembled from. The app icon needs every size `.icns` and `.ico` name between
# them; the web set is the mark alone, down to the favicon.
ICON_SIZES = (16, 24, 32, 48, 64, 128, 256, 512, 1024)
WEB_SIZES = (16, 32, 64, 128, 512)

# `iconutil` reads an .iconset by filename, and the names are the contract: one entry per (size,
# label), with the @2x rows pointing at the pixel count twice their label.
ICONSET = (
    (16, "16x16"), (32, "16x16@2x"), (32, "32x32"), (64, "32x32@2x"),
    (128, "128x128"), (256, "128x128@2x"), (256, "256x256"), (512, "256x256@2x"),
    (512, "512x512"), (1024, "512x512@2x"),
)

# The sizes Windows reaches into an .ico for. One file holds them all, so a small shell icon and a
# large one in a properties dialog come out of the same asset.
ICO_SIZES = (16, 24, 32, 48, 64, 256)

GENERATED = "Generated by scripts/gen-brand.py from assets/brand/mark.svg — do not edit"


def paths_of(svg: str) -> str:
    """The drawing itself: every `<path>` in the file, indented to sit inside a group."""
    return "\n".join("    " + p for p in re.findall(r"<path [^>]*/>", svg))


def icon_svg(paths: str, stroke: str, tile: str) -> str:
    """The app icon: the mark on its tile, inset to the macOS safe area.

    The stroke width is divided by the same factor the group is scaled by, so the line comes out the
    weight the origin drew it at rather than the weight the inset would shrink it to.
    """
    side = 64 * SAFE
    half = side / 2
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="-32 -32 64 64" width="1024" height="1024">
  <title>amenbo</title>
  <!-- {GENERATED} -->
  <rect x="{-half}" y="{-half}" width="{side}" height="{side}" rx="{64 * RADIUS}" fill="{tile}"/>
  <g transform="scale({SAFE})">
    <g fill="none" stroke="{stroke}" stroke-width="{1 / SAFE}" stroke-linecap="butt" stroke-linejoin="miter">
{paths}
    </g>
  </g>
</svg>
"""


def render(svg: pathlib.Path, out: pathlib.Path, size: int) -> None:
    """Rasterize `svg` at `size` on a transparent ground.

    A browser rather than a converter, because the browser is the renderer the mark is drawn for and
    the one every other surface will show it in — a converter agreeing with itself proves less than
    the engine agreeing with the page. It is pointed at a one-line page rather than the file, since
    that is where the size is stated in pixels.
    """
    with tempfile.TemporaryDirectory() as tmp:
        page = pathlib.Path(tmp) / "page.html"
        page.write_text(
            f'<style>html,body{{margin:0;background:transparent}}img{{width:{size}px;'
            f'height:{size}px;display:block}}</style><img src="{svg.resolve().as_uri()}">'
        )
        subprocess.run(
            [str(CHROME), "--headless", "--disable-gpu", "--hide-scrollbars",
             "--allow-file-access-from-files", "--default-background-color=00000000",
             f"--window-size={size},{size}", f"--screenshot={out}", str(page)],
            check=True, capture_output=True,
        )


def bake_app_icon(out: pathlib.Path, paths: str, stroke: str, tile: str) -> None:
    """One app icon, in every form a bundler asks for: the SVG, the rasters, `.icns` and `.ico`."""
    out.mkdir(parents=True, exist_ok=True)
    svg = out / "icon.svg"
    svg.write_text(icon_svg(paths, stroke, tile))
    for size in ICON_SIZES:
        render(svg, out / f"icon-{size}.png", size)

    iconset = out / "icon.iconset"
    iconset.mkdir(exist_ok=True)
    for size, label in ICONSET:
        shutil.copy(out / f"icon-{size}.png", iconset / f"icon_{label}.png")
    subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(out / "icon.icns")], check=True)
    shutil.rmtree(iconset)

    Image.open(out / "icon-256.png").save(out / "icon.ico", sizes=[(s, s) for s in ICO_SIZES])


def bake_web(out: pathlib.Path, origins: dict[str, pathlib.Path]) -> None:
    """The mark alone, at the sizes a page reaches for, on whatever ground the page already has."""
    out.mkdir(parents=True, exist_ok=True)
    for stem, origin in origins.items():
        for size in WEB_SIZES:
            render(origin, out / f"{stem}-{size}.png", size)


def main() -> None:
    if not CHROME.exists():
        sys.exit(f"Google Chrome is not at {CHROME} — it is the rasterizer this script uses")

    black = BRAND / "mark.svg"
    white = BRAND / "mark-inv.svg"

    # The production icon is the black mark on a white tile; the dev icon is the inverse, so the two
    # are told apart in a Dock holding both.
    bake_app_icon(BRAND / "app-icon", paths_of(black.read_text()), "#000000", "#ffffff")
    bake_app_icon(BRAND / "app-icon-dev", paths_of(white.read_text()), "#ffffff", "#000000")
    bake_web(BRAND / "web", {"mark": black, "mark-inv": white})

    print(f"baked into {BRAND}")


if __name__ == "__main__":
    main()
