// THE WIRING SEAM (read side).
//
// At startup, one round trip to core (the Tauri command `snapshot`) fetches the read data every
// screen needs and parks it in a module cache. Readers read that cache **synchronously**. Outside
// Tauri (a plain `npm run dev` browser) it falls back to the mock fixtures, so the frontend can be
// iterated on its own.
//
// Invariant: only domain state (the shared data whose source of truth is SQLite) belongs on
// `Snapshot`. Not UI-local state (selection, tab, filter, draft — React useState), and not
// device-local UI preferences (theme — localStorage): putting them here would drag every view
// through the wholesale swap that each write performs. Nor do the bulk task and decision rows of
// the list and board live in the cache — the `tasks`/`decisions` fields are **for the browser mock
// fallback only** and core leaves them empty on the Tauri path, where the paging hooks in
// `core/reads` (task_page/decision_page/tasks_by_ids/decisions_by_ids) fetch a window at a time and
// keep memory bounded.
import type { TaskCard } from "../mock/types";
import type {
  DecisionRefDto,
  DecisionDto,
  DoctorIssueDto,
  StartupHealthDto,
  VersionStatusDto,
  Snapshot as SnapshotDto,
} from "../bindings/bindings";
import { invalidateAllQueries, invalidateScopes } from "./query";
import { drainChanges, takeChangeCursor } from "./changes";
import { applyPerfConfig, invoke } from "./ipc";
import { clearDismissedUpdate } from "./updateDismissed";

// The wire types are generated by ts-rs. Re-export them under the app's names, and extend only the
// types that gain a client-only field.
/** A cross-link to a decision or task (id, display name, and the conversational ref `#N`). */
export type DecisionRef = DecisionRefDto;
export type DecisionStatus = DecisionDto["status"];
/** One decision record. */
export type Decision = DecisionDto;
// Findings from the startup integrity check. The GUI surfaces any warning in a read-only banner and
// never repairs on its own. An issue is the same type the doctor surface uses: no prose of its own,
// the surface composes the sentence from kind and params.
export type StartupIssue = DoctorIssueDto;
export type StartupHealth = StartupHealthDto;

/**
 * The GUI snapshot. Its wire half is the generated `SnapshotDto` (roster, projects, activity, config
 * and so on). `tasks`/`decisions` are **for the browser mock fallback only** — core never sends
 * them, and `loadSnapshot` fills them with empty arrays to satisfy the non-optional type. The Tauri
 * path never reads those two; the paging hooks fetch a window at a time, keeping memory bounded.
 */
export type Snapshot = SnapshotDto & {
  tasks: TaskCard[];
  decisions: Decision[];
};

const EMPTY: Snapshot = {
  language: null,
  onboarded: true, // before load, and in the browser, no first-run flow (the Tauri snapshot overwrites this)
  roster: [],
  projects: [],
  tasks: [],
  decisions: [],
  activity: [],
  startupHealth: { issues: [] },
  versionStatus: { appVersion: "", updateAvailable: false, newerVersion: null },
  perfLog: null,
  updateCheck: true,
};

let cache: Snapshot = EMPTY;
const listeners = new Set<() => void>();

/**
 * The payload announcing the moment an outside write (AI or CLI) landed in the GUI. It carries the
 * bare minimum a visual effect needs to distinguish why and when — never the effect itself.
 */
export interface StoreChangeReflected {
  /** Where it came from: `live` = the watcher's normal targeted path (a scope), `gap` = a full re-read after a detected gap. */
  reason: "live" | "gap";
  /** When it landed (epoch ms). */
  at: number;
}

// Subscribers to outside writes landing — deliberately separate from the domain snapshot's
// `listeners`, so a visual effect does not ride along with every domain re-render.
const reflectionListeners = new Set<(r: StoreChangeReflected) => void>();

/**
 * Subscribes to the moment an outside write (AI or CLI) lands in the GUI — the substrate every
 * visual effect builds on. It fires **only for outside writes**: `watchStore` has already filtered
 * our own via `sig === lastSignature`. Outside Tauri `watchStore` is a no-op, so nothing ever
 * fires. The returned function unsubscribes.
 */
export function subscribeStoreChangeReflected(fn: (r: StoreChangeReflected) => void): () => void {
  reflectionListeners.add(fn);
  return () => reflectionListeners.delete(fn);
}

/**
 * Notifies subscribers that an outside write landed. **`watchStore` is the only caller** (both the
 * gap and the normal path), and it calls this only after filtering out our own writes — which is
 * what makes the signal mean "outside". No other module may call it, or that meaning is lost.
 */
export function notifyStoreChangeReflected(r: StoreChangeReflected): void {
  for (const l of reflectionListeners) l(r);
}

// Generation counter for data that can change who is *in* the mailbox. `loadSnapshot` and
// `applySnapshot` (a re-read of real domain data) and `notifyInboxChanged` (a device-local inbox
// archive change) bump it. `notifyDataChanged` — the read-receipt path, i.e. clicking an item read
// — deliberately **does not**: marking read leaves membership untouched, so there is nothing to
// wake the mailbox for. The mailbox re-derives its set of inbox ids only when this generation
// moves, which is what stops a recompute on every read click.
let inboxDataGeneration = 0;

/** The mailbox-affecting data generation: bumped by a data re-read or an archive change, never by marking read. */
export function getInboxDataGeneration(): number {
  return inboxDataGeneration;
}

/** Whether we are running inside the Tauri shell — i.e. whether core can be invoked at all. */
export function inTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/** The current snapshot — a synchronous read, empty until the first load. */
export function getSnapshot(): Snapshot {
  return cache;
}

/** Subscribes to snapshot updates (this is what React's useSyncExternalStore hangs off). */
export function subscribe(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/** Swaps the cache and notifies subscribers — for the return value of a write command, or a mock mutation. */
export function applySnapshot(next: Snapshot): void {
  cache = next;
  inboxDataGeneration++; // real data was swapped in, so the mailbox must re-derive its set.
  for (const l of listeners) l();
}

/**
 * Notifies subscribers without touching the cache — a nudge to refetch. Views pull task_page on
 * demand, so this is the way to re-run the subscribing hooks after a state change that never rides
 * on the snapshot at all (the device-local read last-seen, for instance, which shifts the inbox's
 * unread set). It **does not change inbox membership**, so `inboxDataGeneration` stays put and the
 * mailbox does not recompute.
 */
export function notifyDataChanged(): void {
  for (const l of listeners) l();
}

/**
 * Notifies that the device-local inbox archive changed. Archiving is the one way out of the inbox,
 * so membership shrinks: bump `inboxDataGeneration` and let the mailbox re-derive its badge count.
 * This differs from `notifyDataChanged` in exactly that — the change reaches the inbox.
 */
export function notifyInboxChanged(): void {
  inboxDataGeneration++;
  for (const l of listeners) l();
}

// The store mtime signature this device saw last (what the store_signature command returns),
// refreshed on every loadSnapshot. When a store-changed arrives and the signature still matches,
// the mtime moved because *we* wrote — the result is already on screen — and the refetch is
// suppressed. This is the watcher's dedup of our own writes.
let lastSignature: string | null = null;

/**
 * Store subscription: when core emits `store-changed` — another process (AI, CLI) wrote — **read the
 * change feed from the cursor onward only**, fold the changed rows' datasets into scopes, and
 * refetch just the queries that touch those scopes. The read is O(changes): `store-changed` is
 * nothing but a wake-up saying *something* moved, and **what moved is the feed's word** (it is never
 * in the event payload). When the feed cannot say — it has expired, the file was replaced wholesale,
 * a dataset does not fold — fall back to the full re-read of `reconcile("gap")`: an invalidation
 * signal is not truth, and when in doubt reconcile from the source of truth (see `drainChanges`).
 * Changes caused by our own writes — signature identical to the last load — are filtered out here:
 * the write's ack already put the result on screen, and the `loadSnapshot` at the end of that ack
 * has already advanced the cursor past our own rows in the feed. Inbox membership only ever moves on
 * the task side, so the generation is bumped only when `tasks` is among the scopes — an outside
 * write touching decisions or attachments alone must not trigger a mailbox recompute. Outside Tauri
 * this does nothing. The returned function unsubscribes.
 */
export async function watchStore(): Promise<() => void> {
  if (!inTauri()) return () => {};
  const { listen } = await import("@tauri-apps/api/event");
  return listen("store-changed", async () => {
    let sig: string | null = null;
    try {
      sig = await invoke<string>("store_signature");
    } catch {
      sig = null; // no signature: fall to the safe side and refetch.
    }
    if (sig !== null && sig === lastSignature) return; // our own write, already on screen.
    const { scopes, gap } = await drainChanges();
    if (gap) {
      await reconcile("gap");
      notifyStoreChangeReflected({ reason: "gap", at: Date.now() });
      return;
    }
    await loadSnapshot({ inboxAffected: scopes.has("tasks") });
    invalidateScopes(scopes);
    notifyStoreChangeReflected({ reason: "live", at: Date.now() });
  });
}

/**
 * What can trigger a reconcile. Reconcile is the insurance that closes the holes targeted
 * invalidation can miss, by re-reading from the source of truth (SQLite), and there are exactly
 * three triggers: focus (the window came back — catch up on `store-changed` events that never
 * arrived while backgrounded), manual (the refresh button in the TopBar), and gap (the watcher
 * could not narrow to scopes; raised by `watchStore`). Pinned as a type so observability and
 * fault-injection tests can name the last reason.
 */
export type ReconcileReason = "focus" | "manual" | "gap";

let lastReconcile: { reason: ReconcileReason; at: number } | null = null;

/** The reason and time (epoch ms) of the last reconcile, for observability and fault-injection tests; null until one runs. */
export function getLastReconcile(): { reason: ReconcileReason; at: number } | null {
  return lastReconcile;
}

// The reconcile in flight (multiple wake-ups fold into one) and whether another request arrived
// while it ran (run exactly once more afterwards).
let reconcileInFlight: Promise<void> | null = null;
let reconcilePending = false;
// Whether any of the folded wake-ups carried a reason that demands a full re-read (manual, gap). A
// path of nothing but focus can stay a no-op when the signature has not moved; a mix falls to the
// safe side and re-reads everything.
let reconcileForceFull = false;

/**
 * Re-reads state from the source of truth — the snapshot region via `loadSnapshot`, the live queries
 * via invalidation. The trigger decides the granularity:
 *   - manual / gap … a **full re-read** (`invalidateAllQueries`) that trusts no invalidation signal.
 *   - focus … catching up on store-changed events missed while backgrounded. If the store signature
 *     has not moved since the last load, **do nothing** — no indiscriminate invalidation.
 * Overlapping wake-ups (focus and visibility firing together, say) join the one in flight, and a
 * request that arrives during it runs exactly once more afterwards, so nothing is dropped.
 */
export async function reconcile(reason: ReconcileReason): Promise<void> {
  lastReconcile = { reason, at: Date.now() };
  if (reason !== "focus") reconcileForceFull = true; // remember that a full re-read is owed.
  if (reconcileInFlight) {
    reconcilePending = true;
    return reconcileInFlight;
  }
  reconcileInFlight = (async () => {
    try {
      do {
        reconcilePending = false;
        const full = reconcileForceFull;
        reconcileForceFull = false;
        if (full) {
          await loadSnapshot(); // members/projects/activity/config… and lastSignature moves to now.
          invalidateAllQueries(); // every live query — list, board, single, aggregate, decision — re-reads.
        } else {
          await focusCatchUp(); // focus-only path: the signature decides between no-op and a re-read.
        }
      } while (reconcilePending);
    } finally {
      reconcileInFlight = null;
    }
  })();
  return reconcileInFlight;
}

/**
 * One pass of the focus path. Re-reads the store signature and compares it with the last load:
 *   - unchanged → read nothing back (no loadSnapshot, no invalidation, so nothing wakes the mailbox either). The one
 *     thing still asked is the update state, which does not live in the store and so has no signature to move.
 *   - changed, or no signature at all → re-read the snapshot region and every live query. There is
 *     one store, so there is no "where" to narrow by: the signature says only whether it moved.
 * Outside Tauri there is no signature, so this always re-reads everything.
 */
async function focusCatchUp(): Promise<void> {
  let cur: string | null = null;
  if (inTauri()) {
    try {
      cur = await invoke<string>("store_signature");
    } catch {
      cur = null; // no signature: fall to the safe side and re-read everything.
    }
  }
  if (cur !== null && lastSignature !== null && cur === lastSignature) {
    // Nothing moved on disk, so there is no snapshot to re-read — but "is there a newer release" does not live in
    // the store, and this is the one moment we get to ask it: the user just came back to the app. Someone who only
    // reads never moves the signature, and would otherwise never be told about an update again after launch.
    await refreshVersionStatus();
    return;
  }
  await loadSnapshot(); // this also moves lastSignature to the current value.
  invalidateAllQueries();
}

/**
 * Re-asks core for the update-available state alone and patches it into the snapshot cache. The TTL lives in core
 * (24h), so within the window this answers from its cache without traffic — which is why it is safe to call on every
 * focus return. Failure is silent, the same as everywhere else the update check is surfaced: not being able to say
 * whether an update exists must never get in the way. Outside Tauri there is nothing to ask.
 */
async function refreshVersionStatus(): Promise<void> {
  if (!inTauri()) return;
  let next: VersionStatusDto;
  try {
    next = await invoke<VersionStatusDto>("version_status");
  } catch {
    return; // silent: an update check does not get in the way of the real work.
  }
  const cur = cache.versionStatus;
  if (cur.updateAvailable === next.updateAvailable && cur.newerVersion === next.newerVersion) return; // nothing to redraw.
  cache = { ...cache, versionStatus: next };
  notifyDataChanged(); // the banner is the only reader; inbox membership is untouched.
}

/**
 * The app menu's manual "check for updates" action. Unlike `refreshVersionStatus` (TTL-cached, fired on focus return),
 * this asks core for a **fresh** check that bypasses the cache and the update_check toggle (`check_updates_fresh`),
 * because the user asked explicitly — so it works even for someone who turned automatic checking off. It patches the
 * result into the snapshot cache so the existing update banner reflects it (clearing any prior dismissal when it finds
 * one, so an explicit check surfaces the offer regardless), and returns which of the three outcomes to show as the
 * menu's own transient feedback. Never throws; outside Tauri there is nothing upstream to ask.
 */
export async function checkForUpdatesFresh(): Promise<"available" | "uptodate" | "error"> {
  if (!inTauri()) return "uptodate";
  let next: VersionStatusDto;
  try {
    next = await invoke<VersionStatusDto>("check_updates_fresh");
  } catch {
    return "error"; // the query failed (network, timeout); tell the user rather than claim it is up to date.
  }
  const cur = cache.versionStatus;
  if (
    cur.updateAvailable !== next.updateAvailable ||
    cur.newerVersion !== next.newerVersion ||
    cur.appVersion !== next.appVersion
  ) {
    cache = { ...cache, versionStatus: next };
    notifyDataChanged();
  }
  if (next.updateAvailable) {
    clearDismissedUpdate();
    return "available";
  }
  return "uptodate";
}

// Throttle window for a burst of focus returns, matched to the watcher's 1.5s wake interval. manual and gap are never throttled.
const FOCUS_RECONCILE_THROTTLE_MS = 1500;
let lastFocusReconcileAt = 0;

/**
 * Wires up the one reconcile trigger the DOM can give us: the window regaining focus. The other two
 * call `reconcile` directly and from elsewhere — manual from the TopBar's refresh button, gap from
 * `watchStore`. Focus is caught both via visibilitychange→visible and via window focus, and a burst
 * of them is throttled. The DOM path works outside Tauri too. The returned function removes every
 * listener.
 */
export function installReconcileTriggers(): () => void {
  const onFocus = () => {
    const now = Date.now();
    if (now - lastFocusReconcileAt < FOCUS_RECONCILE_THROTTLE_MS) return;
    lastFocusReconcileAt = now;
    void reconcile("focus");
  };
  const onVisible = () => {
    if (typeof document !== "undefined" && document.visibilityState === "visible") onFocus();
  };
  const hasDoc = typeof document !== "undefined";
  const hasWin = typeof window !== "undefined";
  if (hasDoc) document.addEventListener("visibilitychange", onVisible);
  if (hasWin) window.addEventListener("focus", onFocus);
  return () => {
    if (hasDoc) document.removeEventListener("visibilitychange", onVisible);
    if (hasWin) window.removeEventListener("focus", onFocus);
  };
}

/** Re-reads the store mtime signature from core and keeps it — this is what dedup compares against. */
async function refreshSignature(): Promise<void> {
  if (!inTauri()) return;
  try {
    lastSignature = await invoke<string>("store_signature");
  } catch {
    lastSignature = null;
  }
}

/** Granularity of a `loadSnapshot`. By default it counts as inbox-affecting — a wholesale re-read. */
export interface LoadOptions {
  /**
   * Whether this re-read can change inbox membership (default true). When false, `inboxDataGeneration`
   * does not move and the mailbox does not recompute — a change to decisions or attachments alone
   * must not stoke an inbox recompute.
   */
  inboxAffected?: boolean;
}

/**
 * Re-reads from core (or the fixtures), swaps the cache and notifies subscribers. The change feed's
 * position is taken **before** the store is read, not after: a change that slips into the gap would
 * otherwise land behind the cursor and be lost forever. Taking it first can only make a change show
 * up twice, which is the harmless direction. Core returns no tasks/decisions rows, so they are
 * filled with empty arrays to satisfy the non-optional type — the Tauri path reads neither, and the
 * paging hooks fetch a window at a time.
 */
export async function loadSnapshot(opts: LoadOptions = {}): Promise<void> {
  if (inTauri()) {
    await takeChangeCursor();
    const snap = await invoke<Snapshot>("snapshot");
    cache = { ...snap, tasks: snap.tasks ?? [], decisions: snap.decisions ?? [] };
    applyPerfConfig(cache.perfLog);
    await refreshSignature();
  } else {
    // Browser fallback: build a snapshot of the same shape out of the mock fixtures.
    const fix = await import("../mock/data");
    cache = {
      language: "ja", // the browser fallback runs a Japanese UI (frontend-only iteration)
      onboarded: true, // no first-run flow when iterating in the browser
      roster: fix.roster,
      projects: fix.projects,
      tasks: fix.tasks,
      decisions: [], // the mock fixtures carry no decisions
      activity: fix.activity,
      startupHealth: { issues: [] }, // no warnings when iterating in the browser
      versionStatus: { appVersion: "", updateAvailable: false, newerVersion: null }, // and no update check either (the browser fallback asks nothing upstream)
      perfLog: null, // in the browser this is on by default in dev (ipc decides via import.meta.env.DEV)
      updateCheck: true,
    };
  }
  // Real data came back from the source of truth, so the mailbox owes itself a re-derive — unless the caller said this re-read cannot touch membership.
  if (opts.inboxAffected ?? true) inboxDataGeneration++;
  for (const l of listeners) l();
}
